const localized = {
  type: 'object',
  required: ['en', 'it'],
  properties: { en: { type: 'string' }, it: { type: 'string' } },
  additionalProperties: false,
} as const;

export const pressKitSchemas = {
  'press-kit': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit/v1',
    title: 'PolicyWatcher Press Kit payload',
    type: 'object',
    required: ['schema', 'schemaVersion', 'generatedAt', 'canonicalUrl', 'product', 'facts', 'claims', 'assets', 'packages', 'releases', 'boundaries'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/press-kit/v1' },
      schemaVersion: { type: 'string' },
      generatedAt: { type: 'string', format: 'date' },
      canonicalUrl: { type: 'string', format: 'uri' },
      product: { type: 'object' }, facts: { type: 'array' }, claims: { type: 'array' }, assets: { type: 'array' }, packages: { type: 'array' }, releases: { type: 'array' }, boundaries: { type: 'array', items: { type: 'string' } },
    },
  },
  'press-kit-asset-manifest': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-asset-manifest/v1',
    title: 'PolicyWatcher Press Kit asset manifest',
    type: 'object',
    required: ['schemaVersion', 'generatedAt', 'release', 'contentCredentials', 'assets'],
    properties: { schemaVersion: { type: 'string' }, generatedAt: { type: 'string', format: 'date' }, release: { type: 'string' }, contentCredentials: { const: 'not-attached' }, assets: { type: 'array', items: { type: 'object', required: ['filename', 'mediaType', 'bytes', 'sha256'], properties: { filename: { type: 'string' }, mediaType: { type: 'string' }, bytes: { type: 'integer', minimum: 0 }, sha256: { type: 'string', pattern: '^[a-f0-9]{64}$' }, creditLine: { type: 'string' }, rightsUrl: { type: 'string' } } } } },
  },
  'press-kit-package-manifest': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-package-manifest/v1',
    title: 'PolicyWatcher Press Kit package manifest',
    type: 'object',
    required: ['schemaVersion', 'generatedAt', 'release', 'packages'],
    properties: { schemaVersion: { type: 'string' }, generatedAt: { type: 'string', format: 'date' }, release: { type: 'string' }, packages: { type: 'array', items: { type: 'object', required: ['locale', 'filename', 'bytes', 'sha256'], properties: { locale: { enum: ['en', 'it'] }, filename: { type: 'string' }, bytes: { type: 'integer' }, sha256: { type: 'string', pattern: '^[a-f0-9]{64}$' } } } } },
  },
  'press-kit-media-metadata': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-media-metadata/v1',
    title: 'PolicyWatcher Press Kit media metadata',
    type: 'object',
    required: ['schemaVersion', 'standard', 'contentCredentials', 'assets'],
    properties: { schemaVersion: { type: 'string' }, standard: { const: 'IPTC Photo Metadata 2025.1' }, contentCredentials: { const: 'not-attached' }, vectorMasterAvailable: { type: 'boolean' }, assets: { type: 'object', additionalProperties: { type: 'object', properties: { title: localized, description: localized, alt: localized, usage: localized } } } },
  },
  'press-kit-data-snapshot': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-data-snapshot/v1',
    title: 'PolicyWatcher configured-scope data snapshot',
    type: 'object',
    required: ['snapshotId', 'asOf', 'generatedAt', 'facts', 'boundary'],
    properties: { snapshotId: { type: 'string' }, asOf: { type: 'string', format: 'date' }, generatedAt: { type: 'string', format: 'date' }, facts: { type: 'array', items: { type: 'object', required: ['id', 'value', 'unit', 'scope'], properties: { id: { type: 'string' }, value: { type: 'string' }, unit: { type: 'string' }, scope: { type: 'string' } } } }, boundary: { type: 'string' } },
  },
  'editorial-story-pack': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/editorial-story-pack/v1',
    title: 'PolicyWatcher Editorial Story Pack manifest',
    type: 'object',
    required: ['schema', 'schemaVersion', 'storySlug', 'storyVersion', 'generatedAt', 'asOf', 'locale', 'canonicalUrl', 'claimIds', 'sourceHrefs', 'files', 'boundary'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/editorial-story-pack/v1' },
      schemaVersion: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+$' },
      storySlug: { type: 'string' },
      storyVersion: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+$' },
      generatedAt: { type: 'string', format: 'date' },
      asOf: { type: 'string', format: 'date' },
      locale: { enum: ['en', 'it'] },
      canonicalUrl: { type: 'string', format: 'uri' },
      claimIds: { type: 'array', items: { type: 'string' }, uniqueItems: true },
      sourceHrefs: { type: 'array', items: { type: 'string' }, uniqueItems: true },
      files: { type: 'array', items: { type: 'string' }, uniqueItems: true },
      boundary: { type: 'string' },
    },
    additionalProperties: false,
  },
  'press-coverage': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-coverage/v1',
    title: 'PolicyWatcher public press coverage registry',
    type: 'object',
    required: ['schema', 'schemaVersion', 'asOf', 'canonicalUrl', 'boundary', 'summary', 'records'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/press-coverage/v1' },
      schemaVersion: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+$' },
      asOf: { type: 'string', format: 'date' },
      canonicalUrl: { type: 'string', format: 'uri' },
      boundary: { type: 'string' },
      summary: {
        type: 'object',
        required: ['total', 'sourceLinked', 'editorial', 'professionalPosts', 'byLanguage'],
        properties: {
          total: { type: 'integer', minimum: 0 },
          sourceLinked: { type: 'integer', minimum: 0 },
          editorial: { type: 'integer', minimum: 0 },
          professionalPosts: { type: 'integer', minimum: 0 },
          byLanguage: { type: 'object', required: ['en', 'it'], properties: { en: { type: 'integer', minimum: 0 }, it: { type: 'integer', minimum: 0 } }, additionalProperties: false },
        },
        additionalProperties: false,
      },
      records: {
        type: 'array',
        items: {
          type: 'object',
          required: ['id', 'sourceName', 'platform', 'kind', 'language', 'publishedDate', 'datePrecision', 'recordedAt', 'reviewedAt', 'title', 'titleStatus', 'summary', 'sourceUrl', 'relationship', 'recordStatus', 'dateLabel', 'citation'],
          properties: {
            id: { type: 'string' }, sourceName: { type: 'string' }, platform: { type: 'string' },
            kind: { enum: ['editorial-article', 'newsletter-article', 'professional-post'] },
            language: { enum: ['en', 'it'] }, publishedDate: { type: 'string', pattern: '^\\d{4}-\\d{2}$' },
            datePrecision: { const: 'month' }, recordedAt: { type: 'string', format: 'date' }, reviewedAt: { type: 'string', format: 'date' },
            title: { type: 'string' }, titleStatus: { enum: ['publisher-supplied', 'registry-description'] }, summary: { type: 'string' },
            sourceUrl: { type: 'string', format: 'uri' }, relationship: { enum: ['external editorial reference', 'external professional reference'] },
            recordStatus: { const: 'source-linked' }, dateLabel: { type: 'string' }, citation: { type: 'string' },
          },
        },
      },
    },
    additionalProperties: false,
  },
  'evidence-packet': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/evidence-packet/v1',
    title: 'PolicyWatcher change-bound evidence packet',
    type: 'object',
    required: ['schema', 'schemaVersion', 'mappingVersion', 'changeId', 'screeningDate', 'publicationGate', 'company', 'policy', 'sourceConfidence', 'snapshots', 'assessment', 'governance', 'humanReviewQuestions', 'methodologyUrl', 'changeUrl', 'boundary', 'contentDigest'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/evidence-packet/v1' },
      schemaVersion: { const: '1.0.0' },
      mappingVersion: { type: 'string' },
      changeId: { type: 'string', format: 'uuid' },
      screeningDate: { type: 'string', format: 'date-time' },
      publicationGate: { enum: ['published', 'withheld'] },
      company: { type: 'object' },
      policy: { type: 'object' },
      sourceConfidence: { type: 'object' },
      snapshots: { type: 'object' },
      assessment: { type: 'object' },
      governance: { type: 'object' },
      humanReviewQuestions: { type: 'array', items: { type: 'string' }, minItems: 1 },
      methodologyUrl: { type: 'string', format: 'uri' },
      changeUrl: { type: 'string', format: 'uri' },
      boundary: { type: 'string' },
      contentDigest: { type: 'string', pattern: '^[a-f0-9]{64}$' },
    },
  },
  'evidence-collection': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/evidence-collection/v1',
    title: 'PolicyWatcher shareable evidence collection',
    type: 'object',
    required: ['schema', 'schemaVersion', 'asOf', 'selection', 'records', 'reviewChecklist', 'boundary', 'collectionId', 'contentDigest'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/evidence-collection/v1' },
      schemaVersion: { const: '1.0.0' },
      asOf: { type: 'string', format: 'date-time' },
      selection: {
        type: 'object',
        required: ['count', 'limit', 'companyCount', 'jurisdictionCount', 'changeIds'],
        properties: {
          count: { type: 'integer', minimum: 1, maximum: 12 },
          limit: { const: 12 },
          companyCount: { type: 'integer', minimum: 1 },
          jurisdictionCount: { type: 'integer', minimum: 1 },
          changeIds: { type: 'array', minItems: 1, maxItems: 12, uniqueItems: true, items: { type: 'string', format: 'uuid' } },
        },
        additionalProperties: false,
      },
      records: { type: 'array', minItems: 1, maxItems: 12, items: { type: 'object' } },
      reviewChecklist: { type: 'array', minItems: 1, items: { type: 'string' } },
      boundary: { type: 'string' },
      collectionId: { type: 'string', pattern: '^pwc_[a-f0-9]{16}$' },
      contentDigest: { type: 'string', pattern: '^[a-f0-9]{64}$' },
    },
    additionalProperties: false,
  },
  'evidence-handoff': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/evidence-handoff/v1',
    title: 'PolicyWatcher vendor-neutral evidence review handoff',
    type: 'object',
    required: ['schema', 'schemaVersion', 'asOf', 'handoffType', 'collection', 'workItems', 'receivingSystemInstructions', 'boundary', 'handoffId', 'contentDigest'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/evidence-handoff/v1' },
      schemaVersion: { const: '1.0.0' },
      asOf: { type: 'string', format: 'date-time' },
      handoffType: { const: 'vendor-neutral-human-review' },
      collection: {
        type: 'object',
        required: ['id', 'contentDigest', 'selectedRecords'],
        properties: {
          id: { type: 'string', pattern: '^pwc_[a-f0-9]{16}$' },
          contentDigest: { type: 'string', pattern: '^[a-f0-9]{64}$' },
          selectedRecords: { type: 'integer', minimum: 1, maximum: 12 },
        },
        additionalProperties: false,
      },
      workItems: {
        type: 'array',
        minItems: 1,
        maxItems: 12,
        items: {
          type: 'object',
          required: ['id', 'sequence', 'type', 'state', 'title', 'summary', 'context', 'attentionSignal', 'acceptanceCriteria', 'evidence', 'boundaries'],
          properties: {
            id: { type: 'string', pattern: '^pwi_[a-f0-9]{16}$' },
            sequence: { type: 'integer', minimum: 1, maximum: 12 },
            type: { const: 'evidence-review' },
            state: { const: 'ready-for-human-triage' },
            title: { type: 'string' },
            summary: { type: 'string' },
            context: { type: 'object' },
            attentionSignal: { type: 'object' },
            acceptanceCriteria: { type: 'array', minItems: 1, items: { type: 'string' } },
            evidence: { type: 'object' },
            boundaries: { type: 'array', minItems: 1, items: { type: 'string' } },
          },
          additionalProperties: false,
        },
      },
      receivingSystemInstructions: { type: 'array', minItems: 1, items: { type: 'string' } },
      boundary: { type: 'string' },
      handoffId: { type: 'string', pattern: '^pwh_[a-f0-9]{16}$' },
      contentDigest: { type: 'string', pattern: '^[a-f0-9]{64}$' },
    },
    additionalProperties: false,
  },
  'change-event-feed': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/change-event-feed/v1',
    title: 'PolicyWatcher public change event polling feed',
    type: 'object',
    required: ['schema', 'schemaVersion', 'mode', 'locale', 'count', 'limit', 'hasMore', 'initialWindowTruncated', 'nextCursor', 'events', 'boundary'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/change-event-feed/v1' },
      schemaVersion: { const: '1.0.0' },
      mode: { const: 'forward-polling' },
      locale: { enum: ['en', 'it'] },
      count: { type: 'integer', minimum: 0, maximum: 100 },
      limit: { type: 'integer', minimum: 1, maximum: 100 },
      hasMore: { type: 'boolean' },
      initialWindowTruncated: { type: 'boolean' },
      nextCursor: { type: ['string', 'null'] },
      events: {
        type: 'array',
        maxItems: 100,
        items: {
          type: 'object',
          required: ['eventId', 'eventType', 'schemaVersion', 'occurredAt', 'subject', 'screening', 'links'],
          properties: {
            eventId: { type: 'string', pattern: '^pwe_[a-f0-9]{20}$' },
            eventType: { const: 'policy.change.published' },
            schemaVersion: { const: '1.0.0' },
            occurredAt: { type: 'string', format: 'date-time' },
            subject: { type: 'object' },
            screening: { type: 'object' },
            links: { type: 'object' },
          },
          additionalProperties: false,
        },
      },
      boundary: { type: 'string' },
    },
    additionalProperties: false,
  },
  'webhook-verification-kit': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/webhook-verification-kit/v1',
    title: 'PolicyWatcher webhook verification readiness kit',
    type: 'object',
    required: [
      'schema',
      'kitVersion',
      'status',
      'deliveryAvailable',
      'algorithm',
      'signatureVersion',
      'signedPayloadFormat',
      'headers',
      'candidateTimestampToleranceSeconds',
      'testVector',
      'testVectorInstructions',
      'receiverRequirements',
      'examples',
      'boundary',
    ],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/webhook-verification-kit/v1' },
      kitVersion: { const: '1.0.0' },
      status: { const: 'readiness-contract' },
      deliveryAvailable: { const: false },
      algorithm: { const: 'HMAC-SHA256' },
      signatureVersion: { const: 'v1' },
      signedPayloadFormat: { const: '{unix_timestamp}.{raw_request_body}' },
      headers: {
        type: 'object',
        required: ['eventId', 'timestamp', 'signature'],
        properties: {
          eventId: { const: 'PolicyWatcher-Event-Id' },
          timestamp: { const: 'PolicyWatcher-Timestamp' },
          signature: { const: 'PolicyWatcher-Signature' },
        },
        additionalProperties: false,
      },
      candidateTimestampToleranceSeconds: { type: 'integer', minimum: 1, maximum: 3600 },
      testVector: {
        type: 'object',
        required: [
          'id',
          'verificationMode',
          'secretClassification',
          'secret',
          'timestamp',
          'freshnessReferenceSeconds',
          'eventId',
          'payload',
          'signedPayload',
          'signatureHeader',
        ],
        properties: {
          id: { type: 'string' },
          verificationMode: { const: 'signature-compatibility-only' },
          secretClassification: { const: 'public-test-only' },
          secret: { type: 'string', minLength: 1 },
          timestamp: { type: 'integer', minimum: 1 },
          freshnessReferenceSeconds: { type: 'integer', minimum: 1 },
          eventId: { type: 'string', pattern: '^pwe_[a-f0-9]{20}$' },
          payload: { type: 'string', minLength: 2 },
          signedPayload: { type: 'string', minLength: 4 },
          signatureHeader: { type: 'string', pattern: '^v1=[a-f0-9]{64}$' },
        },
        additionalProperties: false,
      },
      testVectorInstructions: {
        type: 'array',
        minItems: 3,
        items: { type: 'string', minLength: 1 },
      },
      receiverRequirements: {
        type: 'array',
        minItems: 1,
        items: { type: 'string' },
      },
      examples: {
        type: 'object',
        required: ['node', 'python'],
        properties: {
          node: { type: 'string' },
          python: { type: 'string' },
        },
        additionalProperties: false,
      },
      boundary: { type: 'string' },
    },
    additionalProperties: false,
  },
} as const;
