const localized = {
  type: 'object',
  required: ['en', 'it'],
  properties: { en: { type: 'string' }, it: { type: 'string' } },
  additionalProperties: false,
} as const;

export const pressKitSchemas = {
  'press-kit': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit/v1',
    title: 'PolicyWatcher Press Kit payload',
    type: 'object',
    required: ['schema', 'schemaVersion', 'generatedAt', 'canonicalUrl', 'product', 'facts', 'claims', 'assets', 'packages', 'releases', 'boundaries'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/press-kit/v1' },
      schemaVersion: { type: 'string' },
      generatedAt: { type: 'string', format: 'date' },
      canonicalUrl: { type: 'string', format: 'uri' },
      product: { type: 'object' }, facts: { type: 'array' }, claims: { type: 'array' }, assets: { type: 'array' }, packages: { type: 'array' }, releases: { type: 'array' }, boundaries: { type: 'array', items: { type: 'string' } },
    },
  },
  'press-kit-asset-manifest': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-asset-manifest/v1',
    title: 'PolicyWatcher Press Kit asset manifest',
    type: 'object',
    required: ['schemaVersion', 'generatedAt', 'release', 'contentCredentials', 'assets'],
    properties: { schemaVersion: { type: 'string' }, generatedAt: { type: 'string', format: 'date' }, release: { type: 'string' }, contentCredentials: { const: 'not-attached' }, assets: { type: 'array', items: { type: 'object', required: ['filename', 'mediaType', 'bytes', 'sha256'], properties: { filename: { type: 'string' }, mediaType: { type: 'string' }, bytes: { type: 'integer', minimum: 0 }, sha256: { type: 'string', pattern: '^[a-f0-9]{64}$' }, creditLine: { type: 'string' }, rightsUrl: { type: 'string' } } } } },
  },
  'press-kit-package-manifest': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-package-manifest/v1',
    title: 'PolicyWatcher Press Kit package manifest',
    type: 'object',
    required: ['schemaVersion', 'generatedAt', 'release', 'packages'],
    properties: { schemaVersion: { type: 'string' }, generatedAt: { type: 'string', format: 'date' }, release: { type: 'string' }, packages: { type: 'array', items: { type: 'object', required: ['locale', 'filename', 'bytes', 'sha256'], properties: { locale: { enum: ['en', 'it'] }, filename: { type: 'string' }, bytes: { type: 'integer' }, sha256: { type: 'string', pattern: '^[a-f0-9]{64}$' } } } } },
  },
  'press-kit-media-metadata': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-media-metadata/v1',
    title: 'PolicyWatcher Press Kit media metadata',
    type: 'object',
    required: ['schemaVersion', 'standard', 'contentCredentials', 'assets'],
    properties: { schemaVersion: { type: 'string' }, standard: { const: 'IPTC Photo Metadata 2025.1' }, contentCredentials: { const: 'not-attached' }, vectorMasterAvailable: { type: 'boolean' }, assets: { type: 'object', additionalProperties: { type: 'object', properties: { title: localized, description: localized, alt: localized, usage: localized } } } },
  },
  'press-kit-data-snapshot': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-kit-data-snapshot/v1',
    title: 'PolicyWatcher configured-scope data snapshot',
    type: 'object',
    required: ['snapshotId', 'asOf', 'generatedAt', 'facts', 'boundary'],
    properties: { snapshotId: { type: 'string' }, asOf: { type: 'string', format: 'date' }, generatedAt: { type: 'string', format: 'date' }, facts: { type: 'array', items: { type: 'object', required: ['id', 'value', 'unit', 'scope'], properties: { id: { type: 'string' }, value: { type: 'string' }, unit: { type: 'string' }, scope: { type: 'string' } } } }, boundary: { type: 'string' } },
  },
  'editorial-story-pack': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/editorial-story-pack/v1',
    title: 'PolicyWatcher Editorial Story Pack manifest',
    type: 'object',
    required: ['schema', 'schemaVersion', 'storySlug', 'storyVersion', 'generatedAt', 'asOf', 'locale', 'canonicalUrl', 'claimIds', 'sourceHrefs', 'files', 'boundary'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/editorial-story-pack/v1' },
      schemaVersion: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+$' },
      storySlug: { type: 'string' },
      storyVersion: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+$' },
      generatedAt: { type: 'string', format: 'date' },
      asOf: { type: 'string', format: 'date' },
      locale: { enum: ['en', 'it'] },
      canonicalUrl: { type: 'string', format: 'uri' },
      claimIds: { type: 'array', items: { type: 'string' }, uniqueItems: true },
      sourceHrefs: { type: 'array', items: { type: 'string' }, uniqueItems: true },
      files: { type: 'array', items: { type: 'string' }, uniqueItems: true },
      boundary: { type: 'string' },
    },
    additionalProperties: false,
  },
  'press-coverage': {
    $schema: 'https://json-schema.org/draft/2020-12/schema',
    $id: 'https://policywatcher.online/schemas/press-coverage/v1',
    title: 'PolicyWatcher public press coverage registry',
    type: 'object',
    required: ['schema', 'schemaVersion', 'asOf', 'canonicalUrl', 'boundary', 'summary', 'records'],
    properties: {
      schema: { const: 'https://policywatcher.online/schemas/press-coverage/v1' },
      schemaVersion: { type: 'string', pattern: '^\\d+\\.\\d+\\.\\d+$' },
      asOf: { type: 'string', format: 'date' },
      canonicalUrl: { type: 'string', format: 'uri' },
      boundary: { type: 'string' },
      summary: {
        type: 'object',
        required: ['total', 'sourceLinked', 'editorial', 'professionalPosts', 'byLanguage'],
        properties: {
          total: { type: 'integer', minimum: 0 },
          sourceLinked: { type: 'integer', minimum: 0 },
          editorial: { type: 'integer', minimum: 0 },
          professionalPosts: { type: 'integer', minimum: 0 },
          byLanguage: { type: 'object', required: ['en', 'it'], properties: { en: { type: 'integer', minimum: 0 }, it: { type: 'integer', minimum: 0 } }, additionalProperties: false },
        },
        additionalProperties: false,
      },
      records: {
        type: 'array',
        items: {
          type: 'object',
          required: ['id', 'sourceName', 'platform', 'kind', 'language', 'publishedDate', 'datePrecision', 'recordedAt', 'reviewedAt', 'title', 'titleStatus', 'summary', 'sourceUrl', 'relationship', 'recordStatus', 'dateLabel', 'citation'],
          properties: {
            id: { type: 'string' }, sourceName: { type: 'string' }, platform: { type: 'string' },
            kind: { enum: ['editorial-article', 'newsletter-article', 'professional-post'] },
            language: { enum: ['en', 'it'] }, publishedDate: { type: 'string', pattern: '^\\d{4}-\\d{2}$' },
            datePrecision: { const: 'month' }, recordedAt: { type: 'string', format: 'date' }, reviewedAt: { type: 'string', format: 'date' },
            title: { type: 'string' }, titleStatus: { enum: ['publisher-supplied', 'registry-description'] }, summary: { type: 'string' },
            sourceUrl: { type: 'string', format: 'uri' }, relationship: { enum: ['external editorial reference', 'external professional reference'] },
            recordStatus: { const: 'source-linked' }, dateLabel: { type: 'string' }, citation: { type: 'string' },
          },
        },
      },
    },
    additionalProperties: false,
  },
} as const;
