export type PublicSectionGroup =
  | 'core'
  | 'evidence'
  | 'assurance'
  | 'community'
  | 'governance'
  | 'boundary';

export interface PublicSectionNode {
  id: string;
  label: string;
  href: string;
  group: PublicSectionGroup;
  summary: string;
  role: string;
  status: 'live' | 'dynamic' | 'reference' | 'protected';
  icon: string;
  x: number;
  y: number;
}

export interface PublicSectionEdge {
  from: string;
  to: string;
  label: string;
  strength: 'primary' | 'secondary';
}

export const publicSectionGroups: Record<PublicSectionGroup, { label: string; description: string; color: string }> = {
  core: {
    label: 'Core routes',
    description: 'Entry points and public inspection surfaces.',
    color: '#146c6a',
  },
  evidence: {
    label: 'Evidence views',
    description: 'Source-gated views built from publicEvidence records.',
    color: '#3f55a6',
  },
  assurance: {
    label: 'Quality assurance',
    description: 'Quality gates, security signals and operational evidence.',
    color: '#b45309',
  },
  community: {
    label: 'Public information',
    description: 'Roadmap, press references and public product information.',
    color: '#7c3aed',
  },
  governance: {
    label: 'Policies and methodology',
    description: 'Use boundaries, evidence methodology and privacy policy.',
    color: '#0f766e',
  },
  boundary: {
    label: 'Protected operations',
    description: 'Protected operational capabilities, shown for context only.',
    color: '#475569',
  },
};

export const publicSectionNodes: PublicSectionNode[] = [
  {
    id: 'associations',
    label: 'Consumer associations',
    href: '/en/associations',
    group: 'core',
    summary: 'Global civic-review workspace with a source-backed consumer-organization directory, territorial context and public-gated policy evidence.',
    role: 'The directory lists national, regional and global advocates, verification sources, published changes and review-ready evidence. Suggestions are available without an account.',
    status: 'dynamic',
    icon: 'user',
    x: 41,
    y: 35,
  },
  {
    id: 'knowledge',
    label: 'Public Knowledge Base',
    href: '/knowledge',
    group: 'evidence',
    summary: 'Server-rendered index of companies, policies, verified baselines and published changes that pass the public-evidence gate.',
    role: 'Provides textual, citable and crawler-accessible entry into public PolicyWatcher records.',
    status: 'dynamic',
    icon: 'book',
    x: 42,
    y: 65,
  },
  {
    id: 'dashboard',
    label: 'Evidence Console',
    href: '/',
    group: 'core',
    summary: 'Main public dashboard with configurable density, current actions, filters, QA state and monitored companies.',
    role: 'The dashboard configures interface density and displays current public evidence under the existing publication gates.',
    status: 'dynamic',
    icon: 'layout',
    x: 48,
    y: 50,
  },
  {
    id: 'showcase',
    label: 'Product overview',
    href: '/showcase',
    group: 'core',
    summary: 'Product overview, workflows, admin capabilities and dataset-quality controls.',
    role: 'Lists implemented platform areas, workflows and data-quality controls.',
    status: 'live',
    icon: 'sparkles',
    x: 28,
    y: 22,
  },
  {
    id: 'timeline',
    label: 'Timeline',
    href: '/timeline',
    group: 'evidence',
    summary: 'Chronological views of evidence-gated policy changes and sanitized source-continuity transitions.',
    role: 'Separates provider policy changes from retrieval and publication-state changes.',
    status: 'dynamic',
    icon: 'clock',
    x: 22,
    y: 55,
  },
  {
    id: 'what-changed',
    label: 'Notice verification',
    href: '/what-changed',
    group: 'core',
    summary: 'Turns a policy-update notification into verified public evidence or a tracked human-review request.',
    role: 'Accepts terms or privacy notices for public-evidence verification.',
    status: 'dynamic',
    icon: 'file-search',
    x: 34,
    y: 42,
  },
  {
    id: 'observatory',
    label: 'Observatory',
    href: '/observatory',
    group: 'evidence',
    summary: 'Curated public source registry for AI governance, privacy enforcement, standards and events.',
    role: 'Lists authoritative sources used for public policy signals.',
    status: 'reference',
    icon: 'book',
    x: 58,
    y: 34,
  },
  {
    id: 'developers',
    label: 'Developer APIs and tools',
    href: '/developers',
    group: 'core',
    summary: 'Read-only public integration directory for evidence metadata, agent briefs, forward-polling continuity and the curated Observatory registry.',
    role: 'The directory documents system and enterprise-agent access, publication rules, rate limits and source-review boundaries.',
    status: 'reference',
    icon: 'code',
    x: 67,
    y: 40,
  },
  {
    id: 'integrations',
    label: 'Integrations',
    href: '/integrations',
    group: 'core',
    summary: 'Readiness map for public APIs, Enterprise API v2, Azure, Power Platform, Microsoft 365, Google Cloud, AWS and Office source packages.',
    role: 'Documents supported machine surfaces, evidence boundaries and tenant requirements.',
    status: 'reference',
    icon: 'code',
    x: 60,
    y: 48,
  },
  {
    id: 'leaderboard',
    label: 'Policy Signals Board',
    href: '/leaderboard',
    group: 'evidence',
    summary: 'Evidence-only ranking of source coverage, retrieval traceability and public movement.',
    role: 'The board compares evidence readiness. It does not assess legal compliance.',
    status: 'dynamic',
    icon: 'bar-chart',
    x: 31,
    y: 78,
  },
  {
    id: 'trust',
    label: 'Trust & Quality',
    href: '/trust',
    group: 'assurance',
    summary: 'CI, CodeQL, OpenSSF, HTTP header checks, renderer evidence and Dataset QA framing.',
    role: 'Lists operational quality signals and Dataset QA controls.',
    status: 'reference',
    icon: 'shield',
    x: 69,
    y: 76,
  },
  {
    id: 'methodology',
    label: 'Evidence methodology',
    href: '/methodology/confidence',
    group: 'governance',
    summary: 'Bilingual explanation of provenance, scraper cascade, AI limits and known boundaries.',
    role: 'Documents provenance, AI limits and publication boundaries.',
    status: 'reference',
    icon: 'book',
    x: 76,
    y: 55,
  },
  {
    id: 'roadmap',
    label: 'Product roadmap',
    href: '/roadmap',
    group: 'community',
    summary: 'Delivered releases, planned features, API work and community-priority signals.',
    role: 'Lists planned work and accepts roadmap priority submissions.',
    status: 'live',
    icon: 'route',
    x: 73,
    y: 25,
  },
  {
    id: 'press',
    label: 'Coverage registry',
    href: '/press',
    group: 'community',
    summary: 'Public references, professional-community mentions and media coverage.',
    role: 'The registry links public discussion records and states that mentions are not endorsements.',
    status: 'live',
    icon: 'newspaper',
    x: 53,
    y: 13,
  },
  {
    id: 'press-kit',
    label: 'Press Kit',
    href: '/press-kit',
    group: 'community',
    summary: 'Bilingual press page with product facts, supporting links, limitations, owned assets and citation guidance.',
    role: 'Provides product statements, press materials and links to external coverage records.',
    status: 'reference',
    icon: 'file-text',
    x: 54,
    y: 25,
  },
  {
    id: 'pulse',
    label: 'PolicyWatcher Pulse',
    href: '/pulse',
    group: 'community',
    summary: 'Human-approved story leads with versioned packs, source links, evidence visuals and explicit reuse boundaries.',
    role: 'Each editorial lead keeps its claims, supporting evidence and limitations together.',
    status: 'reference',
    icon: 'newspaper',
    x: 44,
    y: 27,
  },
  {
    id: 'about',
    label: 'About the Project',
    href: '/about',
    group: 'community',
    summary: 'Project authorship, public contact routes, open-source links and maintenance information.',
    role: 'Lists project maintainers, contact routes and repository links.',
    status: 'reference',
    icon: 'user',
    x: 39,
    y: 13,
  },
  {
    id: 'security',
    label: 'Security Policy',
    href: '/security',
    group: 'governance',
    summary: 'Responsible disclosure channel and in-scope security reporting boundaries.',
    role: 'Provides the responsible-disclosure process and reporting scope.',
    status: 'reference',
    icon: 'lock',
    x: 88,
    y: 38,
  },
  {
    id: 'privacy',
    label: 'Privacy Policy',
    href: '/privacy',
    group: 'governance',
    summary: 'Privacy notice and user-data boundaries.',
    role: 'States site privacy terms and user-data boundaries.',
    status: 'reference',
    icon: 'file-text',
    x: 86,
    y: 70,
  },
  {
    id: 'infographics',
    label: 'Infographics',
    href: '/infographics',
    group: 'community',
    summary: 'Editorial and interactive diagrams for the generated ER sitemap, dashboard settings, Site Atlas and filter invariants.',
    role: 'Provides the domain map and generated Mermaid and JSON route records.',
    status: 'live',
    icon: 'sparkles',
    x: 64,
    y: 19,
  },
  {
    id: 'feature-atlas',
    label: 'Feature atlas',
    href: '/feature-atlas',
    group: 'core',
    summary: 'Capability catalog linking outcomes, dependencies, implementation evidence and residual limits.',
    role: 'Lists release-linked capabilities and qualitative KPI/KRI impact; the Site Atlas provides the page map.',
    status: 'reference',
    icon: 'sparkles',
    x: 65,
    y: 45,
  },
  {
    id: 'terms',
    label: 'Terms of Use',
    href: '/terms',
    group: 'governance',
    summary: 'Bilingual public statement of the platform use boundaries and local acknowledgement behavior.',
    role: 'States the limits governing dashboard use and interpretation.',
    status: 'reference',
    icon: 'file-text',
    x: 89,
    y: 59,
  },
  {
    id: 'admin',
    label: 'Admin Operations',
    href: '/admin',
    group: 'boundary',
    summary: 'Protected console for Dataset QA, source scans, configured webhook delivery, VPS services, database inspection and review logs.',
    role: 'Shown as an architecture boundary; access remains protected.',
    status: 'protected',
    icon: 'server',
    x: 50,
    y: 93,
  },
];

export const publicSectionEdges: PublicSectionEdge[] = [
  { from: 'associations', to: 'knowledge', label: 'contains published records from', strength: 'primary' },
  { from: 'associations', to: 'what-changed', label: 'submits source signals to', strength: 'primary' },
  { from: 'associations', to: 'methodology', label: 'uses evidence boundaries from', strength: 'primary' },
  { from: 'dashboard', to: 'knowledge', label: 'links to public records in', strength: 'primary' },
  { from: 'knowledge', to: 'methodology', label: 'uses publication rules from', strength: 'primary' },
  { from: 'knowledge', to: 'developers', label: 'publishes machine records through', strength: 'secondary' },
  { from: 'what-changed', to: 'timeline', label: 'checks notices against', strength: 'primary' },
  { from: 'what-changed', to: 'methodology', label: 'uses evidence boundaries from', strength: 'primary' },
  { from: 'admin', to: 'what-changed', label: 'reviews unresolved inquiries from', strength: 'primary' },
  { from: 'dashboard', to: 'timeline', label: 'links to published changes in', strength: 'primary' },
  { from: 'dashboard', to: 'observatory', label: 'uses source references from', strength: 'secondary' },
  { from: 'dashboard', to: 'leaderboard', label: 'supplies evidence signals to', strength: 'primary' },
  { from: 'dashboard', to: 'methodology', label: 'uses evidence rules from', strength: 'primary' },
  { from: 'dashboard', to: 'trust', label: 'displays QA state from', strength: 'primary' },
  { from: 'observatory', to: 'methodology', label: 'documents source limits in', strength: 'primary' },
  { from: 'observatory', to: 'trust', label: 'uses QA rules from', strength: 'secondary' },
  { from: 'developers', to: 'observatory', label: 'publishes source metadata from', strength: 'primary' },
  { from: 'developers', to: 'methodology', label: 'uses data limits from', strength: 'secondary' },
  { from: 'integrations', to: 'developers', label: 'links API implementers to', strength: 'primary' },
  { from: 'integrations', to: 'methodology', label: 'uses evidence boundaries from', strength: 'primary' },
  { from: 'roadmap', to: 'integrations', label: 'lists planned channels in', strength: 'secondary' },
  { from: 'showcase', to: 'dashboard', label: 'documents features in', strength: 'primary' },
  { from: 'showcase', to: 'roadmap', label: 'lists planned work in', strength: 'secondary' },
  { from: 'showcase', to: 'trust', label: 'summarizes controls from', strength: 'secondary' },
  { from: 'roadmap', to: 'dashboard', label: 'lists dashboard changes for', strength: 'primary' },
  { from: 'roadmap', to: 'infographics', label: 'links release diagrams in', strength: 'secondary' },
  { from: 'infographics', to: 'dashboard', label: 'documents dashboard views in', strength: 'primary' },
  { from: 'feature-atlas', to: 'dashboard', label: 'lists dashboard capabilities in', strength: 'primary' },
  { from: 'feature-atlas', to: 'roadmap', label: 'links delivery stages to', strength: 'primary' },
  { from: 'feature-atlas', to: 'methodology', label: 'uses claim rules from', strength: 'secondary' },
  { from: 'terms', to: 'methodology', label: 'links use boundaries to', strength: 'primary' },
  { from: 'press', to: 'showcase', label: 'links coverage records to', strength: 'secondary' },
  { from: 'press-kit', to: 'press', label: 'labels owned materials and coverage in', strength: 'primary' },
  { from: 'press-kit', to: 'trust', label: 'links claims to controls in', strength: 'primary' },
  { from: 'press-kit', to: 'methodology', label: 'uses evidence boundaries from', strength: 'secondary' },
  { from: 'pulse', to: 'press-kit', label: 'links editorial leads to', strength: 'primary' },
  { from: 'pulse', to: 'methodology', label: 'uses interpretation boundaries from', strength: 'primary' },
  { from: 'about', to: 'showcase', label: 'links project details to', strength: 'primary' },
  { from: 'about', to: 'roadmap', label: 'links project work to', strength: 'secondary' },
  { from: 'trust', to: 'methodology', label: 'documents evidence boundaries in', strength: 'primary' },
  { from: 'security', to: 'trust', label: 'links security controls to', strength: 'secondary' },
  { from: 'privacy', to: 'methodology', label: 'links data boundaries to', strength: 'secondary' },
  { from: 'admin', to: 'dashboard', label: 'controls published data in', strength: 'primary' },
  { from: 'admin', to: 'trust', label: 'supplies operational evidence to', strength: 'secondary' },
];
