import { POLICYWATCHER_VERSION_DISPLAY } from './release';

export type ReleaseImpactKind = 'business' | 'technical';
export type ReleaseImpactStatus = 'delivered' | 'current' | 'planned';
export type ReleaseImpactHorizon = 'delivered' | 'next' | 'later';

export interface ReleaseColumn {
  id: string;
  shortLabel: string;
  label: string;
  state: ReleaseImpactStatus;
}

export interface ReleaseImpactDomain {
  id: string;
  label: string;
  kind: ReleaseImpactKind;
}

export interface ReleaseImpactItem {
  id: string;
  title: string;
  summary: string;
  domainId: string;
  status: ReleaseImpactStatus;
  horizon: ReleaseImpactHorizon;
  startRelease: string;
  endRelease: string;
  benefit: string;
  kpi: string;
  kri: string;
  evidence: string;
  limitation: string;
  externalDependency?: string;
}

export const RELEASE_IMPACT_UPDATED_AT = '29 July 2026' as const;

export const RELEASE_COLUMNS: ReleaseColumn[] = [
  { id: '3.7.0', shortLabel: '3.7.0', label: '3.7.0', state: 'delivered' },
  { id: '3.7.1', shortLabel: '3.7.1', label: '3.7.1', state: 'delivered' },
  { id: '3.7.2', shortLabel: '3.7.2', label: '3.7.2', state: 'delivered' },
  { id: '3.8.0', shortLabel: '3.8.0', label: '3.8.0', state: 'delivered' },
  { id: '3.8.1', shortLabel: '3.8.1', label: '3.8.1', state: 'delivered' },
  { id: '3.8.2', shortLabel: '3.8.2', label: '3.8.2', state: 'delivered' },
  { id: 'beta.2', shortLabel: 'B2', label: '3.8.3 Beta 2', state: 'delivered' },
  { id: 'beta.3', shortLabel: 'B3', label: '3.8.3 Beta 3', state: 'delivered' },
  { id: 'beta.4', shortLabel: 'B4', label: '3.8.3 Beta 4', state: 'delivered' },
  { id: 'beta.5', shortLabel: 'B5', label: '3.8.3 Beta 5', state: 'delivered' },
  { id: 'beta.6', shortLabel: 'B6', label: '3.8.3 Beta 6', state: 'delivered' },
  { id: 'beta.7', shortLabel: 'B7', label: '3.8.3 Beta 7', state: 'delivered' },
  { id: 'beta.8', shortLabel: 'B8', label: '3.8.3 Beta 8', state: 'delivered' },
  { id: 'beta.9', shortLabel: 'B9', label: '3.8.3 Beta 9', state: 'delivered' },
  { id: 'beta.10', shortLabel: 'B10', label: '3.8.3 Beta 10', state: 'delivered' },
  { id: 'beta.11', shortLabel: 'B11', label: '3.8.3 Beta 11', state: 'delivered' },
  { id: '3.9.0-beta.1', shortLabel: '3.9 B1', label: '3.9.0 Beta 1', state: 'delivered' },
  { id: '3.9.0-beta.2', shortLabel: '3.9 B2', label: '3.9.0 Beta 2', state: 'delivered' },
  { id: '3.9.0-beta.3', shortLabel: '3.9 B3', label: '3.9.0 Beta 3', state: 'delivered' },
  { id: '3.9.0-beta.4', shortLabel: '3.9 B4', label: '3.9.0 Beta 4', state: 'delivered' },
  { id: '3.9.0-beta.5', shortLabel: '3.9 B5', label: '3.9.0 Beta 5', state: 'delivered' },
  { id: '3.9.0-beta.6', shortLabel: '3.9 B6', label: '3.9.0 Beta 6', state: 'delivered' },
  { id: '3.9.0-beta.7', shortLabel: '3.9 B7', label: '3.9.0 Beta 7', state: 'delivered' },
  { id: '3.9.0-beta.8', shortLabel: '3.9 B8', label: '3.9.0 Beta 8', state: 'delivered' },
  { id: '3.9.0-beta.9', shortLabel: '3.9 B9', label: '3.9.0 Beta 9', state: 'delivered' },
  { id: '3.9.0-beta.10', shortLabel: '3.9 B10', label: '3.9.0 Beta 10', state: 'delivered' },
  { id: '3.9.0-beta.11', shortLabel: '3.9 B11', label: '3.9.0 Beta 11', state: 'delivered' },
  { id: '3.9.0-beta.12', shortLabel: '3.9 B12', label: '3.9.0 Beta 12', state: 'delivered' },
  { id: '3.9.0-beta.13', shortLabel: '3.9 B13', label: POLICYWATCHER_VERSION_DISPLAY, state: 'current' },
  { id: 'next', shortLabel: 'Next', label: 'Next beta horizon', state: 'planned' },
  { id: 'later', shortLabel: 'Later', label: 'Later horizon', state: 'planned' },
];

export const RELEASE_IMPACT_DOMAINS: ReleaseImpactDomain[] = [
  { id: 'experience', label: 'User experience', kind: 'business' },
  { id: 'corrections', label: 'Correction operations', kind: 'business' },
  { id: 'distribution', label: 'Channel distribution', kind: 'business' },
  { id: 'legal', label: 'Legal resilience', kind: 'business' },
  { id: 'intake', label: 'Evidence intake', kind: 'technical' },
  { id: 'retrieval', label: 'Retrieval', kind: 'technical' },
  { id: 'assurance', label: 'Data assurance', kind: 'technical' },
  { id: 'security', label: 'Security', kind: 'technical' },
  { id: 'operations', label: 'Production operations', kind: 'technical' },
];

export const RELEASE_IMPACT_ITEMS: ReleaseImpactItem[] = [
  {
    id: 'verified-browser-store-distribution',
    title: 'Verified browser-store distribution',
    summary: 'Publishes a direct Chrome Web Store action and reports Chrome, Edge and Safari availability as independent verified states.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.9',
    endRelease: '3.9.0-beta.9',
    benefit: 'Users can reach the published Chrome listing directly and are not shown a shared pending status for unrelated browser stores.',
    kpi: 'Verified browser-store destinations: One public Chrome listing',
    kri: 'Edge and Safari distribution: No verified public listing',
    evidence: 'Public Chrome Web Store listing, official-host URL validation, store-specific availability copy and regression coverage.',
    limitation: 'The verified state records public distribution only; it does not change extension behavior, review other browser stores or establish user adoption.',
    externalDependency: 'Microsoft Edge Add-ons and Apple App Store publication',
  },
  {
    id: 'assistant-entry-point-consolidation',
    title: 'Assistant entry-point consolidation',
    summary: 'Removes the legacy floating chat trigger while retaining assistant access in unified navigation, Workspace Controls and command search.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.8',
    endRelease: '3.9.0-beta.8',
    benefit: 'The dashboard presents one persistent assistant control instead of two competing fixed actions.',
    kpi: 'Persistent assistant triggers on the dashboard: One unified navigation control',
    kri: 'Discoverability dependency: Users must recognize the labelled navigation or Workspace Controls action',
    evidence: 'Unified Navigation assistant command, labelled Workspace Controls action, Command Palette action and duplicate-trigger regression coverage.',
    limitation: 'This release changes assistant discovery only; it does not change generated answers, model behavior or the chat API.',
  },
  {
    id: 'newsroom-measurement-and-release-assurance',
    title: 'Newsroom measurement and release assurance',
    summary: 'Improves mobile Press Kit access, adds privacy-minimized aggregate newsroom event counts and closes scoped release-security findings.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.7',
    endRelease: '3.9.0-beta.7',
    benefit: 'Editors reach core facts and actions sooner on mobile while authorized operators can inspect bounded distribution signals.',
    kpi: 'Measured newsroom signals: Package-download intentions, Data Room views and press-contact intentions',
    kri: 'Interpretation risk: Aggregate events can include automation and do not identify unique people or confirmed outcomes',
    evidence: 'Mobile Fast Facts, horizontal action rail with visible cue, readable Claim Registry metadata, compact utility footer, allowlisted first-party event endpoint, protected 30-day and all-time aggregates, migration and regression tests.',
    limitation: 'No target or conversion rate is stated before baseline data exists; telemetry writes are non-blocking and can be lost.',
  },
  {
    id: 'evidence-newsroom',
    title: 'Evidence Newsroom',
    summary: 'Extends the Press Kit with versioned packages, dated claim records, release feeds, reusable data and public reference registers.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.6',
    endRelease: '3.9.0-beta.6',
    benefit: 'Journalists and fact-checkers can download dated assets, inspect claim freshness and follow release records without reconstructing context.',
    kpi: 'Editorial distribution surfaces: Package, registry, feed and data room available',
    kri: 'Later reuse of snapshots: Live-source revalidation remains required',
    evidence: 'Localized press ZIPs, asset and package manifests, IPTC/XMP metadata, claim registry, release archive, RSS, JSON Feed, data snapshot and specialized mail routes.',
    limitation: 'The newsroom improves reuse and traceability; it does not establish media coverage, factual endorsement, legal compliance or Content Credentials.',
  },
  {
    id: 'press-kit-navigation-discovery',
    title: 'Press Kit navigation discovery',
    summary: 'Adds a direct Press Kit link to dashboard controls, the public header and command search.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.5',
    endRelease: '3.9.0-beta.5',
    benefit: 'Press information is reachable from the dashboard and shared public navigation.',
    kpi: 'Press Kit navigation entry points: Three',
    kri: 'Production visibility: Requires deployment of the matching web release',
    evidence: 'Workspace Controls item, shared public-header item, Command Palette action and navigation regression test.',
    limitation: 'Navigation availability remains dependent on the deployed web release.',
  },
  {
    id: 'public-claim-language-governance',
    title: 'Public claim language governance',
    summary: 'Uses scoped descriptions of implemented behavior, evidence boundaries, dates and known limitations across public and press-facing copy.',
    domainId: 'legal',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.4',
    endRelease: '3.9.0-beta.4',
    benefit: 'Readers receive concrete product statements with stated scope and limitations.',
    kpi: 'Selected public claim surfaces: Editorial rule enforced',
    kri: 'Underlying data and external status accuracy: Requires separate validation',
    evidence: 'Cross-site copy audit, revised press fact sheet and outreach guide, point-in-time security wording and an editorial regression test.',
    limitation: 'The editorial control detects listed wording patterns; it does not validate source data, deployed configuration or external services.',
  },
  {
    id: 'editorial-briefing-room',
    title: 'Editorial briefing room',
    summary: 'Publishes a bilingual, evidence-led press kit with a claim ledger, owned assets and stable machine-readable metadata.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.3',
    endRelease: '3.9.0-beta.3',
    benefit: 'Journalists and analysts can verify bounded product claims before reusing them.',
    kpi: 'Press evidence surface: Published',
    kri: 'Independent coverage and reader comprehension: Not assessed',
    evidence: 'Public press kit, six-entry claim ledger, checksummed asset manifest, JSON-LD and stable JSON endpoint.',
    limitation: 'The newsroom contains owned materials; it does not prove independent adoption, compliance or exhaustive coverage.',
  },
  {
    id: 'notification-evidence',
    title: 'Notification to evidence inquiry',
    summary: 'Turns user-confirmed clues from a policy notice into a source-gated portfolio inquiry.',
    domainId: 'intake',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.7.0',
    endRelease: '3.7.1',
    benefit: 'A direct path from a real notice to public evidence without treating the notice as proof.',
    kpi: 'Public evidence boundary: Guarded',
    kri: 'Unknown source quality: Human approval required',
    evidence: 'Local clue confirmation, publicEvidence filtering, inquiry queue and conflict handling.',
    limitation: 'Inquiry to discovery remains intentionally human-approved.',
  },
  {
    id: 'calm-workspace',
    title: 'Calm evidence workspace',
    summary: 'Adapts the first-use workspace to user objective and evidence depth.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.7.2',
    endRelease: '3.7.2',
    benefit: 'The initial workspace presents objective, evidence depth and Source QA in one flow.',
    kpi: 'Workspace orientation: Unlocked',
    kri: 'Real-user comprehension: Pending validation',
    evidence: 'Objective composer, progressive controls, local preferences and mobile navigation.',
    limitation: 'Observed user evidence is still needed before stable promotion.',
  },
  {
    id: 'browser-companion',
    title: 'Browser Evidence Companion',
    summary: 'Extracts minimal clues inside the active tab after an explicit user gesture.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.8.0',
    endRelease: 'beta.3',
    benefit: 'Chrome users can inspect a notice without persistent mailbox access.',
    kpi: 'Chrome notice path: Unlocked',
    kri: 'Edge and Safari distribution: External dependency',
    evidence: 'Browser extension 3.8.3 Beta 3 is publicly listed in the Chrome Web Store and retains local parsing with explicit confirmation.',
    limitation: 'No official Edge Add-ons listing is currently verified. Safari still needs signing, packaging and review.',
    externalDependency: 'Edge listing verification and Safari signing and review',
  },
  {
    id: 'regional-discovery',
    title: 'Regional policy discovery',
    summary: 'Retains locale-specific official policy variants through discovery and review.',
    domainId: 'retrieval',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.8.2',
    endRelease: 'beta.4',
    benefit: 'Regional variants survive discovery for human source review.',
    kpi: 'Regional candidate coverage: Unlocked',
    kri: 'SPA retrieval coverage: Production dependency',
    evidence: 'URL locale inference, hreflang extraction, locale probes and bounded candidate caps.',
    limitation: 'Some script-rendered sites still depend on the production renderer.',
  },
  {
    id: 'inquiry-publication-gate',
    title: 'Inquiry publication gate',
    summary: 'Keeps inquiry-derived sources private through baseline capture, QA and explicit publication.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.4',
    endRelease: 'beta.6',
    benefit: 'New sources cannot become public evidence from an inquiry alone.',
    kpi: 'Publication boundary: Guarded',
    kri: 'Operator review capacity: Residual dependency',
    evidence: 'Onboarding batch, private baseline, hash, QA review and explicit publish state.',
    limitation: 'Publication quality still depends on trained operator review.',
  },
  {
    id: 'qualified-language',
    title: 'Qualified public analysis language',
    summary: 'Frames automated output as textual attention signals with explicit evidence dates and limits.',
    domainId: 'legal',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.5',
    endRelease: 'beta.6',
    benefit: 'Readers can distinguish a text-derived indicator from a legal determination.',
    kpi: 'Method boundary visibility: Unlocked',
    kri: 'Professional legal review: External dependency',
    evidence: 'Updated public pages, share views, reports, PDF wording and methodology disclaimers.',
    limitation: 'Qualified language reduces ambiguity but does not remove legal risk.',
    externalDependency: 'Independent professional legal review',
  },
  {
    id: 'correction-channel',
    title: 'Human correction channel',
    summary: 'Provides a direct route to report an inaccuracy or request a rerun.',
    domainId: 'corrections',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.6',
    endRelease: 'beta.6',
    benefit: 'Affected organizations have a visible cooperative review route.',
    kpi: 'Correction channel coverage: Unlocked',
    kri: 'Case tracking and identity assurance: Pending',
    evidence: 'Review-request page and links on change, share and PDF surfaces.',
    limitation: 'The current channel does not persist cases or alter public indicators automatically.',
  },
  {
    id: 'request-hardening',
    title: 'Public request boundary hardening',
    summary: 'Bounds chat and speech requests, minimizes logs and narrows default context.',
    domainId: 'security',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.5',
    endRelease: 'beta.6',
    benefit: 'Predictable input and privacy boundaries for exposed services.',
    kpi: 'Request abuse controls: Guarded',
    kri: 'Dynamic production attack paths: Pending validation',
    evidence: 'Bounded JSON parsing, input caps, rate controls, masked logs and focused tests.',
    limitation: 'A production pentest is still required.',
  },
  {
    id: 'hostinger-recovery',
    title: 'Hostinger database recovery',
    summary: 'Separates session access from metrics and exposes protected read-only database readiness alongside deployment-time schema reconciliation.',
    domainId: 'operations',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.6',
    endRelease: 'beta.6',
    benefit: 'Operators can recover an outdated schema without replacing the database.',
    kpi: 'Operator recovery path and readiness inspection: Available',
    kri: 'Restore execution and post-deploy production result: Require operator validation',
    evidence: 'Database-independent admin session, non-blocking optional metrics, managed-install initializer, bounded schema diagnostics and protected readiness panel.',
    limitation: 'The readiness panel is read-only and does not migrate, reset, repair or restore production data.',
  },
  {
    id: 'impact-clarity',
    title: 'Release impact clarity',
    summary: 'Connects releases to affected domains, unlocked outcomes, evidence and residual risks.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.7',
    endRelease: 'beta.7',
    benefit: 'Business and technical stakeholders can inspect one release record.',
    kpi: 'Release impact traceability: Unlocked',
    kri: 'Stakeholder comprehension: Pending validation',
    evidence: 'Shared release-impact dataset, interactive matrix, KPI and KRI inspector.',
    limitation: 'The map reports release evidence, not measured adoption or business performance.',
  },
  {
    id: 'public-surface-consistency',
    title: 'Public evidence consistency',
    summary: 'Aligns explanatory, evidence ranking and correction routes around one public evidence language.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.8',
    endRelease: 'beta.8',
    benefit: 'Visitors can distinguish live database evidence, explanatory product guides and human review workflows within the public interface.',
    kpi: 'Public surface provenance: Unlocked',
    kri: 'Cross-route comprehension: Pending validation',
    evidence: 'Shared public chrome, recurring evidence-status rail, persisted snapshot timestamp, fail-closed empty state and bilingual correction workflow.',
    limitation: 'The release improves provenance visibility but does not turn the evidence index into a compliance assessment.',
  },
  {
    id: 'verified-corrections',
    title: 'Correction case management',
    summary: 'Adds identity and domain verification, anti-abuse controls, human triage and audited case states.',
    domainId: 'corrections',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.9',
    endRelease: 'beta.9',
    benefit: 'A recorded route from email and domain confirmation to scoped human review.',
    kpi: 'Correction case workflow: Unlocked',
    kri: 'Identity abuse and complaint flooding: Human gate retained',
    evidence: 'One-time email verification, keyed address hashing, registrable-domain checks, bounded intake, rate limits, deduplication and audited human transitions.',
    limitation: 'A complaint alone will not suspend an indicator or create a public badge.',
  },
  {
    id: 'public-review-state',
    title: 'Evidence-scoped public review state',
    summary: 'Shows review in progress and permits suspension only for accepted, evidence-scoped cases.',
    domainId: 'legal',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.9',
    endRelease: 'beta.9',
    benefit: 'Readers can see when specific evidence is under an accepted review case.',
    kpi: 'Public review state: Unlocked',
    kri: 'Platform-wide abuse: Scope isolated',
    evidence: 'Private submission state, admin acceptance, public evidence badge, record-scoped suspension and public resolution timeline.',
    limitation: 'No complaint-only automatic suspension. Effects remain limited to the contested evidence.',
  },
  {
    id: 'source-recovery-console',
    title: 'Source Recovery Console',
    summary: 'Separates suspension cause, recorded evidence, latest attempt and the next scoped operator action.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'Readers and operators can understand why public evidence is withheld without seeing internal errors.',
    kpi: 'Suspension cause clarity: Unlocked',
    kri: 'Source remediation outcome: Not guaranteed',
    evidence: 'Bilingual category mapping, evidence rail, bounded disclosure and direct methodology links.',
    limitation: 'The console explains recorded state and does not claim that a blocked source can always be recovered.',
  },
  {
    id: 'latest-check-clarity',
    title: 'Latest-check status presentation',
    summary: 'Normalizes mixed historical timestamp shapes before selecting the latest recorded check.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'Public suspension evidence reflects the most recent recorded attempt across legacy timestamp formats.',
    kpi: 'Mixed timestamp selection: Guarded',
    kri: 'Bounded history window: Retained',
    evidence: 'Pure timestamp normalization, JavaScript latest-check selection and regression tests.',
    limitation: 'Selection is limited to a bounded recent check-log window and does not change stored records.',
  },
  {
    id: 'accessible-changelog',
    title: 'Accessible bilingual changelog',
    summary: 'Localizes release records and adds keyboard-safe dialog behavior with reduced-motion support.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'English and Italian readers can inspect release impact without losing keyboard context.',
    kpi: 'Changelog keyboard path: Unlocked',
    kri: 'Assistive-technology coverage: Requires continued validation',
    evidence: 'Localized chrome, initial focus, focus containment, Escape close, restoration and reduced motion.',
    limitation: 'Automated checks support but do not replace testing with multiple assistive technologies.',
  },
  {
    id: 'demo-story-path',
    title: '90-second evidence product flow',
    summary: 'Connects notice clues, official evidence, qualified analysis and correction review in one sequence.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'A public product walkthrough can use implemented surfaces while preserving source and human-review boundaries.',
    kpi: 'Demo flow continuity: Unlocked',
    kri: 'Audience comprehension: Pending observation',
    evidence: 'Bilingual four-stage showcase sequence linked to live product routes.',
    limitation: 'The sequence is explanatory and does not represent measured product adoption.',
  },
  {
    id: 'feature-intelligence-atlas',
    title: 'Feature Intelligence Atlas',
    summary: 'Maps platform capabilities, dependencies, release impact, implementation proof and residual limits as one explorable system.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.11',
    endRelease: 'beta.11',
    benefit: 'Business and technical stakeholders can trace what the platform does, how capabilities connect and what remains unproven.',
    kpi: 'Feature-level traceability: Unlocked',
    kri: 'Inventory completeness and stakeholder comprehension: Requires continued validation',
    evidence: 'Typed capability inventory, dependency constellation, release chain, KPI/KRI inspector, implementation proof and responsive regression coverage.',
    limitation: 'The atlas reports qualitative inventory and assurance state, not adoption, performance, legal findings or compliance certification.',
  },
  {
    id: 'native-dashboard-contracts',
    title: 'Native dashboard intelligence contracts',
    summary: 'Adds deterministic dashboard grammar, action and layout contracts, evidence-source metadata and filtered export with provenance metadata without integrating the studied framework runtime.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.1',
    endRelease: '3.9.0-beta.1',
    benefit: 'Dashboard behavior, composition and export scope can be inspected through explicit native contracts.',
    kpi: 'Dashboard contract coverage: Unlocked',
    kri: 'Real-user workflow comprehension: Pending validation',
    evidence: 'Typed dashboard grammar, action graph, layout contract, source registry, view model, export manifest and regression suite.',
    limitation: 'Deterministic contracts improve traceability but do not prove user adoption or decision quality.',
  },
  {
    id: 'governed-regional-benchmark-visualizations',
    title: 'Governed regional and benchmark visualizations',
    summary: 'Routes the regional risk matrix and company or industry KPI radar through shared accessible chart specifications and evidence metadata.',
    domainId: 'experience',
    status: 'current',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.2',
    endRelease: '3.9.0-beta.2',
    benefit: 'Regional and benchmark comparisons expose exact values, provenance, missing assessments and limitations beside the visual encoding.',
    kpi: 'Governed visualization coverage: Extended to five chart families',
    kri: 'Cross-device and assistive-technology comprehension: Requires continued validation',
    evidence: 'Static ChartSpec registry, accessible chart frame, keyed KPI joins, evidence-gated compare source and focused regression tests.',
    limitation: 'Visual comparisons remain screening aids and do not establish legal compliance or complete market coverage.',
  },
  {
    id: 'editorial-pulse-distribution',
    title: 'Editorial Pulse and distribution assets',
    summary: 'Packages reviewed evidence-linked leads into deterministic editorial and social reuse formats.',
    domainId: 'distribution',
    status: 'current',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.13',
    endRelease: '3.9.0-beta.13',
    benefit: 'Editors can inspect, cite, download and embed one dated lead without reconstructing its source boundary.',
    kpi: 'Editorial reuse surface: Pulse, Story Packs, cards and embeds available',
    kri: 'Artifact staleness and interpretation: Dated scope and source re-verification remain required',
    evidence: 'Verified Pulse registry, deterministic ZIP tests, specific Open Graph images, DataDownload metadata, iframe citations and aggregate event reporting.',
    limitation: 'Availability of reuse assets does not establish publication, readership, conversion, source completeness or independent validation.',
  },
  {
    id: 'shareable-evidence-views',
    title: 'Shareable dashboard evidence views',
    summary: 'Encodes the public dashboard view in a versioned canonical URL and restores committed filter context through browser history.',
    domainId: 'distribution',
    status: 'current',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.2',
    endRelease: '3.9.0-beta.2',
    benefit: 'A reviewer can copy a reproducible public evidence view without rebuilding its visible filters manually.',
    kpi: 'Shareable evidence-view state: Unlocked',
    kri: 'Stale-link interpretation and context comprehension: Public state only; requires continued validation',
    evidence: 'Versioned dashboard URL codec, Copy view action, typed filter history policy, popstate restoration, fail-closed parsing and deterministic regression tests.',
    limitation: 'The URL contains public view state only. It excludes private evidence, identity, consent state and any guarantee that future source availability will match the original view.',
  },
  {
    id: 'coordinated-evidence-drilldown',
    title: 'Coordinated regional and KPI drill-down',
    summary: 'Commits region and audience context atomically from the heatmap and exposes an exact KPI inspector from the benchmark radar.',
    domainId: 'experience',
    status: 'current',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.2',
    endRelease: '3.9.0-beta.2',
    benefit: 'Readers can move from a visual signal to the precise regional context or KPI values and limitations behind it.',
    kpi: 'Coordinated visual evidence inspection: Heatmap context and KPI detail unlocked',
    kri: 'Real-user and assistive-technology comprehension: Requires validation; normalized values are not compliance or performance measures',
    evidence: 'Typed atomic region/audience action, one canonical history entry, keyboard-operable heatmap cells, KPI radar inspector, original and normalized values, missing/tie states and exact-value tables.',
    limitation: 'Drill-down improves traceability within available public evidence; it does not fill missing assessments, measure business performance or establish legal compliance.',
  },
  {
    id: 'mobile-email-intake',
    title: 'Local MIME email intake',
    summary: 'Decodes bounded .eml messages in browser memory and returns only locally reviewed policy clues.',
    domainId: 'intake',
    status: 'current',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.12',
    endRelease: '3.9.0-beta.12',
    benefit: 'A saved email can enter the existing notification-to-evidence workflow without mailbox access or server-side MIME transport.',
    kpi: 'Local email file intake: Plain-text and HTML MIME alternatives available',
    kri: 'Client and format compatibility: Limited to bounded .eml files and supported MIME structures',
    evidence: 'Dependency-free local MIME parser, transfer and header decoding, attachment exclusion, HTML text fallback, visible import state and focused tests.',
    limitation: 'The feature does not monitor a mailbox, receive forwarded mail, open attachments or recover unsupported and oversized messages.',
  },
  {
    id: 'mail-addins',
    title: 'Gmail and Outlook add-ins',
    summary: 'Evaluates dedicated in-app actions after privacy and security review of mobile intake.',
    domainId: 'distribution',
    status: 'planned',
    horizon: 'later',
    startRelease: 'later',
    endRelease: 'later',
    benefit: 'Lower-friction access inside common mail applications.',
    kpi: 'Mail application reach: External dependency',
    kri: 'Provider permissions and review: External dependency',
    evidence: 'Planned only after the inbound transport has passed privacy and security review.',
    limitation: 'Provider permission models and marketplace review are outside direct product control.',
    externalDependency: 'Google and Microsoft marketplace approval',
  },
  {
    id: 'public-integration-directory',
    title: 'Public integration directory',
    summary: 'Publishes a small read-only v1 contract for the curated Observatory registry and its public evidence boundaries.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.11',
    endRelease: '3.9.0-beta.11',
    benefit: 'Builders can inspect stable endpoints, source-gate semantics, cache policy and supported localization without requesting administrative access.',
    kpi: 'Public integration contract: Manifest and Observatory registry endpoints available',
    kri: 'Integration scope: Read-only metadata only; no policy text, administrative data or write actions',
    evidence: 'Versioned v1 routes, localized Observatory payload, published developer directory, source registry entry, navigation links and regression coverage.',
    limitation: 'The API does not ingest external feeds, provide webhooks, expose raw evidence or replace direct source review.',
  },
  {
    id: 'historical-suspensions',
    title: 'Historical suspended snapshots',
    summary: 'Makes safely qualified historical suspension states visible without reopening unverified evidence.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.10',
    endRelease: '3.9.0-beta.10',
    benefit: 'Researchers can distinguish recorded policy changes from retrieval interruptions and verified recoveries.',
    kpi: 'Historical source-state visibility: Sanitized transition ledger available',
    kri: 'Continuity-state misinterpretation: Operational states require the displayed evidence boundary',
    evidence: 'Bounded public continuity API, standardized transition builder, source-state filters, current-transition markers and focused regression tests.',
    limitation: 'The ledger exposes operational retrieval states only; it withholds policy text, raw failure reasons, private evidence and administrative records.',
  },
  {
    id: 'database-hardening',
    title: 'Production database hardening',
    summary: 'Moves beyond single-file production storage with scaling, recovery and access controls.',
    domainId: 'operations',
    status: 'planned',
    horizon: 'later',
    startRelease: 'later',
    endRelease: 'later',
    benefit: 'The planned database design addresses production concurrency, recovery and access control.',
    kpi: 'Database scaling path: Planned',
    kri: 'Migration and operations complexity: Pending design',
    evidence: 'Planned PostgreSQL evaluation, migration rehearsal, backup validation and access review.',
    limitation: 'Current Hostinger production uses access-controlled SQLite.',
  },
  {
    id: 'residency-assurance',
    title: 'Data residency evidence and DPA',
    summary: 'Documents hosting location, backup location, subprocessors and contractual evidence.',
    domainId: 'legal',
    status: 'planned',
    horizon: 'next',
    startRelease: 'next',
    endRelease: 'later',
    benefit: 'Operational statements can be backed by current documentary evidence.',
    kpi: 'Residency evidence pack: Planned',
    kri: 'Provider documentation: External dependency',
    evidence: 'Planned DPA, subprocessor register and dated hosting evidence review.',
    limitation: 'Public location wording is not a substitute for contractual documentation.',
    externalDependency: 'Current provider documentation and DPA',
  },
  {
    id: 'production-validation',
    title: 'Production pentest and end-to-end verification',
    summary: 'Tests listed attack paths and Hostinger deployment checks after release.',
    domainId: 'security',
    status: 'planned',
    horizon: 'next',
    startRelease: 'next',
    endRelease: 'next',
    benefit: 'Local assurance is checked against the actual deployed environment.',
    kpi: 'Production assurance: Pending validation',
    kri: 'Deployment-specific attack paths: Open',
    evidence: 'Planned authenticated E2E, post-deploy database check and independent dynamic security testing.',
    limitation: 'Local tests and static review cannot establish the deployed production posture.',
    externalDependency: 'Independent pentest capacity',
  },
  {
    id: 'renderer-hardening',
    title: 'Renderer production hardening',
    summary: 'Validates protected rendering, secret management, observability and controlled egress in production.',
    domainId: 'retrieval',
    status: 'planned',
    horizon: 'next',
    startRelease: 'next',
    endRelease: 'later',
    benefit: 'The planned renderer controls address retrieval of script-rendered official sources.',
    kpi: 'Rendered-source recovery: Pending validation',
    kri: 'Production secrets and SSRF boundary: Open',
    evidence: 'Planned secret rotation, egress verification, health checks and production retrieval fixtures.',
    limitation: 'The renderer remains dependent on production infrastructure and secrets.',
  },
  {
    id: 'beta-evidence-cycle',
    title: 'Real-user beta evidence cycle',
    summary: 'Collects structured usability, retrieval and operator evidence before stable promotion.',
    domainId: 'experience',
    status: 'planned',
    horizon: 'next',
    startRelease: 'next',
    endRelease: 'later',
    benefit: 'Stable promotion follows explicit evidence instead of version age.',
    kpi: 'Stable-promotion gate: Pending validation',
    kri: 'User-pilot evidence: Open',
    evidence: 'Planned scenario-based pilot, issue triage and documented release acceptance gate.',
    limitation: 'No adoption or comprehension improvement is claimed before the pilot.',
  },
];

export function getReleaseColumnIndex(releaseId: string) {
  return RELEASE_COLUMNS.findIndex((release) => release.id === releaseId);
}

export function getReleaseItems(releaseId: string) {
  const releaseIndex = getReleaseColumnIndex(releaseId);
  return RELEASE_IMPACT_ITEMS.filter((item) => {
    const start = getReleaseColumnIndex(item.startRelease);
    const end = getReleaseColumnIndex(item.endRelease);
    return releaseIndex >= start && releaseIndex <= end;
  });
}
