import { POLICYWATCHER_VERSION_DISPLAY } from './release';

export type ReleaseImpactKind = 'business' | 'technical';
export type ReleaseImpactStatus = 'delivered' | 'current' | 'planned';
export type ReleaseImpactHorizon = 'delivered' | 'next' | 'later';

export interface ReleaseColumn {
  id: string;
  shortLabel: string;
  label: string;
  state: ReleaseImpactStatus;
}

export interface ReleaseImpactDomain {
  id: string;
  label: string;
  kind: ReleaseImpactKind;
}

export interface ReleaseImpactItem {
  id: string;
  title: string;
  summary: string;
  domainId: string;
  status: ReleaseImpactStatus;
  horizon: ReleaseImpactHorizon;
  startRelease: string;
  endRelease: string;
  benefit: string;
  kpi: string;
  kri: string;
  evidence: string;
  limitation: string;
  externalDependency?: string;
}

export const RELEASE_IMPACT_UPDATED_AT = '2 August 2026' as const;

export const RELEASE_COLUMNS: ReleaseColumn[] = [
  { id: '3.7.0', shortLabel: '3.7.0', label: '3.7.0', state: 'delivered' },
  { id: '3.7.1', shortLabel: '3.7.1', label: '3.7.1', state: 'delivered' },
  { id: '3.7.2', shortLabel: '3.7.2', label: '3.7.2', state: 'delivered' },
  { id: '3.8.0', shortLabel: '3.8.0', label: '3.8.0', state: 'delivered' },
  { id: '3.8.1', shortLabel: '3.8.1', label: '3.8.1', state: 'delivered' },
  { id: '3.8.2', shortLabel: '3.8.2', label: '3.8.2', state: 'delivered' },
  { id: 'beta.2', shortLabel: 'B2', label: '3.8.3 Beta 2', state: 'delivered' },
  { id: 'beta.3', shortLabel: 'B3', label: '3.8.3 Beta 3', state: 'delivered' },
  { id: 'beta.4', shortLabel: 'B4', label: '3.8.3 Beta 4', state: 'delivered' },
  { id: 'beta.5', shortLabel: 'B5', label: '3.8.3 Beta 5', state: 'delivered' },
  { id: 'beta.6', shortLabel: 'B6', label: '3.8.3 Beta 6', state: 'delivered' },
  { id: 'beta.7', shortLabel: 'B7', label: '3.8.3 Beta 7', state: 'delivered' },
  { id: 'beta.8', shortLabel: 'B8', label: '3.8.3 Beta 8', state: 'delivered' },
  { id: 'beta.9', shortLabel: 'B9', label: '3.8.3 Beta 9', state: 'delivered' },
  { id: 'beta.10', shortLabel: 'B10', label: '3.8.3 Beta 10', state: 'delivered' },
  { id: 'beta.11', shortLabel: 'B11', label: '3.8.3 Beta 11', state: 'delivered' },
  { id: '3.9.0-beta.1', shortLabel: '3.9 B1', label: '3.9.0 Beta 1', state: 'delivered' },
  { id: '3.9.0-beta.2', shortLabel: '3.9 B2', label: '3.9.0 Beta 2', state: 'delivered' },
  { id: '3.9.0-beta.3', shortLabel: '3.9 B3', label: '3.9.0 Beta 3', state: 'delivered' },
  { id: '3.9.0-beta.4', shortLabel: '3.9 B4', label: '3.9.0 Beta 4', state: 'delivered' },
  { id: '3.9.0-beta.5', shortLabel: '3.9 B5', label: '3.9.0 Beta 5', state: 'delivered' },
  { id: '3.9.0-beta.6', shortLabel: '3.9 B6', label: '3.9.0 Beta 6', state: 'delivered' },
  { id: '3.9.0-beta.7', shortLabel: '3.9 B7', label: '3.9.0 Beta 7', state: 'delivered' },
  { id: '3.9.0-beta.8', shortLabel: '3.9 B8', label: '3.9.0 Beta 8', state: 'delivered' },
  { id: '3.9.0-beta.9', shortLabel: '3.9 B9', label: '3.9.0 Beta 9', state: 'delivered' },
  { id: '3.9.0-beta.10', shortLabel: '3.9 B10', label: '3.9.0 Beta 10', state: 'delivered' },
  { id: '3.9.0-beta.11', shortLabel: '3.9 B11', label: '3.9.0 Beta 11', state: 'delivered' },
  { id: '3.9.0-beta.12', shortLabel: '3.9 B12', label: '3.9.0 Beta 12', state: 'delivered' },
  { id: '3.9.0-beta.13', shortLabel: '3.9 B13', label: '3.9.0 Beta 13', state: 'delivered' },
  { id: '3.9.0-beta.14', shortLabel: '3.9 B14', label: '3.9.0 Beta 14', state: 'delivered' },
  { id: '3.9.0-beta.15', shortLabel: '3.9 B15', label: '3.9.0 Beta 15', state: 'delivered' },
  { id: '3.9.0-beta.16', shortLabel: '3.9 B16', label: '3.9.0 Beta 16', state: 'delivered' },
  { id: '3.9.0-beta.17', shortLabel: '3.9 B17', label: '3.9.0 Beta 17', state: 'delivered' },
  { id: '3.9.0-beta.18', shortLabel: '3.9 B18', label: '3.9.0 Beta 18', state: 'delivered' },
  { id: '3.9.0-beta.19', shortLabel: '3.9 B19', label: '3.9.0 Beta 19', state: 'delivered' },
  { id: '3.9.0-beta.20', shortLabel: '3.9 B20', label: '3.9.0 Beta 20', state: 'delivered' },
  { id: '3.9.0-beta.21', shortLabel: '3.9 B21', label: '3.9.0 Beta 21', state: 'delivered' },
  { id: '3.9.0-beta.22', shortLabel: '3.9 B22', label: '3.9.0 Beta 22', state: 'delivered' },
  { id: '3.9.0-beta.23', shortLabel: '3.9 B23', label: '3.9.0 Beta 23', state: 'delivered' },
  { id: '3.9.0-beta.24', shortLabel: '3.9 B24', label: '3.9.0 Beta 24', state: 'delivered' },
  { id: '3.9.0-beta.25', shortLabel: '3.9 B25', label: '3.9.0 Beta 25', state: 'delivered' },
  { id: '3.9.0-beta.26', shortLabel: '3.9 B26', label: '3.9.0 Beta 26', state: 'delivered' },
  { id: '3.9.0-beta.27', shortLabel: '3.9 B27', label: '3.9.0 Beta 27', state: 'delivered' },
  { id: '3.9.0-beta.28', shortLabel: '3.9 B28', label: '3.9.0 Beta 28', state: 'delivered' },
  { id: '3.9.0-beta.29', shortLabel: '3.9 B29', label: '3.9.0 Beta 29', state: 'delivered' },
  { id: '3.9.0-beta.30', shortLabel: '3.9 B30', label: '3.9.0 Beta 30', state: 'delivered' },
  { id: '3.9.0-beta.31', shortLabel: '3.9 B31', label: '3.9.0 Beta 31', state: 'delivered' },
  { id: '3.9.0-beta.32', shortLabel: '3.9 B32', label: '3.9.0 Beta 32', state: 'delivered' },
  { id: '3.9.0-beta.33', shortLabel: '3.9 B33', label: '3.9.0 Beta 33', state: 'delivered' },
  { id: '3.9.0-beta.34', shortLabel: '3.9 B34', label: '3.9.0 Beta 34', state: 'delivered' },
  { id: '3.9.0-beta.35', shortLabel: '3.9 B35', label: '3.9.0 Beta 35', state: 'delivered' },
  { id: '3.9.0-beta.36', shortLabel: '3.9 B36', label: '3.9.0 Beta 36', state: 'delivered' },
  { id: '3.9.0-beta.37', shortLabel: '3.9 B37', label: '3.9.0 Beta 37', state: 'delivered' },
  { id: '3.9.0-beta.38', shortLabel: '3.9 B38', label: '3.9.0 Beta 38', state: 'delivered' },
  { id: '3.9.0-beta.39', shortLabel: '3.9 B39', label: POLICYWATCHER_VERSION_DISPLAY, state: 'current' },
  { id: 'next', shortLabel: 'Next', label: 'Next beta horizon', state: 'planned' },
  { id: 'later', shortLabel: 'Later', label: 'Later horizon', state: 'planned' },
];

export const RELEASE_IMPACT_DOMAINS: ReleaseImpactDomain[] = [
  { id: 'experience', label: 'User experience', kind: 'business' },
  { id: 'corrections', label: 'Correction operations', kind: 'business' },
  { id: 'distribution', label: 'Channel distribution', kind: 'business' },
  { id: 'legal', label: 'Legal resilience', kind: 'business' },
  { id: 'intake', label: 'Evidence intake', kind: 'technical' },
  { id: 'retrieval', label: 'Retrieval', kind: 'technical' },
  { id: 'assurance', label: 'Data assurance', kind: 'technical' },
  { id: 'security', label: 'Security', kind: 'technical' },
  { id: 'operations', label: 'Production operations', kind: 'technical' },
];

export const RELEASE_IMPACT_ITEMS: ReleaseImpactItem[] = [
  {
    id: 'word-contract-evidence-review',
    title: 'Word Contract Evidence Review',
    summary: 'Classifies an explicitly selected Word clause locally and queries related public evidence with fixed topic labels only.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.30',
    endRelease: '3.9.0-beta.30',
    benefit: 'A reviewer can move from a clause in Word to cited PolicyWatcher public evidence without transmitting the selected clause.',
    kpi: 'Data-minimization controls available: explicit capture, fixed taxonomy, displayed derived topics, separate acknowledgement and bounded public query',
    kri: 'Residual KRI: topic matching can be incomplete or imprecise and returned public evidence can require additional professional review',
    evidence: 'Word task pane, Office sideload manifest, fixed-taxonomy derivation, route-specific CSP, network-minimized query and focused tests.',
    limitation: 'The source package is not tenant-deployed or AppSource-published and does not verify, approve or legally assess a contract.',
    externalDependency: 'Customer Microsoft 365 tenant policy, sideload approval and supported Word host',
  },
  {
    id: 'multicloud-agent-source-packages',
    title: 'Multi-cloud Agent Source Packages',
    summary: 'Packages one public evidence contract for Microsoft 365 Copilot, Vertex AI Agent Builder and Amazon Quick pilots.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.29',
    endRelease: '3.9.0-beta.29',
    benefit: 'Enterprise teams can validate PolicyWatcher dialogue from their chosen agent environment without copying the public dataset into a new product surface.',
    kpi: 'Provider source packages available: Microsoft 365 declarative agent, Vertex AI OpenAPI tool and Amazon Quick OpenAPI connector',
    kri: 'Residual KRI: provider manifest rules, tenant approvals, cloud controls and product capabilities can change outside PolicyWatcher',
    evidence: 'Versioned provider manifests, generated OpenAPI descriptions, deterministic agent instructions and controlled-pilot runbooks.',
    limitation: 'Source-package readiness is not deployment, certification, marketplace publication, tenant approval or customer adoption.',
    externalDependency: 'Microsoft 365, Google Cloud and AWS customer administration',
  },
  {
    id: 'agent-evidence-gateway',
    title: 'Cross-cloud Agent Evidence Gateway',
    summary: 'Exposes three deterministic public evidence operations through a flattened OpenAPI contract designed for enterprise agent tools.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.28',
    endRelease: '3.9.0-beta.28',
    benefit: 'Agent clients receive source-linked public change and Observatory briefs from one read-only contract with explicit empty-state semantics.',
    kpi: 'Gateway contract available: three GET operations, five-result maximum, bounded filters, citations, timestamps and explicit boundary',
    kri: 'Residual KRI: public evidence can be unavailable, withheld, incomplete or unmatched; zero results do not establish absence',
    evidence: 'Agent routes, cross-platform OpenAPI, publication-gated data access, privacy-bounded rate limiting and schema/query tests.',
    limitation: 'The gateway accepts no private tenant data, arbitrary prompt transcript or contract body and does not produce legal or compliance verdicts.',
  },
  {
    id: 'admin-operational-readiness',
    title: 'Operational Readiness Dashboard',
    summary: 'Connects deterministic protected priorities, publication readiness, independent live status, role-safe actions and bounded measurement in one administrative evidence sequence.',
    domainId: 'operations',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.27',
    endRelease: '3.9.0-beta.27',
    benefit: 'Administrators receive one responsible-console action per priority while Auditors receive read-only verification routes over the same bounded operational evidence.',
    kpi: 'Implementation inventory: at most five priorities, five readiness stages, four independently loaded status cards and five bounded dashboard measurement definitions',
    kri: 'Residual KRI: unavailable metrics, absent scans or missing modules can limit the view and must not be interpreted as zero or healthy',
    evidence: 'Protected Action Center, Publication Readiness Funnel, live-status endpoints, role presentation mapping, privacy-minimized telemetry contract, text alternatives and focused regression tests.',
    limitation: 'The dashboard does not certify operational health, task completion, usability, accessibility, service levels, security or compliance. Server-side authorization remains authoritative.',
  },
  {
    id: 'crawlable-public-knowledge-layer',
    title: 'Crawlable Public Knowledge Layer',
    summary: 'Publishes evidence-gated company and policy references as server-rendered HTML with canonical entity routes and bounded machine discovery.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.26',
    endRelease: '3.9.0-beta.26',
    benefit: 'Readers, crawlers and answer engines can retrieve the same bounded public reference content without depending on client-side dashboard execution.',
    kpi: 'Public discovery controls available: SSR index, canonical entity pages, crawlable home snapshot, sitemap, robots.txt, llms.txt and visible structured data',
    kri: 'Residual KRI: discovery controls do not guarantee indexing, citation, ranking, freshness or inclusion by external engines',
    evidence: 'Initial-HTML Knowledge routes, shared publication gates, canonical metadata, citations, crawler files, structured-data serialization and focused regression coverage.',
    limitation: 'The layer exposes public metadata and evidence links only; raw policy text, internal diagnostics, admin notes, credentials and withheld records remain unavailable.',
  },
  {
    id: 'admin-shell-readability',
    title: 'Admin Shell Readability',
    summary: 'Makes protected route, role, active navigation and keyboard entry explicit across the shared administrative shell.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.25',
    endRelease: '3.9.0-beta.25',
    benefit: 'Administrators and auditors can identify their role and current protected workspace before interpreting page-specific operations.',
    kpi: 'Shared-shell controls available: explicit role and route, structural active marker, skip link, 44px controls and 12px secondary-text floor',
    kri: 'Residual KRI: implementation checks do not establish measured task-time reduction or accessibility certification',
    evidence: 'Shared layout and CSS changes, stable main target, accessible verification states, preserved drawer focus handling and focused regression coverage.',
    limitation: 'The release changes the shared administrative frame only; authentication, authorization, protected-page behavior and API contracts are unchanged.',
  },
  {
    id: 'webhook-operations-ux',
    title: 'Webhook Operations UX',
    summary: 'Reorders the protected webhook console around one evidence-based next action and adds local exception, schedule and identifier filtering.',
    domainId: 'operations',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.24',
    endRelease: '3.9.0-beta.24',
    benefit: 'Administrators and auditors can move from returned delivery state to the relevant ledger records without scanning every row.',
    kpi: 'Operational controls available: one derived focus, four status views, identifier search, result count and explicit reset',
    kri: 'Residual KRI: the recommendation describes the returned ledger window and does not establish exhaustive delivery health',
    evidence: 'Exception-first focus logic, client-side ledger filters, distinct empty states, responsive 12px typography floor, role-safe actions, focused UI tests and browser evaluation.',
    limitation: 'The release changes presentation and navigation only; it does not alter delivery scheduling, receiver behavior, retry policy, authorization or service commitments.',
  },
  {
    id: 'configured-webhook-delivery-pilot',
    title: 'Configured Webhook Delivery Pilot',
    summary: 'Delivers eligible public change events to deployment-configured HTTPS destinations through a persistent signed outbox and bounded retry ledger.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.23',
    endRelease: '3.9.0-beta.23',
    benefit: 'A controlled integration pilot can receive the existing public change-event envelope without polling, while operators retain an inspectable delivery state.',
    kpi: 'Delivery controls available: HMAC signature, persistent outbox, per-attempt ledger, bounded retry schedule and protected operator console',
    kri: 'Residual KRI: destination identity, network behavior and receiver processing remain external; delivery is not guaranteed',
    evidence: 'Strict deployment configuration, exact HTTPS-origin allowlist, stable event identity, atomic delivery claims, attempt records, admin and cron routes, migration and focused regression coverage.',
    limitation: 'The pilot has no public subscription form, tenant self-service, endpoint challenge, automatic key rotation, guaranteed delivery or service-level commitment.',
  },
  {
    id: 'event-feed-continuity-lab',
    title: 'Event Feed Continuity Lab',
    summary: 'Inspects the public forward-polling feed, maintains a bounded browser-local checkpoint and reports observable consumer continuity conditions.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.22',
    endRelease: '3.9.0-beta.22',
    benefit: 'Developers can exercise initial-window, checkpoint and resume behavior without creating an account or moving consumer state to PolicyWatcher.',
    kpi: 'Polling continuity controls: strict local checkpoint, explicit resume, duplicate and ordering inspection available',
    kri: 'Residual KRI: a clean returned window cannot establish exhaustive monitoring, network delivery or absence of events outside the public feed',
    evidence: 'Bounded checkpoint parser, deterministic JSON export, continuity report, explicit request state, responsive public workbench and focused regression coverage.',
    limitation: 'The lab provides no endpoint registration, webhook subscription, push delivery, server-side replay store, delivery receipt, external-system acknowledgment or service-level commitment.',
  },
  {
    id: 'source-reliability-control-plane',
    title: 'Source Reliability control plane',
    summary: 'Persists scan and retrieval outcomes, deduplicates shared acquisitions and exposes bounded remediation state to protected operators.',
    domainId: 'retrieval',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.21',
    endRelease: '3.9.0-beta.21',
    benefit: 'Operators can distinguish configured policy rows, unique retrievals, withheld records and repeated failures before interpreting an empty public surface.',
    kpi: 'Operational traceability: persisted scan runs, retrieval keys and public-baseline coverage',
    kri: 'Residual KRI: source access, content stability and exact-evidence eligibility remain external and record-specific',
    evidence: 'Normalized acquisition keys, additive Prisma records, structured cause codes, protected admin metrics and focused regression coverage.',
    limitation: 'Reliability telemetry describes PolicyWatcher retrieval and publication state; it does not certify source authenticity, completeness or availability.',
  },
  {
    id: 'verified-public-baseline-repair',
    title: 'Verified public baseline repair',
    summary: 'Promotes exact source-supported snapshots to first public baselines without manufacturing a change event or analytical result.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.21',
    endRelease: '3.9.0-beta.21',
    benefit: 'A successful first scan can make supported company and policy records visible while unsupported seed data stays withheld.',
    kpi: 'Evidence-gate repair: dry-run plan and exact-hash promotion path available',
    kri: 'Residual KRI: operators must review the plan, preserve a database backup and complete a fresh scan',
    evidence: 'First-baseline gate correction, dry-run-first Hostinger repair, read-only inventory audit and no-change-event tests.',
    limitation: 'The repair cannot infer missing evidence, bypass a source restriction or convert a stale archive reference into a current baseline.',
  },
  {
    id: 'receiver-conformance-lab',
    title: 'Receiver Conformance Lab',
    summary: 'Runs a deterministic batch of positive and negative webhook receiver decisions against the documented candidate contract.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.21',
    endRelease: '3.9.0-beta.21',
    benefit: 'Integration developers can compare expected and actual decisions across the complete published fixture set and export local results.',
    kpi: 'Contract coverage: eight deterministic receiver fixtures and every documented decision code',
    kri: 'Residual KRI: a passing local suite does not establish endpoint identity, production secret custody or network delivery reliability',
    evidence: 'Public conformance endpoint, JSON Schema, browser-local runner, bounded export and contract/API/UI tests.',
    limitation: 'The suite is a compatibility aid, not certification; it provides no registration, subscriptions, retries, replay storage or delivery receipts.',
  },
  {
    id: 'verified-browser-store-distribution',
    title: 'Verified browser-store distribution',
    summary: 'Publishes a direct Chrome Web Store action and reports Chrome, Edge and Safari availability as independent verified states.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.9',
    endRelease: '3.9.0-beta.9',
    benefit: 'Users can reach the published Chrome listing directly and are not shown a shared pending status for unrelated browser stores.',
    kpi: 'Verified browser-store destinations: One public Chrome listing',
    kri: 'Edge and Safari distribution: No verified public listing',
    evidence: 'Public Chrome Web Store listing, official-host URL validation, store-specific availability copy and regression coverage.',
    limitation: 'The verified state records public distribution only; it does not change extension behavior, review other browser stores or establish user adoption.',
    externalDependency: 'Microsoft Edge Add-ons and Apple App Store publication',
  },
  {
    id: 'assistant-entry-point-consolidation',
    title: 'Assistant entry-point consolidation',
    summary: 'Removes the legacy floating chat trigger while retaining assistant access in unified navigation, Workspace Controls and command search.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.8',
    endRelease: '3.9.0-beta.8',
    benefit: 'The dashboard presents one persistent assistant control instead of two competing fixed actions.',
    kpi: 'Persistent assistant triggers on the dashboard: One unified navigation control',
    kri: 'Discoverability dependency: Users must recognize the labelled navigation or Workspace Controls action',
    evidence: 'Unified Navigation assistant command, labelled Workspace Controls action, Command Palette action and duplicate-trigger regression coverage.',
    limitation: 'This release changes assistant discovery only; it does not change generated answers, model behavior or the chat API.',
  },
  {
    id: 'newsroom-measurement-and-release-assurance',
    title: 'Newsroom measurement and release assurance',
    summary: 'Improves mobile Press Kit access, adds privacy-minimized aggregate newsroom event counts and closes scoped release-security findings.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.7',
    endRelease: '3.9.0-beta.7',
    benefit: 'Editors reach core facts and actions sooner on mobile while authorized operators can inspect bounded distribution signals.',
    kpi: 'Measured newsroom signals: Package-download intentions, Data Room views and press-contact intentions',
    kri: 'Interpretation risk: Aggregate events can include automation and do not identify unique people or confirmed outcomes',
    evidence: 'Mobile Fast Facts, horizontal action rail with visible cue, readable Claim Registry metadata, compact utility footer, allowlisted first-party event endpoint, protected 30-day and all-time aggregates, migration and regression tests.',
    limitation: 'No target or conversion rate is stated before baseline data exists; telemetry writes are non-blocking and can be lost.',
  },
  {
    id: 'evidence-newsroom',
    title: 'Evidence Newsroom',
    summary: 'Extends the Press Kit with versioned packages, dated claim records, release feeds, reusable data and public reference registers.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.6',
    endRelease: '3.9.0-beta.6',
    benefit: 'Journalists and fact-checkers can download dated assets, inspect claim freshness and follow release records without reconstructing context.',
    kpi: 'Editorial distribution surfaces: Package, registry, feed and data room available',
    kri: 'Later reuse of snapshots: Live-source revalidation remains required',
    evidence: 'Localized press ZIPs, asset and package manifests, IPTC/XMP metadata, claim registry, release archive, RSS, JSON Feed, data snapshot and specialized mail routes.',
    limitation: 'The newsroom improves reuse and traceability; it does not establish media coverage, factual endorsement, legal compliance or Content Credentials.',
  },
  {
    id: 'press-kit-navigation-discovery',
    title: 'Press Kit navigation discovery',
    summary: 'Adds a direct Press Kit link to dashboard controls, the public header and command search.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.5',
    endRelease: '3.9.0-beta.5',
    benefit: 'Press information is reachable from the dashboard and shared public navigation.',
    kpi: 'Press Kit navigation entry points: Three',
    kri: 'Production visibility: Requires deployment of the matching web release',
    evidence: 'Workspace Controls item, shared public-header item, Command Palette action and navigation regression test.',
    limitation: 'Navigation availability remains dependent on the deployed web release.',
  },
  {
    id: 'public-claim-language-governance',
    title: 'Public claim language governance',
    summary: 'Uses scoped descriptions of implemented behavior, evidence boundaries, dates and known limitations across public and press-facing copy.',
    domainId: 'legal',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.4',
    endRelease: '3.9.0-beta.4',
    benefit: 'Readers receive concrete product statements with stated scope and limitations.',
    kpi: 'Selected public claim surfaces: Editorial rule enforced',
    kri: 'Underlying data and external status accuracy: Requires separate validation',
    evidence: 'Cross-site copy audit, revised press fact sheet and outreach guide, point-in-time security wording and an editorial regression test.',
    limitation: 'The editorial control detects listed wording patterns; it does not validate source data, deployed configuration or external services.',
  },
  {
    id: 'editorial-briefing-room',
    title: 'Editorial briefing room',
    summary: 'Publishes a bilingual, evidence-led press kit with a claim ledger, owned assets and stable machine-readable metadata.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.3',
    endRelease: '3.9.0-beta.3',
    benefit: 'Journalists and analysts can verify bounded product claims before reusing them.',
    kpi: 'Press evidence surface: Published',
    kri: 'Independent coverage and reader comprehension: Not assessed',
    evidence: 'Public press kit, six-entry claim ledger, checksummed asset manifest, JSON-LD and stable JSON endpoint.',
    limitation: 'The newsroom contains owned materials; it does not prove independent adoption, compliance or exhaustive coverage.',
  },
  {
    id: 'notification-evidence',
    title: 'Notification to evidence inquiry',
    summary: 'Turns user-confirmed clues from a policy notice into a source-gated portfolio inquiry.',
    domainId: 'intake',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.7.0',
    endRelease: '3.7.1',
    benefit: 'A direct path from a real notice to public evidence without treating the notice as proof.',
    kpi: 'Public evidence boundary: Guarded',
    kri: 'Unknown source quality: Human approval required',
    evidence: 'Local clue confirmation, publicEvidence filtering, inquiry queue and conflict handling.',
    limitation: 'Inquiry to discovery remains intentionally human-approved.',
  },
  {
    id: 'calm-workspace',
    title: 'Calm evidence workspace',
    summary: 'Adapts the first-use workspace to user objective and evidence depth.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.7.2',
    endRelease: '3.7.2',
    benefit: 'The initial workspace presents objective, evidence depth and Source QA in one flow.',
    kpi: 'Workspace orientation: Unlocked',
    kri: 'Real-user comprehension: Pending validation',
    evidence: 'Objective composer, progressive controls, local preferences and mobile navigation.',
    limitation: 'Observed user evidence is still needed before stable promotion.',
  },
  {
    id: 'browser-companion',
    title: 'Browser Evidence Companion',
    summary: 'Extracts minimal clues inside the active tab after an explicit user gesture.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.8.0',
    endRelease: 'beta.3',
    benefit: 'Chrome users can inspect a notice without persistent mailbox access.',
    kpi: 'Chrome notice path: Unlocked',
    kri: 'Edge and Safari distribution: External dependency',
    evidence: 'Browser extension 3.8.3 Beta 3 is publicly listed in the Chrome Web Store and retains local parsing with explicit confirmation.',
    limitation: 'No official Edge Add-ons listing is currently verified. Safari still needs signing, packaging and review.',
    externalDependency: 'Edge listing verification and Safari signing and review',
  },
  {
    id: 'regional-discovery',
    title: 'Regional policy discovery',
    summary: 'Retains locale-specific official policy variants through discovery and review.',
    domainId: 'retrieval',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.8.2',
    endRelease: 'beta.4',
    benefit: 'Regional variants survive discovery for human source review.',
    kpi: 'Regional candidate coverage: Unlocked',
    kri: 'SPA retrieval coverage: Production dependency',
    evidence: 'URL locale inference, hreflang extraction, locale probes and bounded candidate caps.',
    limitation: 'Some script-rendered sites still depend on the production renderer.',
  },
  {
    id: 'inquiry-publication-gate',
    title: 'Inquiry publication gate',
    summary: 'Keeps inquiry-derived sources private through baseline capture, QA and explicit publication.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.4',
    endRelease: 'beta.6',
    benefit: 'New sources cannot become public evidence from an inquiry alone.',
    kpi: 'Publication boundary: Guarded',
    kri: 'Operator review capacity: Residual dependency',
    evidence: 'Onboarding batch, private baseline, hash, QA review and explicit publish state.',
    limitation: 'Publication quality still depends on trained operator review.',
  },
  {
    id: 'qualified-language',
    title: 'Qualified public analysis language',
    summary: 'Frames automated output as textual attention signals with explicit evidence dates and limits.',
    domainId: 'legal',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.5',
    endRelease: 'beta.6',
    benefit: 'Readers can distinguish a text-derived indicator from a legal determination.',
    kpi: 'Method boundary visibility: Unlocked',
    kri: 'Professional legal review: External dependency',
    evidence: 'Updated public pages, share views, reports, PDF wording and methodology disclaimers.',
    limitation: 'Qualified language reduces ambiguity but does not remove legal risk.',
    externalDependency: 'Independent professional legal review',
  },
  {
    id: 'correction-channel',
    title: 'Human correction channel',
    summary: 'Provides a direct route to report an inaccuracy or request a rerun.',
    domainId: 'corrections',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.6',
    endRelease: 'beta.6',
    benefit: 'Affected organizations have a visible cooperative review route.',
    kpi: 'Correction channel coverage: Unlocked',
    kri: 'Case tracking and identity assurance: Pending',
    evidence: 'Review-request page and links on change, share and PDF surfaces.',
    limitation: 'The current channel does not persist cases or alter public indicators automatically.',
  },
  {
    id: 'request-hardening',
    title: 'Public request boundary hardening',
    summary: 'Bounds chat and speech requests, minimizes logs and narrows default context.',
    domainId: 'security',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.5',
    endRelease: 'beta.6',
    benefit: 'Predictable input and privacy boundaries for exposed services.',
    kpi: 'Request abuse controls: Guarded',
    kri: 'Dynamic production attack paths: Pending validation',
    evidence: 'Bounded JSON parsing, input caps, rate controls, masked logs and focused tests.',
    limitation: 'A production pentest is still required.',
  },
  {
    id: 'hostinger-recovery',
    title: 'Hostinger database recovery',
    summary: 'Separates session access from metrics and exposes protected read-only database readiness alongside deployment-time schema reconciliation.',
    domainId: 'operations',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.6',
    endRelease: 'beta.6',
    benefit: 'Operators can recover an outdated schema without replacing the database.',
    kpi: 'Operator recovery path and readiness inspection: Available',
    kri: 'Restore execution and post-deploy production result: Require operator validation',
    evidence: 'Database-independent admin session, non-blocking optional metrics, managed-install initializer, bounded schema diagnostics and protected readiness panel.',
    limitation: 'The readiness panel is read-only and does not migrate, reset, repair or restore production data.',
  },
  {
    id: 'impact-clarity',
    title: 'Release impact clarity',
    summary: 'Connects releases to affected domains, unlocked outcomes, evidence and residual risks.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.7',
    endRelease: 'beta.7',
    benefit: 'Business and technical stakeholders can inspect one release record.',
    kpi: 'Release impact traceability: Unlocked',
    kri: 'Stakeholder comprehension: Pending validation',
    evidence: 'Shared release-impact dataset, interactive matrix, KPI and KRI inspector.',
    limitation: 'The map reports release evidence, not measured adoption or business performance.',
  },
  {
    id: 'public-surface-consistency',
    title: 'Public evidence consistency',
    summary: 'Aligns explanatory, evidence ranking and correction routes around one public evidence language.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.8',
    endRelease: 'beta.8',
    benefit: 'Visitors can distinguish live database evidence, explanatory product guides and human review workflows within the public interface.',
    kpi: 'Public surface provenance: Unlocked',
    kri: 'Cross-route comprehension: Pending validation',
    evidence: 'Shared public chrome, recurring evidence-status rail, persisted snapshot timestamp, fail-closed empty state and bilingual correction workflow.',
    limitation: 'The release improves provenance visibility but does not turn the evidence index into a compliance assessment.',
  },
  {
    id: 'verified-corrections',
    title: 'Correction case management',
    summary: 'Adds identity and domain verification, anti-abuse controls, human triage and audited case states.',
    domainId: 'corrections',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.9',
    endRelease: 'beta.9',
    benefit: 'A recorded route from email and domain confirmation to scoped human review.',
    kpi: 'Correction case workflow: Unlocked',
    kri: 'Identity abuse and complaint flooding: Human gate retained',
    evidence: 'One-time email verification, keyed address hashing, registrable-domain checks, bounded intake, rate limits, deduplication and audited human transitions.',
    limitation: 'A complaint alone will not suspend an indicator or create a public badge.',
  },
  {
    id: 'public-review-state',
    title: 'Evidence-scoped public review state',
    summary: 'Shows review in progress and permits suspension only for accepted, evidence-scoped cases.',
    domainId: 'legal',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.9',
    endRelease: 'beta.9',
    benefit: 'Readers can see when specific evidence is under an accepted review case.',
    kpi: 'Public review state: Unlocked',
    kri: 'Platform-wide abuse: Scope isolated',
    evidence: 'Private submission state, admin acceptance, public evidence badge, record-scoped suspension and public resolution timeline.',
    limitation: 'No complaint-only automatic suspension. Effects remain limited to the contested evidence.',
  },
  {
    id: 'source-recovery-console',
    title: 'Source Recovery Console',
    summary: 'Separates suspension cause, recorded evidence, latest attempt and the next scoped operator action.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'Readers and operators can understand why public evidence is withheld without seeing internal errors.',
    kpi: 'Suspension cause clarity: Unlocked',
    kri: 'Source remediation outcome: Not guaranteed',
    evidence: 'Bilingual category mapping, evidence rail, bounded disclosure and direct methodology links.',
    limitation: 'The console explains recorded state and does not claim that a blocked source can always be recovered.',
  },
  {
    id: 'latest-check-clarity',
    title: 'Latest-check status presentation',
    summary: 'Normalizes mixed historical timestamp shapes before selecting the latest recorded check.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'Public suspension evidence reflects the most recent recorded attempt across legacy timestamp formats.',
    kpi: 'Mixed timestamp selection: Guarded',
    kri: 'Bounded history window: Retained',
    evidence: 'Pure timestamp normalization, JavaScript latest-check selection and regression tests.',
    limitation: 'Selection is limited to a bounded recent check-log window and does not change stored records.',
  },
  {
    id: 'accessible-changelog',
    title: 'Accessible bilingual changelog',
    summary: 'Localizes release records and adds keyboard-safe dialog behavior with reduced-motion support.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'English and Italian readers can inspect release impact without losing keyboard context.',
    kpi: 'Changelog keyboard path: Unlocked',
    kri: 'Assistive-technology coverage: Requires continued validation',
    evidence: 'Localized chrome, initial focus, focus containment, Escape close, restoration and reduced motion.',
    limitation: 'Automated checks support but do not replace testing with multiple assistive technologies.',
  },
  {
    id: 'demo-story-path',
    title: '90-second evidence product flow',
    summary: 'Connects notice clues, official evidence, qualified analysis and correction review in one sequence.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.10',
    endRelease: 'beta.10',
    benefit: 'A public product walkthrough can use implemented surfaces while preserving source and human-review boundaries.',
    kpi: 'Demo flow continuity: Unlocked',
    kri: 'Audience comprehension: Pending observation',
    evidence: 'Bilingual four-stage showcase sequence linked to live product routes.',
    limitation: 'The sequence is explanatory and does not represent measured product adoption.',
  },
  {
    id: 'feature-intelligence-atlas',
    title: 'Feature Intelligence Atlas',
    summary: 'Maps platform capabilities, dependencies, release impact, implementation proof and residual limits as one explorable system.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: 'beta.11',
    endRelease: 'beta.11',
    benefit: 'Business and technical stakeholders can trace what the platform does, how capabilities connect and what remains unproven.',
    kpi: 'Feature-level traceability: Unlocked',
    kri: 'Inventory completeness and stakeholder comprehension: Requires continued validation',
    evidence: 'Typed capability inventory, dependency constellation, release chain, KPI/KRI inspector, implementation proof and responsive regression coverage.',
    limitation: 'The atlas reports qualitative inventory and assurance state, not adoption, performance, legal findings or compliance certification.',
  },
  {
    id: 'native-dashboard-contracts',
    title: 'Native dashboard intelligence contracts',
    summary: 'Adds deterministic dashboard grammar, action and layout contracts, evidence-source metadata and filtered export with provenance metadata without integrating the studied framework runtime.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.1',
    endRelease: '3.9.0-beta.1',
    benefit: 'Dashboard behavior, composition and export scope can be inspected through explicit native contracts.',
    kpi: 'Dashboard contract coverage: Unlocked',
    kri: 'Real-user workflow comprehension: Pending validation',
    evidence: 'Typed dashboard grammar, action graph, layout contract, source registry, view model, export manifest and regression suite.',
    limitation: 'Deterministic contracts improve traceability but do not prove user adoption or decision quality.',
  },
  {
    id: 'governed-regional-benchmark-visualizations',
    title: 'Governed regional and benchmark visualizations',
    summary: 'Routes the regional risk matrix and company or industry KPI radar through shared accessible chart specifications and evidence metadata.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.2',
    endRelease: '3.9.0-beta.2',
    benefit: 'Regional and benchmark comparisons expose exact values, provenance, missing assessments and limitations beside the visual encoding.',
    kpi: 'Governed visualization coverage: Extended to five chart families',
    kri: 'Cross-device and assistive-technology comprehension: Requires continued validation',
    evidence: 'Static ChartSpec registry, accessible chart frame, keyed KPI joins, evidence-gated compare source and focused regression tests.',
    limitation: 'Visual comparisons remain screening aids and do not establish legal compliance or complete market coverage.',
  },
  {
    id: 'editorial-pulse-distribution',
    title: 'Editorial Pulse and distribution assets',
    summary: 'Packages reviewed evidence-linked leads into deterministic editorial and social reuse formats.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.13',
    endRelease: '3.9.0-beta.13',
    benefit: 'Editors can inspect, cite, download and embed one dated lead without reconstructing its source boundary.',
    kpi: 'Editorial reuse surface: Pulse, Story Packs, cards and embeds available',
    kri: 'Artifact staleness and interpretation: Dated scope and source re-verification remain required',
    evidence: 'Verified Pulse registry, deterministic ZIP tests, specific Open Graph images, DataDownload metadata, iframe citations and aggregate event reporting.',
    limitation: 'Availability of reuse assets does not establish publication, readership, conversion, source completeness or independent validation.',
  },
  {
    id: 'protected-press-outreach-desk',
    title: 'Protected Press Outreach Desk',
    summary: 'Turns reviewed public release assets into five fixed campaign workflows with local readiness checks and aggregate operational measurement.',
    domainId: 'operations',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.14',
    endRelease: '3.9.0-beta.14',
    benefit: 'An authorized operator can verify assets, reuse reviewed copy and inspect bounded outreach signals without building recipient histories in PolicyWatcher.',
    kpi: 'Operating KPI · qualified editorial reuse events reported with all-time and 30-day drivers',
    kri: 'Residual KRI · proxy counts can include automation or manual-entry error and do not establish delivery or editorial outcomes',
    evidence: 'Protected outreach route, five-campaign typed registry, release-versioned local checklist, strict public/admin event parsers, role enforcement and focused tests.',
    limitation: 'The desk does not send email, verify availability automatically, store contacts, confirm delivery or calculate conversion rates.',
  },
  {
    id: 'citable-coverage-registry',
    title: 'Citable Coverage Registry',
    summary: 'Replaces manual coverage-wall data with a typed public registry, derived totals and reusable machine-readable distributions.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.15',
    endRelease: '3.9.0-beta.15',
    benefit: 'Editors and researchers can inspect each external reference with a stable ID, source URL, date precision, citation and relationship boundary.',
    kpi: 'Registry contract · source-linked records available as HTML, JSON and CSV',
    kri: 'Residual KRI · source availability and third-party statements can change after the recorded review date',
    evidence: 'Typed registry, derived summaries, strict JSON/CSV endpoint, published schema, Dataset and ItemList metadata, source actions and regression tests.',
    limitation: 'Registry inclusion does not establish endorsement, certification, independent audit, readership, reach or factual validation.',
  },
  {
    id: 'evidence-governance-packets',
    title: 'Evidence Governance Packets',
    summary: 'Binds sanitized source-confidence state, exact snapshot fingerprints, score trace, verified source passages, advisory framework relevance and report downloads to one public change ID.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.16',
    endRelease: '3.9.0-beta.16',
    benefit: 'Reviewers can inspect and download one deterministic evidence record without mixing a historical permalink with a later policy analysis.',
    kpi: 'Evidence packet contract · exact-change HTML, JSON and PDF surfaces available',
    kri: 'Residual KRI · stored AI reasons can lack a verified source passage and framework mappings require qualified human interpretation',
    evidence: 'Change-bound packet query, public-evidence snapshot gate, sanitized retrieval state, exact substring validation, typed governance registry, deterministic content digest, PDF/JSON endpoints and regression tests.',
    limitation: 'The packet records review evidence and advisory relevance; it is not legal advice, compliance assessment, certification or proof of continuing source availability.',
  },
  {
    id: 'shareable-evidence-collections',
    title: 'Shareable Evidence Collections',
    summary: 'Lets reviewers select up to 12 exact public changes, keep personal review state in the browser, share an ID-only collection URL and download deterministic JSON, Markdown or CSV bundles.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.17',
    endRelease: '3.9.0-beta.17',
    benefit: 'A bounded set of public evidence records can be reviewed and handed to another person or generic workflow without copying private notes or rebuilding citations.',
    kpi: 'Portable collection contract · local selection, canonical URL and three deterministic formats available',
    kri: 'Residual KRI · shared links contain public IDs only and do not provide access control, persistent collaboration or notification delivery',
    evidence: 'Browser-local review state, 12-record ceiling, exact-change public gate, canonical query parser, per-record digests, collection digest, JSON/Markdown/CSV API and injection-safe serializers.',
    limitation: 'Collections are portable public evidence bundles, not persistent team workspaces, vendor integrations, complete market samples, legal advice or compliance assessments.',
  },
  {
    id: 'evidence-workflow-refinements',
    title: 'Evidence Workflow Refinements',
    summary: 'Aligns evidence-first hierarchy, progressive disclosure, mobile navigation, developer sequencing and compact service-page footers.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.18',
    endRelease: '3.9.0-beta.18',
    benefit: 'Reviewers reach available evidence and actionable collection controls with fewer nonfunctional controls competing for attention.',
    kpi: 'Workflow contract · register-first order, conditional controls and reciprocal mobile navigation available',
    kri: 'Residual KRI · populated collection behavior depends on available public records and was not visually exercised in the empty local dataset',
    evidence: 'Responsive browser inspection, independent design evaluation, DOM-order checks, focus treatment, targeted regression tests and production build.',
    limitation: 'The release changes presentation and navigation; it does not establish measured usability gains, accessibility certification or production adoption.',
  },
  {
    id: 'collaboration-handoff-manifest',
    title: 'Collaboration Handoff Manifest',
    summary: 'Exports deterministic, vendor-neutral human-review work items from exact public Evidence Collections.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.19',
    endRelease: '3.9.0-beta.19',
    benefit: 'A reviewer can transfer evidence links, digests, questions and acceptance criteria into an authorized receiving workflow without copying private browser state.',
    kpi: 'Handoff contract · deterministic manifest and public JSON Schema available',
    kri: 'Residual KRI · receiving-system identity, authorization, assignment and delivery state remain outside the public export',
    evidence: 'Strict collection parser, stable handoff and work-item identifiers, published schema, dedicated media type, bounded UI action and regression tests.',
    limitation: 'The manifest does not create Jira, Confluence, Teams, GRC or other vendor records and does not provide assignees, due dates, access control or delivery confirmation.',
  },
  {
    id: 'public-change-event-feed',
    title: 'Public Change Event Feed',
    summary: 'Exposes already-published policy change events through a bounded forward-polling contract.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.19',
    endRelease: '3.9.0-beta.19',
    benefit: 'Authorized consumers can poll a stable public envelope and route exact evidence links without automating portal HTML.',
    kpi: 'Polling contract · deterministic event IDs, strict cursor and localized bounded pages available',
    kri: 'Residual KRI · polling position is not delivery confirmation and consumers remain responsible for cursor storage and deduplication',
    evidence: 'Publication-time migration, public-evidence query gate, strict cursor codec, schema, CORS and rate controls, API tests and production build.',
    limitation: 'The feed provides no subscription management, recipients, push delivery, HMAC signatures, retries, replay protection or delivery receipts.',
  },
  {
    id: 'webhook-verification-readiness',
    title: 'Webhook Verification Readiness',
    summary: 'Publishes a versioned candidate HMAC-SHA256 receiver contract, deterministic compatibility vector and browser-local verification workbench.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.20',
    endRelease: '3.9.0-beta.20',
    benefit: 'Integration developers can test exact signature construction and failure behavior before PolicyWatcher offers outbound delivery.',
    kpi: 'Receiver-readiness contract: Versioned kit, local verifier, public schema and two runtime examples available',
    kri: 'Residual KRI: Compatibility with the static vector does not establish endpoint identity, production freshness, replay protection or delivery reliability',
    evidence: 'Strict signature parser, timestamp-tolerance helper, constant-time server comparison, public test vector, browser Web Crypto workbench, JSON Schema and automated tests.',
    limitation: 'The kit provides no endpoint registration, subscription state, production secret, push delivery, retry, replay storage, key rotation, receipt or service-level commitment.',
  },
  {
    id: 'shareable-evidence-views',
    title: 'Shareable dashboard evidence views',
    summary: 'Encodes the public dashboard view in a versioned canonical URL and restores committed filter context through browser history.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.2',
    endRelease: '3.9.0-beta.2',
    benefit: 'A reviewer can copy a reproducible public evidence view without rebuilding its visible filters manually.',
    kpi: 'Shareable evidence-view state: Unlocked',
    kri: 'Stale-link interpretation and context comprehension: Public state only; requires continued validation',
    evidence: 'Versioned dashboard URL codec, Copy view action, typed filter history policy, popstate restoration, fail-closed parsing and deterministic regression tests.',
    limitation: 'The URL contains public view state only. It excludes private evidence, identity, consent state and any guarantee that future source availability will match the original view.',
  },
  {
    id: 'coordinated-evidence-drilldown',
    title: 'Coordinated regional and KPI drill-down',
    summary: 'Commits region and audience context atomically from the heatmap and exposes an exact KPI inspector from the benchmark radar.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.2',
    endRelease: '3.9.0-beta.2',
    benefit: 'Readers can move from a visual signal to the precise regional context or KPI values and limitations behind it.',
    kpi: 'Coordinated visual evidence inspection: Heatmap context and KPI detail unlocked',
    kri: 'Real-user and assistive-technology comprehension: Requires validation; normalized values are not compliance or performance measures',
    evidence: 'Typed atomic region/audience action, one canonical history entry, keyboard-operable heatmap cells, KPI radar inspector, original and normalized values, missing/tie states and exact-value tables.',
    limitation: 'Drill-down improves traceability within available public evidence; it does not fill missing assessments, measure business performance or establish legal compliance.',
  },
  {
    id: 'mobile-email-intake',
    title: 'Local MIME email intake',
    summary: 'Decodes bounded .eml messages in browser memory and returns only locally reviewed policy clues.',
    domainId: 'intake',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.12',
    endRelease: '3.9.0-beta.12',
    benefit: 'A saved email can enter the existing notification-to-evidence workflow without mailbox access or server-side MIME transport.',
    kpi: 'Local email file intake: Plain-text and HTML MIME alternatives available',
    kri: 'Client and format compatibility: Limited to bounded .eml files and supported MIME structures',
    evidence: 'Dependency-free local MIME parser, transfer and header decoding, attachment exclusion, HTML text fallback, visible import state and focused tests.',
    limitation: 'The feature does not monitor a mailbox, receive forwarded mail, open attachments or recover unsupported and oversized messages.',
  },
  {
    id: 'mail-addins',
    title: 'Gmail and Outlook add-ins',
    summary: 'Evaluates dedicated in-app actions after privacy and security review of mobile intake.',
    domainId: 'distribution',
    status: 'planned',
    horizon: 'later',
    startRelease: 'later',
    endRelease: 'later',
    benefit: 'Lower-friction access inside common mail applications.',
    kpi: 'Mail application reach: External dependency',
    kri: 'Provider permissions and review: External dependency',
    evidence: 'Planned only after the inbound transport has passed privacy and security review.',
    limitation: 'Provider permission models and marketplace review are outside direct product control.',
    externalDependency: 'Google and Microsoft marketplace approval',
  },
  {
    id: 'public-integration-directory',
    title: 'Public integration directory',
    summary: 'Publishes a small read-only v1 contract for the curated Observatory registry and its public evidence boundaries.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.11',
    endRelease: '3.9.0-beta.11',
    benefit: 'Builders can inspect stable endpoints, source-gate semantics, cache policy and supported localization without requesting administrative access.',
    kpi: 'Public integration contract: Manifest and Observatory registry endpoints available',
    kri: 'Integration scope: Read-only metadata only; no policy text, administrative data or write actions',
    evidence: 'Versioned v1 routes, localized Observatory payload, published developer directory, source registry entry, navigation links and regression coverage.',
    limitation: 'The API does not ingest external feeds, provide webhooks, expose raw evidence or replace direct source review.',
  },
  {
    id: 'historical-suspensions',
    title: 'Historical suspended snapshots',
    summary: 'Makes safely qualified historical suspension states visible without reopening unverified evidence.',
    domainId: 'assurance',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.10',
    endRelease: '3.9.0-beta.10',
    benefit: 'Researchers can distinguish recorded policy changes from retrieval interruptions and verified recoveries.',
    kpi: 'Historical source-state visibility: Sanitized transition ledger available',
    kri: 'Continuity-state misinterpretation: Operational states require the displayed evidence boundary',
    evidence: 'Bounded public continuity API, standardized transition builder, source-state filters, current-transition markers and focused regression tests.',
    limitation: 'The ledger exposes operational retrieval states only; it withholds policy text, raw failure reasons, private evidence and administrative records.',
  },
  {
    id: 'database-hardening',
    title: 'Production database hardening',
    summary: 'Moves beyond single-file production storage with scaling, recovery and access controls.',
    domainId: 'operations',
    status: 'planned',
    horizon: 'later',
    startRelease: 'later',
    endRelease: 'later',
    benefit: 'The planned database design addresses production concurrency, recovery and access control.',
    kpi: 'Database scaling path: Planned',
    kri: 'Migration and operations complexity: Pending design',
    evidence: 'Planned PostgreSQL evaluation, migration rehearsal, backup validation and access review.',
    limitation: 'Current Hostinger production uses access-controlled SQLite.',
  },
  {
    id: 'residency-assurance',
    title: 'Data residency evidence and DPA',
    summary: 'Publishes a dated machine-readable register for hosting, storage, backups, subprocessors and transfer evidence.',
    domainId: 'legal',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.31',
    endRelease: '3.9.0-beta.31',
    benefit: 'Reviewers can distinguish public provider documents, operator declarations, deployment-dependent facts and open evidence instead of inferring certainty.',
    kpi: 'Residency evidence contract available: six processing/storage records, four dated references, explicit closure actions and SHA-256 digest',
    kri: 'Residual KRI: live hosting and backup regions remain unverified until deployment control-plane evidence is attached',
    evidence: 'Public residency page, JSON evidence pack, dated Hostinger and Google reference register, per-record status and deterministic digest.',
    limitation: 'The pack is not a DPA, transfer impact assessment, legal opinion or proof of the active deployment and backup regions.',
    externalDependency: 'Current provider documents and deployment control-plane evidence',
  },
  {
    id: 'production-validation',
    title: 'Production verification and independent-test boundary',
    summary: 'Runs authenticated post-deploy checks and keeps independent dynamic testing as separately attributable external evidence.',
    domainId: 'security',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.32',
    endRelease: '3.9.0-beta.32',
    benefit: 'Administrators and auditors can inspect one sanitized report for deployed release identity, database readiness, HTTP controls and unauthenticated rejection paths.',
    kpi: 'Post-deploy verification contract available: authenticated report with explicit passed, attention, unavailable and external states',
    kri: 'Residual KRI: a passing application snapshot is not an independent attack-path assessment or continuous posture result',
    evidence: 'Protected Production Verification console and endpoint, safe origin resolution, live header check, public manifest comparison, database readiness and negative authorization requests.',
    limitation: 'The report is not a penetration-test result, service-level statement, security certification or guarantee of continuous availability.',
    externalDependency: 'Independent pentest capacity',
  },
  {
    id: 'renderer-hardening',
    title: 'Renderer production hardening',
    summary: 'Adds fail-closed egress, secret rotation, authenticated readiness and bounded rendering controls to the VPS renderer.',
    domainId: 'retrieval',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.33',
    endRelease: '3.9.0-beta.33',
    benefit: 'Operators can constrain rendered targets, rotate bearer credentials without an abrupt cutover and distinguish public liveness from authenticated browser readiness.',
    kpi: 'Renderer 1.1 controls available: required target allowlist, HTTPS-only targets, rotation overlap, authenticated readiness, total timeout and HTML cap',
    kri: 'Residual KRI: Chromium owns network sockets and production egress, secret custody and live fixtures still require deployment validation',
    evidence: 'Renderer configuration gate, target and cross-site subresource allowlists, constant-time multi-secret authentication, readyz, bounded output, redacted logs, graceful draining and focused tests.',
    limitation: 'Renderer readiness does not certify retrieved source authenticity, continuous service availability or strong DNS pinning inside Chromium.',
  },
  {
    id: 'source-remediation-workbench-ux',
    title: 'Source Remediation Workbench UX',
    summary: 'Turns the returned remediation window into an action-oriented evidence ledger with deterministic priority, filters and role-safe closure semantics.',
    domainId: 'operations',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.34',
    endRelease: '3.9.0-beta.34',
    benefit: 'Operators and auditors can move from an actionable failure to bounded source evidence, workflow state and the next responsible action on desktop or mobile.',
    kpi: 'Workbench controls available: returned-window status summary, deterministic next action, safe search and filters, evidence rail, desktop ledger and mobile cards',
    kri: 'Residual KRI: a resolved issue records workflow closure only and does not prove continuous source recovery or measured usability improvement',
    evidence: 'Protected remediation workbench, derived API fields, safe HTTPS references, strict transition API and focused helper, UI and route tests.',
    limitation: 'Only Recovered issues can be closed; the workbench describes the returned issue window and does not establish source health or user-task improvement.',
  },
  {
    id: 'community-signal-composer',
    title: 'Community Signal Composer UX',
    summary: 'Structures browser-local roadmap interest into a reviewed Need, Evidence, Limits and Review dossier before a user explicitly hands it to GitHub.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.35',
    endRelease: '3.9.0-beta.35',
    benefit: 'Researchers, citizens, GRC reviewers and builders can turn a candidate need into a bounded proposal without sending draft contents to PolicyWatcher.',
    kpi: 'Composer controls available: candidate filters, four review stages, strict versioned local draft, validation, deterministic GitHub body and copy fallback',
    kri: 'Residual KRI: GitHub availability, repository permissions, review, adoption and acceptance remain external and unmeasured',
    evidence: 'Accessible roadmap composer, browser-local draft parser, bounded field counters, deterministic proposal generator and focused helper and UI tests.',
    limitation: 'The composer does not submit automatically, collect telemetry from draft contents, or establish popularity, endorsement or implementation commitment.',
    externalDependency: 'GitHub availability and repository permissions',
  },
  {
    id: 'admin-mutation-hardening',
    title: 'Administrative Mutation Hardening',
    summary: 'Centralizes provenance, media-type, declared-body, response-header and process-local rate controls for unsafe administrative API requests.',
    domainId: 'security',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.36',
    endRelease: '3.9.0-beta.36',
    benefit: 'Administrative mutations receive one consistent fail-closed request boundary while public APIs and page CSP and framing behavior remain unchanged.',
    kpi: 'Mutation boundary controls available: same-origin provenance, route-specific body caps, JSON enforcement, bounded in-memory rate limit and no-store response metadata',
    kri: 'Residual KRI: rate state is not distributed and deployment proxy behavior and independent attack resistance remain externally validated concerns',
    evidence: 'Central request-boundary helper, proxy integration, bounded safe logging and focused same-origin, denial, cap, header, rate and CSP regression tests.',
    limitation: 'Defense in depth is not a penetration test, CSRF certification, distributed rate limit or proof of reverse-proxy behavior.',
  },
  {
    id: 'categorized-resource-navigation',
    title: 'Categorized Resource Navigation',
    summary: 'Organizes the complete public resource directory into Explore, Product, Build and Media groups with responsive native disclosures.',
    domainId: 'experience',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.37',
    endRelease: '3.9.0-beta.37',
    benefit: 'Readers can scan a shorter set of named categories while retaining direct access to every existing resource destination.',
    kpi: 'Navigation controls available: four semantic resource groups, bilingual labels, mobile disclosures, visible focus and 44px targets',
    kri: 'Residual KRI: grouping quality is implementation-reviewed and has not yet been validated through a measured public navigation study',
    evidence: 'Shared full and compact footer variants, responsive styles, destination-preservation tests and visual evaluation.',
    limitation: 'The grouping changes information architecture and presentation only; it does not establish findability improvement or external adoption.',
  },
  {
    id: 'retrieval-deduplication-diagnostics',
    title: 'Retrieval Deduplication Diagnostics',
    summary: 'Makes shared acquisitions distinguishable through safe fingerprints, explicit cache modes and semantically normalized retrieval keys.',
    domainId: 'retrieval',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.37',
    endRelease: '3.9.0-beta.37',
    benefit: 'Operators can tell whether a policy used a network acquisition or a shared result and can distinguish legitimate regional source differences.',
    kpi: 'Diagnostics available: safe acquisition fingerprint, network or deduplicated mode, query-free log label and renderer browser-major/UA mode',
    kri: 'Residual KRI: equivalent sources with genuinely different semantic URLs remain separate and source-side blocking can still prevent retrieval',
    evidence: 'Acquisition-key normalization, protected progress metadata, bounded logging, renderer 1.2 readiness diagnostics and focused tests.',
    limitation: 'No stealth or WAF-bypass behavior is added; diagnostics do not prove source availability, identity or continuous deduplication savings.',
  },
  {
    id: 'github-press-kit-distribution',
    title: 'Git-hosted Press Kit Distribution',
    summary: 'Serves full checksum-listed editorial packages from the public GitHub repository while keeping the Hostinger application artifact focused on runtime files.',
    domainId: 'distribution',
    status: 'delivered',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.38',
    endRelease: '3.9.0-beta.38',
    benefit: 'Editors retain direct English and Italian package downloads while deployment operators avoid shipping nested release archives with every application build.',
    kpi: 'Distribution controls available: absolute GitHub URLs, provider metadata, SHA-256 values and a Hostinger nested-package rejection gate',
    kri: 'Residual KRI: GitHub availability and the selected repository revision are external dependencies for full-package downloads',
    evidence: 'Versioned package manifest and schema, external-download UI, committed EN/IT packages, release packaging exclusion and archive verification.',
    limitation: 'The checksum establishes downloaded-byte integrity only; individual web assets remain in the application and full package availability is not guaranteed.',
    externalDependency: 'GitHub repository availability and publication of the pinned source revision',
  },
  {
    id: 'managed-vps-releases',
    title: 'Managed VPS Renderer Releases',
    summary: 'Uploads, verifies, deploys and observes bounded Renderer packages from the protected Admin Center without exposing Agent secrets or shell access.',
    domainId: 'operations',
    status: 'current',
    horizon: 'delivered',
    startRelease: '3.9.0-beta.39',
    endRelease: '3.9.0-beta.39',
    benefit: 'Administrators can complete routine Renderer updates through one authenticated workflow with automatic smoke verification and rollback.',
    kpi: 'Managed controls available: browser SHA-256, 5 MiB upload cap, HMAC forwarding, asynchronous state, backup, smoke test and rollback',
    kri: 'Residual KRI: the Operations Agent 0.2 bootstrap and its narrowly scoped service permissions still require one VPS-level deployment',
    evidence: 'Protected upload UI, bounded Hostinger API envelope, signed Agent staging endpoint, archive and metadata validation, asynchronous operation status and focused tests.',
    limitation: 'The workflow manages Renderer releases only; it does not provide arbitrary file transfer, shell access or self-update of the Operations Agent.',
  },
  {
    id: 'beta-evidence-cycle',
    title: 'Real-user beta evidence cycle',
    summary: 'Collects structured usability, retrieval and operator evidence before stable promotion.',
    domainId: 'experience',
    status: 'planned',
    horizon: 'next',
    startRelease: 'next',
    endRelease: 'later',
    benefit: 'Stable promotion follows explicit evidence instead of version age.',
    kpi: 'Stable-promotion gate: Pending validation',
    kri: 'User-pilot evidence: Open',
    evidence: 'Planned scenario-based pilot, issue triage and documented release acceptance gate.',
    limitation: 'No adoption or comprehension improvement is claimed before the pilot.',
  },
];

export function getReleaseColumnIndex(releaseId: string) {
  return RELEASE_COLUMNS.findIndex((release) => release.id === releaseId);
}

export function getReleaseItems(releaseId: string) {
  const releaseIndex = getReleaseColumnIndex(releaseId);
  return RELEASE_IMPACT_ITEMS.filter((item) => {
    const start = getReleaseColumnIndex(item.startRelease);
    const end = getReleaseColumnIndex(item.endRelease);
    return releaseIndex >= start && releaseIndex <= end;
  });
}
