-- PolicyWatcher 4 vs 3.x report snapshot, reviewed 2026-08-20.
-- This self-contained SQLite-compatible query indexes every displayed dataset
-- against the repository evidence used for the report. It reads no production
-- data and intentionally contains only bounded release metadata.
WITH report_snapshot(dataset, item, numeric_value, state, evidence_path) AS (
  VALUES
    ('headline_metrics', 'canonical_models', 5, 'verified', 'docs/document-evidence-model.md'),
    ('headline_metrics', 'taxonomy_domains', 6, 'verified', 'docs/document-evidence-model.md'),
    ('headline_metrics', 'tests', 999, 'verified', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('headline_metrics', 'production_writes', 0, 'verified', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('rehearsal_counts', 'Entity', 17, 'reconciled', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('rehearsal_counts', 'Document', 50, 'reconciled', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('rehearsal_counts', 'Version', 91, 'reconciled', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('rehearsal_counts', 'Change', 91, 'reconciled', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('rehearsal_counts', 'Provision', 240, 'reconciled', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('feature_inventory', 'canonical_graph', NULL, 'delivered-gated', 'docs/document-evidence-model.md'),
    ('feature_inventory', 'stable_public_ids', NULL, 'delivered-gated', 'src/lib/publicEvidenceIds.ts'),
    ('feature_inventory', 'provision_taxonomy', NULL, 'delivered-gated', 'src/lib/provisionTaxonomy.ts'),
    ('feature_inventory', 'publication_readiness', NULL, 'operational', 'src/lib/publicationReadinessServer.ts'),
    ('feature_inventory', 'competitive_analysis', NULL, 'operational-protected', 'src/lib/competitiveAnalysis.ts'),
    ('feature_inventory', 'postgresql_portability', NULL, 'ci-rehearsal', 'docs/postgresql-readiness.md'),
    ('feature_inventory', 'content_ref', NULL, 'boundary-only', 'docs/document-evidence-model.md'),
    ('feature_inventory', 'historical_backfill', NULL, 'delivered-rehearsed', 'scripts/backfill-document-evidence.ts'),
    ('feature_inventory', 'deterministic_reconciliation', NULL, 'delivered-rehearsed', 'scripts/reconcile-document-evidence.ts'),
    ('feature_inventory', 'transactional_dual_write', NULL, 'delivered-off', 'src/lib/documentEvidenceSync.ts'),
    ('feature_inventory', 'activation_gate', NULL, 'delivered', 'scripts/gate-document-evidence-activation.ts'),
    ('version_comparison', 'central_unit', NULL, 'changed', 'CHANGELOG.md'),
    ('version_comparison', 'identity', NULL, 'changed', 'docs/document-evidence-model.md'),
    ('version_comparison', 'granularity', NULL, 'changed', 'docs/document-evidence-model.md'),
    ('version_comparison', 'taxonomy', NULL, 'changed', 'src/lib/provisionTaxonomy.ts'),
    ('version_comparison', 'publication_readiness', NULL, 'strengthened', 'docs/public-api-v1.md'),
    ('version_comparison', 'competitive_analysis', NULL, 'introduced', 'src/lib/competitiveAnalysis.ts'),
    ('version_comparison', 'database', NULL, 'portable-gated', 'docs/postgresql-readiness.md'),
    ('version_comparison', 'data_migration', NULL, 'introduced', 'docs/document-evidence-backfill-runbook.md'),
    ('version_comparison', 'document_storage', NULL, 'prepared', 'docs/document-evidence-model.md'),
    ('version_comparison', 'read_path', NULL, 'unchanged', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('version_comparison', 'commercial_tenancy', NULL, 'pending', 'docs/postgresql-readiness.md'),
    ('version_comparison', 'release_safety', NULL, 'strengthened', 'docs/audit-v4.0.0-beta.1.md'),
    ('stakeholder_impacts', 'product', NULL, 'expected-impact', 'docs/document-evidence-model.md'),
    ('stakeholder_impacts', 'public_users', NULL, 'controlled-impact', 'docs/public-api-v1.md'),
    ('stakeholder_impacts', 'administration', NULL, 'operational-impact', 'src/lib/competitiveAnalysisServer.ts'),
    ('stakeholder_impacts', 'engineering', NULL, 'migration-cost', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('stakeholder_impacts', 'operations', NULL, 'migration-cost', 'docs/document-evidence-backfill-runbook.md'),
    ('stakeholder_impacts', 'data_governance', NULL, 'controlled-impact', 'docs/document-evidence-model.md'),
    ('stakeholder_impacts', 'commercial_enterprise', NULL, 'future-impact', 'docs/postgresql-readiness.md'),
    ('continuity', 'source_integrity', NULL, 'preserved-strengthened', 'CHANGELOG.md'),
    ('continuity', 'change_detection', NULL, 'preserved', 'docs/document-evidence-model.md'),
    ('continuity', 'publication_governance', NULL, 'preserved-strengthened', 'docs/public-api-v1.md'),
    ('continuity', 'ai_evalops', NULL, 'preserved', 'CHANGELOG.md'),
    ('continuity', 'api_and_webhooks', NULL, 'preserved', 'docs/public-api-v1.md'),
    ('continuity', 'civic_and_adaptive_ux', NULL, 'preserved', 'CHANGELOG.md'),
    ('continuity', 'admin_release_gates', NULL, 'preserved-strengthened', 'docs/audit-v4.0.0-beta.1.md'),
    ('activation_status', 'canonical_schema', NULL, 'delivered', 'docs/audit-v4.0.0-beta.1.md'),
    ('activation_status', 'historical_backfill', NULL, 'production-pending', 'docs/document-evidence-backfill-runbook.md'),
    ('activation_status', 'reconciliation', NULL, 'production-pending', 'docs/document-evidence-backfill-runbook.md'),
    ('activation_status', 'dual_write', NULL, 'off-by-default', 'docs/document-evidence-backfill-runbook.md'),
    ('activation_status', 'canonical_reads', NULL, 'pending', 'docs/audit-v4.0.0-beta.1-wave-1b.md'),
    ('activation_status', 'object_storage', NULL, 'pending', 'docs/document-evidence-model.md'),
    ('activation_status', 'postgresql_cutover', NULL, 'pending', 'docs/postgresql-readiness.md'),
    ('activation_status', 'commercial_tenancy', NULL, 'out-of-scope', 'docs/postgresql-readiness.md')
)
SELECT dataset, item, numeric_value, state, evidence_path
FROM report_snapshot
ORDER BY dataset, item;
