/**
 * PolicyWatcher v2.0 - Shared Type Definitions
 *
 * @module types
 *
 * Central type registry used across the entire application: API responses,
 * component props, Prisma model shapes, and chart data structures.
 * All domain interfaces for the application.
 */

/**
 * Represents the regulatory impact assessment for a specific
 * region (EU / US / Global) and audience perspective (Individual / Enterprise).
 * Generated by the Gemini AI analysis for each detected policy change.
 */
export interface RegionImpact {
  id: string;
  region: 'EU' | 'US' | 'Global';
  perspective: 'Individual' | 'Enterprise';
  impactAnalysisEn: string;
  impactAnalysisIt: string;
  riskLevel: 'Low' | 'Medium' | 'High';
  complianceNoteEn?: string;
  complianceNoteIt?: string;
}

/**
 * A single, short reason explaining WHY the risk score is what it is.
 * Displayed as colored badges on the dashboard company cards.
 */
export interface RiskReason {
  icon: 'warning' | 'alert' | 'info';
  textEn: string;
  textIt: string;
  deltaScore: number;
}

/**
 * A structured key takeaway: one short bullet, sentiment-tagged.
 * Rendered in the PolicyDetails slide-over and the Executive PDF Report.
 */
export interface KeyPoint {
  textEn: string;
  textIt: string;
  sentiment: 'positive' | 'neutral' | 'negative';
}

/**
 * A recorded change between two snapshots of a policy document.
 *
 * Contains both the raw diff and AI-generated analysis (bilingual summaries,
 * key points, risk reasons, KPI indicators, and per-region impacts).
 */
export interface PolicyChange {
  id: string;
  policyId: string;
  oldSnapshotId: string | null;
  newSnapshotId: string;
  diff: string;
  aiSummaryEn: string;
  aiSummaryIt: string;

  // NEW: user-friendly structured AI output (JSON-encoded in DB as
  // tldr/keyPoints/riskReasons below; legacy fields above kept for compat)
  tldrEn?: string;
  tldrIt?: string;
  keyPointsJson?: string; // JSON array of KeyPoint
  riskReasonsJson?: string; // JSON array of RiskReason

  overallRisk: 'Low' | 'Medium' | 'High';
  overallScore: number;
  remediationsJson: string;

  // AI Governance Indicators
  aiTrainingOptOut: string;
  aiDataScrapingRestricted: string;
  aiIpLicensing: string;
  aiPromptRetention: string;

  createdAt: string;
  regionImpacts: RegionImpact[];
}

/**
 * A monitored policy document belonging to a company.
 *
 * Tracks the current text/hash and links to an ordered list of changes
 * (most recent first) detected by the cron or on-demand scrape.
 */
export interface Policy {
  id: string;
  companyId: string;
  name: string;
  type: string;
  url: string;
  jurisdiction: string;
  currentText: string;
  currentHash: string;
  updatedAt: string;
  changes: PolicyChange[];
}

/**
 * A monitored company (e.g. Google, Apple, Stripe).
 *
 * Groups one or more policies and carries metadata used for filtering
 * (industry, slug) and visual rendering (logo, website favicon).
 */
export interface Company {
  id: string;
  name: string;
  slug: string;
  logo: string;
  industry: string;
  website: string;
  policies: Policy[];
}

// Utility types for component props
/** Supported UI languages. */
export type Lang = 'en' | 'it';
/** Risk severity levels assigned by AI analysis. */
export type RiskLevel = 'Low' | 'Medium' | 'High';
/** Geographic regions for impact assessment. */
export type Region = 'EU' | 'US' | 'Global';
/** Audience perspectives used to contextualise risk impact. */
export type Perspective = 'Individual' | 'Enterprise';

/**
 * A concrete remediation action suggested by the AI analysis.
 * Parsed from `PolicyChange.remediationsJson`.
 */
export interface Remediation {
  titleEn: string;
  titleIt: string;
  descriptionEn: string;
  descriptionIt: string;
  actionUrl?: string;
  actionTextEn?: string;
  actionTextIt?: string;
}

/** A single data point on the per-policy risk score trend line chart. */
export interface RiskTrendPoint {
  version: number;
  score: number;
  date: string;
}

/**
 * A single bar in the risk profile bar chart (KPI breakdown).
 * Labels are provided in both English and Italian.
 */
export interface RiskProfileBar {
  label: string;
  labelIt: string;
  value: number;
}

/** An email subscriber who receives policy-change alerts/digests. */
export interface Subscriber {
  id: string;
  email: string;
  name?: string;
  regions: string; // JSON array
  industries: string; // JSON array
  active: boolean;
  createdAt: string;
}
