/**
 * @file CrossCompanyMatrix.tsx
 *
 * Full-screen overlay that renders a cross-company KPI comparison matrix.
 *
 * The matrix displays 15 governance KPIs (grouped into Privacy, AI Governance,
 * and Ethics) for every tracked company, colour-coded green / yellow / red.
 *
 * Features:
 *  - Industry tab filter and free-text company search.
 *  - Toggleable KPI groups (show/hide Privacy, AI Gov, Ethics columns).
 *  - Click-to-sort on any KPI column (ascending green→red, descending, clear).
 *  - Per-cell tooltip with justification text and screening date.
 *  - Bottom "Convergence" row showing cross-company alignment per KPI.
 *  - Collapsible BETA disclaimer.
 *
 * Data is fetched from `/api/matrix` on open.
 * Supports EN/IT localisation.
 */
'use client';

import { useState, useEffect, useMemo, useCallback } from 'react';
import {
  X, Grid3X3, Shield, Brain, Scale,
  Search, Filter, SortAsc, SortDesc, Building2, Calendar, AlertTriangle,
  ChevronDown, ChevronUp
} from 'lucide-react';
import Image from 'next/image';
import styles from './CrossCompanyMatrix.module.css';
import { getJustification, SCREENING_DATE } from '@/lib/kpi-justifications';

/* =============================================
   Types
   ============================================= */

/** Props for the {@link CrossCompanyMatrix} component. */
interface CrossCompanyMatrixProps {
  /** Whether the matrix overlay is currently shown. */
  isOpen: boolean;
  /** Dismiss callback (backdrop click, Escape, or close button). */
  onClose: () => void;
  /** Active UI language. */
  lang: 'en' | 'it';
}

/** Shape of a single company row returned by `/api/matrix`. */
interface CompanyMatrixData {
  id: string;
  name: string;
  slug: string;
  website: string;
  industry: string;
  /** Map of KPI key → assessed value string (e.g. `kpiDataCollection: "Extensive"`). */
  kpis: Record<string, string>;
}

/** Wrapper for the `/api/matrix` JSON response. */
interface MatrixResponse {
  companies: CompanyMatrixData[];
}

/**
 * Configuration for a single KPI column.
 * Contains both the machine key and localised display strings.
 */
interface KPIConfig {
  /** Machine-readable key matching the API response field. */
  key: string;
  nameEn: string;
  nameIt: string;
  descEn: string;
  descIt: string;
  /** Which visual group this KPI belongs to. */
  group: 'privacy' | 'aiGov' | 'ethics';
}

/** Tri-state sort direction: ascending, descending, or unsorted. */
type SortDir = 'asc' | 'desc' | null;

/* =============================================
   KPI definitions with descriptions
   ============================================= */

const kpisList: KPIConfig[] = [
  // Privacy
  {
    key: 'kpiDataCollection',
    nameEn: 'Data Collection Scope',
    nameIt: 'Ambito Raccolta Dati',
    descEn: 'Measures how much personal data is collected: minimal, moderate, or extensive.',
    descIt: 'Misura quanti dati personali vengono raccolti: minimi, moderati o estesi.',
    group: 'privacy',
  },
  {
    key: 'kpiThirdPartySharing',
    nameEn: 'Third-Party Sharing',
    nameIt: 'Condivisione Terze Parti',
    descEn: 'Whether user data is shared with third parties and under what restrictions.',
    descIt: 'Se i dati utente vengono condivisi con terze parti e con quali restrizioni.',
    group: 'privacy',
  },
  {
    key: 'kpiDataRetention',
    nameEn: 'Data Retention',
    nameIt: 'Conservazione Dati',
    descEn: 'How long personal data is stored after collection.',
    descIt: 'Per quanto tempo i dati personali vengono conservati dopo la raccolta.',
    group: 'privacy',
  },
  {
    key: 'kpiRightToDeletion',
    nameEn: 'Right to Deletion',
    nameIt: 'Diritto alla Cancellazione',
    descEn: 'Whether users can request full deletion of their data.',
    descIt: 'Se gli utenti possono richiedere la cancellazione completa dei loro dati.',
    group: 'privacy',
  },
  {
    key: 'kpiCrossBorderTransfer',
    nameEn: 'Cross-Border Transfer',
    nameIt: 'Trasferimento Transfrontaliero',
    descEn: 'Policy on transferring data across international borders.',
    descIt: 'Policy sul trasferimento dei dati oltre i confini nazionali.',
    group: 'privacy',
  },
  // AI Governance
  {
    key: 'kpiAiTrainingOptOut',
    nameEn: 'AI Training Opt-Out',
    nameIt: 'Opt-Out Addestramento AI',
    descEn: 'Whether users can opt out of their data being used for AI training.',
    descIt: 'Se gli utenti possono rifiutare che i loro dati siano usati per addestrare AI.',
    group: 'aiGov',
  },
  {
    key: 'kpiAiOutputOwnership',
    nameEn: 'AI Output Ownership',
    nameIt: 'Proprietà Output AI',
    descEn: 'Who retains ownership of content generated by AI systems.',
    descIt: 'Chi detiene la proprietà dei contenuti generati dai sistemi AI.',
    group: 'aiGov',
  },
  {
    key: 'kpiAlgoTransparency',
    nameEn: 'Algorithmic Transparency',
    nameIt: 'Trasparenza Algoritmica',
    descEn: 'Level of transparency around how algorithms make decisions.',
    descIt: 'Livello di trasparenza su come gli algoritmi prendono decisioni.',
    group: 'aiGov',
  },
  {
    key: 'kpiAutomatedDecision',
    nameEn: 'Automated Decisions',
    nameIt: 'Decisioni Automatizzate',
    descEn: 'Disclosure of automated decision-making processes affecting users.',
    descIt: 'Comunicazione dei processi decisionali automatizzati che impattano gli utenti.',
    group: 'aiGov',
  },
  {
    key: 'kpiAiBiasFairness',
    nameEn: 'AI Bias & Fairness',
    nameIt: 'Bias e Equità AI',
    descEn: 'Commitments to fairness, bias auditing, and equitable AI.',
    descIt: 'Impegno per equità, audit dei bias e AI imparziale.',
    group: 'aiGov',
  },
  // Ethics
  {
    key: 'kpiConsentMechanism',
    nameEn: 'Consent Mechanism',
    nameIt: 'Meccanismo di Consenso',
    descEn: 'How user consent is obtained: explicit opt-in, opt-out, or implicit.',
    descIt: 'Come viene ottenuto il consenso: opt-in esplicito, opt-out o implicito.',
    group: 'ethics',
  },
  {
    key: 'kpiRegulatoryCompliance',
    nameEn: 'Regulatory Compliance',
    nameIt: 'Conformità Normativa',
    descEn: 'Level of compliance with regulations like GDPR, AI Act, etc.',
    descIt: 'Livello di conformità con normative come GDPR, AI Act, ecc.',
    group: 'ethics',
  },
  {
    key: 'kpiBreachNotification',
    nameEn: 'Breach Notification',
    nameIt: 'Notifica Violazione',
    descEn: 'How quickly users are notified after a data breach.',
    descIt: 'Quanto velocemente gli utenti vengono notificati dopo una violazione dati.',
    group: 'ethics',
  },
  {
    key: 'kpiIndependentAudit',
    nameEn: 'Independent Audit',
    nameIt: 'Audit Indipendente',
    descEn: 'Whether independent third-party audits are conducted.',
    descIt: 'Se vengono condotti audit indipendenti da terze parti.',
    group: 'ethics',
  },
  {
    key: 'kpiContentModeration',
    nameEn: 'Content Moderation',
    nameIt: 'Moderazione Contenuti',
    descEn: 'Transparency and effectiveness of content moderation policies.',
    descIt: 'Trasparenza ed efficacia delle politiche di moderazione dei contenuti.',
    group: 'ethics',
  },
];

/* =============================================
   Industry tabs config
   ============================================= */

const industryFilters = [
  { key: 'all', labelEn: 'All', labelIt: 'Tutti' },
  { key: 'Tech Giant', labelEn: 'Tech Giant', labelIt: 'Tech Giant' },
  { key: 'FinTech', labelEn: 'FinTech', labelIt: 'FinTech' },
  { key: 'Social Media', labelEn: 'Social Media', labelIt: 'Social Media' },
  { key: 'E-Commerce', labelEn: 'E-Commerce', labelIt: 'E-Commerce' },
  { key: 'AI Provider', labelEn: 'AI Provider', labelIt: 'AI Provider' },
  { key: 'Cloud/SaaS', labelEn: 'Cloud/SaaS', labelIt: 'Cloud/SaaS' },
];

/* =============================================
   Badge color logic
   ============================================= */

/**
 * Maps a KPI key + assessed value to a CSS module badge class.
 *
 * Special-case logic handles KPIs whose value semantics differ from
 * the global lookup tables (e.g. "Minimal" is good for Data Collection
 * but bad for Regulatory Compliance).
 *
 * @param kpiKey - KPI machine key.
 * @param value  - Assessed value string.
 * @returns CSS class name from the module stylesheet.
 */
const getBadgeClass = (kpiKey: string, value: string): string => {
  if (!value || value === 'Not assessed') return styles.badgeMuted;

  const v = value.toLowerCase();

  // Context-sensitive overrides: the same word can mean different things
  // depending on the KPI it describes.
  if (kpiKey === 'kpiDataCollection') {
    if (v === 'minimal') return styles.badgeGreen;
    if (v === 'moderate') return styles.badgeYellow;
    if (v === 'extensive') return styles.badgeRed;
  }

  if (kpiKey === 'kpiRegulatoryCompliance') {
    if (v === 'comprehensive') return styles.badgeGreen;
    if (v === 'partial') return styles.badgeYellow;
    if (v === 'minimal') return styles.badgeRed;
  }

  // Generic lookup tables for values that share consistent semantics
  // across all KPIs.
  const greenValues = [
    'none', 'available', 'full', 'restricted', 'published',
    'disclosed', 'committed', 'explicit opt-in', 'within 24h',
    'certified', 'transparent', 'user retained',
  ];

  const yellowValues = [
    'limited', 'extended', 'partial', 'controlled', 'shared',
    'opt-out', 'within 72h', 'mentioned',
  ];

  const redValues = [
    'broad', 'indefinite', 'not available', 'company claimed',
    'opaque', 'undisclosed', 'absent', 'implicit', 'unspecified',
  ];

  if (greenValues.includes(v)) return styles.badgeGreen;
  if (yellowValues.includes(v)) return styles.badgeYellow;
  if (redValues.includes(v)) return styles.badgeRed;

  return styles.badgeMuted;
};

/**
 * Returns 'green' | 'yellow' | 'red' | 'muted'
 */
const getBadgeColor = (kpiKey: string, value: string): string => {
  const cls = getBadgeClass(kpiKey, value);
  if (cls === styles.badgeGreen) return 'green';
  if (cls === styles.badgeYellow) return 'yellow';
  if (cls === styles.badgeRed) return 'red';
  return 'muted';
};

/* =============================================
   Main Component
   ============================================= */

/**
 * Full-screen cross-company KPI comparison matrix overlay.
 *
 * Fetches data from `/api/matrix`, displays a filterable / sortable table
 * of 15 KPIs, and computes per-column convergence metrics.
 *
 * @param props - {@link CrossCompanyMatrixProps}
 * @returns The matrix overlay, or `null` when `isOpen` is false.
 */
export default function CrossCompanyMatrix({ isOpen, onClose, lang }: CrossCompanyMatrixProps) {
  const [data, setData] = useState<CompanyMatrixData[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [closing, setClosing] = useState(false);

  // Filters
  const [industryFilter, setIndustryFilter] = useState('all');
  const [searchQuery, setSearchQuery] = useState('');
  const [visibleGroups, setVisibleGroups] = useState<Record<string, boolean>>({
    privacy: true,
    aiGov: true,
    ethics: true,
  });

  // Sort
  const [sortKey, setSortKey] = useState<string | null>(null);
  const [sortDir, setSortDir] = useState<SortDir>(null);

  // Tooltip
  const [hoveredKpi, setHoveredKpi] = useState<string | null>(null);

  // Collapsible BETA disclaimer (expanded by default; user can collapse
  // it after reading, and re-expand it anytime).
  const [disclaimerExpanded, setDisclaimerExpanded] = useState(true);

  /* ---- Data fetching ---- */
  const fetchMatrixData = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch('/api/matrix');
      if (res.ok) {
        const result: MatrixResponse = await res.json();
        setData(result.companies);
      } else {
        setError(
          lang === 'it'
            ? 'Impossibile recuperare i dati della matrice.'
            : 'Failed to fetch matrix data.'
        );
      }
    } catch (err) {
      console.error('Error fetching matrix:', err);
      setError(
        lang === 'it'
          ? 'Errore di rete durante il caricamento.'
          : 'Network error while loading data.'
      );
    } finally {
      setLoading(false);
    }
  }, [lang]);

  useEffect(() => {
    if (isOpen) {
      fetchMatrixData();
      setClosing(false);
      // Reset filters when opening
      setIndustryFilter('all');
      setSearchQuery('');
      setSortKey(null);
      setSortDir(null);
    }
  }, [isOpen, fetchMatrixData]);

  // Escape key
  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose();
    };
    window.addEventListener('keydown', handleEsc);
    return () => window.removeEventListener('keydown', handleEsc);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleClose = () => {
    setClosing(true);
    setTimeout(() => onClose(), 250);
  };

  /* ---- Helpers ---- */
  const getCleanDomain = (website: string) => {
    try {
      const url = new URL(website);
      const parts = url.hostname.split('.');
      return parts.slice(-2).join('.');
    } catch {
      return website
        .replace('https://', '')
        .replace('http://', '')
        .split('/')[0];
    }
  };

  /* ---- Active KPIs (based on visible groups) ---- */
  const activeKpis = useMemo(
    () => kpisList.filter((kpi) => visibleGroups[kpi.group]),
    [visibleGroups]
  );

  /* ---- Filtered + Sorted companies ---- */
  const filteredData = useMemo(() => {
    let result = [...data];

    // Industry filter
    if (industryFilter !== 'all') {
      result = result.filter((c) => c.industry === industryFilter);
    }

    // Search filter
    if (searchQuery.trim()) {
      const q = searchQuery.trim().toLowerCase();
      result = result.filter((c) => c.name.toLowerCase().includes(q));
    }

    // Sort
    if (sortKey && sortDir) {
      const kpiConfig = kpisList.find((k) => k.key === sortKey);
      if (kpiConfig) {
        result.sort((a, b) => {
          const colorA = getBadgeColor(sortKey, a.kpis[sortKey] || '');
          const colorB = getBadgeColor(sortKey, b.kpis[sortKey] || '');
          const order: Record<string, number> = { green: 1, yellow: 2, red: 3, muted: 4 };
          const diff = (order[colorA] || 4) - (order[colorB] || 4);
          return sortDir === 'asc' ? diff : -diff;
        });
      }
    }

    return result;
  }, [data, industryFilter, searchQuery, sortKey, sortDir]);

  /* ---- Score computation ---- */
  /**
   * Computes a colour-based scorecard for a company row.
   * Counts how many of the currently visible KPIs fall into each colour tier.
   */
  const computeScore = (company: CompanyMatrixData) => {
    let green = 0, yellow = 0, red = 0, muted = 0;
    activeKpis.forEach((kpi) => {
      const color = getBadgeColor(kpi.key, company.kpis[kpi.key] || '');
      if (color === 'green') green++;
      else if (color === 'yellow') yellow++;
      else if (color === 'red') red++;
      else muted++;
    });
    return { green, yellow, red, muted };
  };

  /**
   * Calculates cross-company convergence for a single KPI column.
   *
   * If ≥ 70% of the filtered companies share the same assessed value,
   * the KPI is "Aligned"; otherwise it is "Divergent".
   *
   * @returns An object with status, dominant value, and percentage.
   */
  const getConvergence = (kpiKey: string) => {
    const counts: Record<string, number> = {};
    let total = 0;

    filteredData.forEach((co) => {
      const val = co.kpis[kpiKey];
      if (val && val !== 'Not assessed') {
        counts[val] = (counts[val] || 0) + 1;
        total++;
      }
    });

    if (total === 0) return { status: 'none' as const, value: 'N/A', percentage: 0 };

    let maxVal = '';
    let maxCount = 0;
    for (const [val, count] of Object.entries(counts)) {
      if (count > maxCount) {
        maxCount = count;
        maxVal = val;
      }
    }

    const percentage = Math.round((maxCount / Math.max(1, total)) * 100);
    const isConvergent = maxCount >= Math.max(1, total * 0.7);

    return {
      status: isConvergent ? ('converge' as const) : ('diverge' as const),
      value: maxVal,
      percentage,
    };
  };

  /**
   * Three-state sort toggle: unsorted → ascending → descending → unsorted.
   * Sorting ranks cells by their colour tier (green < yellow < red < muted).
   */
  const handleSort = (key: string) => {
    if (sortKey === key) {
      if (sortDir === 'asc') setSortDir('desc');
      else if (sortDir === 'desc') {
        setSortKey(null);
        setSortDir(null);
      }
    } else {
      setSortKey(key);
      setSortDir('asc');
    }
  };

  /* ---- Toggle group ---- */
  const toggleGroup = (group: string) => {
    setVisibleGroups((prev) => ({ ...prev, [group]: !prev[group] }));
  };

  /* ---- Count visible by group ---- */
  const countByGroup = (group: string) =>
    kpisList.filter((k) => k.group === group).length;

  if (!isOpen) return null;

  /* ---- Group col spans (only for visible groups) ---- */
  const privacyKpis = activeKpis.filter((k) => k.group === 'privacy');
  const aiGovKpis = activeKpis.filter((k) => k.group === 'aiGov');
  const ethicsKpis = activeKpis.filter((k) => k.group === 'ethics');

  return (
    <div
      className={styles.overlay}
      onClick={handleClose}
      role="dialog"
      aria-modal="true"
      aria-label="KPI Matrix"
    >
      <div
        className={`${styles.panel} ${closing ? styles.panelClosing : ''}`}
        onClick={(e) => e.stopPropagation()}
      >
        {/* ---- HEADER ---- */}
        <div className={styles.header}>
          <div className={styles.titleArea}>
            <h2 className={styles.title}>
              <Grid3X3 size={24} color="var(--primary)" />
              {lang === 'it'
                ? 'Matrice di Confronto KPI Governance'
                : 'KPI Governance Comparison Matrix'}
            </h2>
            <p className={styles.subtitle}>
              {lang === 'it'
                ? 'Confronto incrociato di 15 KPI su Privacy, AI Governance ed Etica societaria.'
                : 'Cross-company comparison of 15 KPIs on Privacy, AI Governance, and Corporate Ethics.'}
              <span className={styles.dateTag}>
                <Calendar size={12} />
                {lang === 'it' ? `Screening: ${SCREENING_DATE}` : `Screening: ${SCREENING_DATE}`}
              </span>
            </p>
            <div className={`${styles.disclaimer} ${disclaimerExpanded ? '' : styles.disclaimerCollapsed}`}>
              <button
                type="button"
                className={styles.disclaimerToggle}
                onClick={() => setDisclaimerExpanded((v) => !v)}
                aria-expanded={disclaimerExpanded}
                aria-controls="disclaimer-body"
              >
                <AlertTriangle size={14} className={styles.disclaimerIcon} />
                <span className={styles.disclaimerTitle}>
                  {lang === 'it' ? 'Disclaimer Beta (clicca per espandere/comprimere)' : 'Beta Disclaimer (click to expand/collapse)'}
                </span>
                {disclaimerExpanded ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>
              {disclaimerExpanded && (
                <>
                  <span id="disclaimer-body" className={styles.disclaimerBody}>
                    {lang === 'it'
                      ? 'BETA RELEASE: Questa piattaforma e in fase di sviluppo (beta) e non rappresenta un prodotto finale. Le valutazioni riportate sono puramente indicative, generate da un\'analisi automatizzata (AI) di testi di policy pubblicamente disponibili alla data dello screening. Non costituiscono in alcun modo parere legale, certificazione di conformita, giudizio vincolante o valutazione definitiva della condotta aziendale. I valori possono contenere imprecisioni, errori interpretativi o omissioni e possono non riflettere la totalita delle pratiche aziendali, degli accordi riservati o degli aggiornamenti successivi. L\'autore e la piattaforma declinano qualsiasi responsabilita per decisioni, azioni o omissioni basate su queste informazioni. L\'interpretazione e l\'uso dei dati presentati sono esclusivamente a carico e sotto la responsabilita dell\'utente. Si raccomanda di consultare sempre le fonti ufficiali e un consulente legale qualificato.'
                      : 'BETA RELEASE: This platform is in active development (beta) and does not represent a final product. The assessments shown are purely indicative, generated by an automated (AI) analysis of publicly available policy texts as of the screening date. They do not constitute legal advice, compliance certification, binding judgment, or definitive assessment of corporate conduct in any way. Values may contain inaccuracies, interpretive errors, or omissions, and may not reflect the full scope of corporate practices, confidential agreements, or subsequent updates. The author and the platform disclaim all liability for any decisions, actions, or omissions based on this information. The interpretation and use of the data presented are solely at the user\'s own risk and responsibility. Users are strongly advised to consult official sources and qualified legal counsel.'}
                  </span>
                  <button
                    type="button"
                    className={styles.disclaimerAck}
                    onClick={() => setDisclaimerExpanded(false)}
                  >
                    {lang === 'it' ? 'Ho letto, chiudi' : 'I\'ve read it, collapse'}
                  </button>
                </>
              )}
            </div>
          </div>
          <button
            onClick={handleClose}
            className={styles.closeBtn}
            aria-label={lang === 'it' ? 'Chiudi' : 'Close'}
          >
            <X size={18} />
          </button>
        </div>

        {/* ---- FILTER BAR ---- */}
        <div className={styles.filterBar}>
          {/* Row 1: Industry tabs + Search */}
          <div className={styles.filterRow}>
            <span className={styles.filterLabel}>
              <Building2 size={13} />
              {lang === 'it' ? 'Settore' : 'Industry'}
            </span>
            <div className={styles.industryTabs}>
              {industryFilters.map((f) => (
                <button
                  key={f.key}
                  className={`${styles.industryTab} ${
                    industryFilter === f.key ? styles.industryTabActive : ''
                  }`}
                  onClick={() => setIndustryFilter(f.key)}
                >
                  {lang === 'it' ? f.labelIt : f.labelEn}
                </button>
              ))}
            </div>

            <div className={styles.searchWrapper}>
              <Search size={14} className={styles.searchIcon} />
              <input
                type="text"
                className={styles.searchInput}
                placeholder={lang === 'it' ? 'Cerca azienda...' : 'Search company...'}
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>

          {/* Row 2: KPI group toggles */}
          <div className={styles.filterRow}>
            <span className={styles.filterLabel}>
              <Filter size={13} />
              {lang === 'it' ? 'Gruppi KPI' : 'KPI Groups'}
            </span>
            <div className={styles.groupToggles}>
              <button
                className={`${styles.groupToggle} ${styles.groupTogglePrivacy} ${
                  visibleGroups.privacy
                    ? styles.groupToggleActive
                    : styles.groupToggleInactive
                }`}
                onClick={() => toggleGroup('privacy')}
              >
                <Shield size={13} />
                Privacy ({countByGroup('privacy')})
              </button>
              <button
                className={`${styles.groupToggle} ${styles.groupToggleAiGov} ${
                  visibleGroups.aiGov
                    ? styles.groupToggleActive
                    : styles.groupToggleInactive
                }`}
                onClick={() => toggleGroup('aiGov')}
              >
                <Brain size={13} />
                AI Gov ({countByGroup('aiGov')})
              </button>
              <button
                className={`${styles.groupToggle} ${styles.groupToggleEthics} ${
                  visibleGroups.ethics
                    ? styles.groupToggleActive
                    : styles.groupToggleInactive
                }`}
                onClick={() => toggleGroup('ethics')}
              >
                <Scale size={13} />
                Ethics ({countByGroup('ethics')})
              </button>
            </div>
          </div>
        </div>

        {/* ---- LOADING ---- */}
        {loading && (
          <div className={styles.loadingWrapper}>
            <div className={styles.spinner} />
            <p>
              {lang === 'it'
                ? 'Caricamento matrice di confronto...'
                : 'Loading comparison matrix...'}
            </p>
          </div>
        )}

        {/* ---- ERROR ---- */}
        {error && (
          <div className={styles.errorWrapper}>
            <p>{error}</p>
            <button onClick={fetchMatrixData} className={styles.retryBtn}>
              {lang === 'it' ? 'Riprova' : 'Retry'}
            </button>
          </div>
        )}

        {/* ---- EMPTY STATE ---- */}
        {!loading && !error && filteredData.length === 0 && (
          <div className={styles.emptyState}>
            <Building2 size={40} className={styles.emptyIcon} />
            <span>
              {lang === 'it'
                ? 'Nessuna azienda corrisponde ai filtri selezionati.'
                : 'No companies match the selected filters.'}
            </span>
          </div>
        )}

        {/* ---- TABLE ---- */}
        {!loading && !error && filteredData.length > 0 && (
          <>
            <div className={styles.matrixContainer}>
              <table className={styles.matrixTable}>
                <thead>
                  {/* Group header row */}
                  <tr className={styles.topHeader}>
                    <th className={`${styles.stickyCol} ${styles.topHeader}`}>
                      {lang === 'it' ? 'Azienda' : 'Company'}
                    </th>
                    <th className={`${styles.scoreCol} ${styles.topHeader}`}>
                      {lang === 'it' ? 'Punteggio' : 'Score'}
                    </th>
                    {privacyKpis.length > 0 && (
                      <th
                        colSpan={privacyKpis.length}
                        className={`${styles.groupHeader} ${styles.privacyGroup}`}
                      >
                        <div
                          style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            gap: '8px',
                          }}
                        >
                          <Shield size={14} />
                          {lang === 'it'
                            ? 'Privacy e Protezione Dati'
                            : 'Privacy & Data Protection'}
                        </div>
                      </th>
                    )}
                    {aiGovKpis.length > 0 && (
                      <th
                        colSpan={aiGovKpis.length}
                        className={`${styles.groupHeader} ${styles.aiGovGroup}`}
                      >
                        <div
                          style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            gap: '8px',
                          }}
                        >
                          <Brain size={14} />
                          {lang === 'it'
                            ? 'AI Governance ed Etica'
                            : 'AI Governance & Ethics'}
                        </div>
                      </th>
                    )}
                    {ethicsKpis.length > 0 && (
                      <th
                        colSpan={ethicsKpis.length}
                        className={`${styles.groupHeader} ${styles.ethicsGroup}`}
                      >
                        <div
                          style={{
                            display: 'flex',
                            alignItems: 'center',
                            justifyContent: 'center',
                            gap: '8px',
                          }}
                        >
                          <Scale size={14} />
                          {lang === 'it'
                            ? 'Etica e Governance Societaria'
                            : 'Ethics & Corporate Governance'}
                        </div>
                      </th>
                    )}
                  </tr>

                  {/* Sub-header row */}
                  <tr>
                    <th className={styles.subHeader} />
                    <th className={`${styles.subHeader} ${styles.scoreCol}`} />
                    {activeKpis.map((kpi) => (
                      <th
                        key={kpi.key}
                        className={styles.subHeader}
                        title={lang === 'it' ? kpi.nameIt : kpi.nameEn}
                        onClick={() => handleSort(kpi.key)}
                      >
                        <div className={styles.subHeaderContent}>
                          <span>{lang === 'it' ? kpi.nameIt : kpi.nameEn}</span>
                          {sortKey === kpi.key ? (
                            sortDir === 'asc' ? (
                              <SortAsc
                                size={12}
                                className={`${styles.sortIcon} ${styles.sortIconActive}`}
                              />
                            ) : (
                              <SortDesc
                                size={12}
                                className={`${styles.sortIcon} ${styles.sortIconActive}`}
                              />
                            )
                          ) : (
                            <SortAsc size={12} className={styles.sortIcon} />
                          )}
                        </div>
                      </th>
                    ))}
                  </tr>
                </thead>

                <tbody>
                  {/* Company rows */}
                  {filteredData.map((company, idx) => {
                    const score = computeScore(company);
                    return (
                      <tr
                        key={company.id}
                        className={styles.companyRow}
                        style={{ animationDelay: `${idx * 40}ms` }}
                      >
                        {/* Sticky company cell */}
                        <td className={styles.stickyCol}>
                          <div className={styles.companyCell}>
                            <div className={styles.logoWrapper}>
                              <Image
                                src={`https://logo.clearbit.com/${getCleanDomain(
                                  company.website
                                )}`}
                                alt={company.name}
                                width={28}
                                height={28}
                                unoptimized
                                onError={(e) => {
                                  (e.currentTarget as HTMLImageElement).src =
                                    'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="28" height="28" viewBox="0 0 28 28" fill="none" stroke="%2364748b" stroke-width="2"><rect width="20" height="20" x="4" y="4" rx="3"/></svg>';
                                }}
                              />
                            </div>
                            <span className={styles.companyName}>{company.name}</span>
                            <span className={styles.industryBadge}>{company.industry}</span>
                          </div>
                        </td>

                        {/* Score cell */}
                        <td className={styles.scoreCol}>
                          <div className={styles.scoreWrapper}>
                            {score.green > 0 && (
                              <>
                                <span
                                  className={`${styles.scoreDot} ${styles.scoreDotGreen}`}
                                />
                                <span
                                  className={`${styles.scoreNumber} ${styles.scoreGreen}`}
                                >
                                  {score.green}
                                </span>
                              </>
                            )}
                            {score.yellow > 0 && (
                              <>
                                <span
                                  className={`${styles.scoreDot} ${styles.scoreDotYellow}`}
                                />
                                <span
                                  className={`${styles.scoreNumber} ${styles.scoreYellow}`}
                                >
                                  {score.yellow}
                                </span>
                              </>
                            )}
                            {score.red > 0 && (
                              <>
                                <span
                                  className={`${styles.scoreDot} ${styles.scoreDotRed}`}
                                />
                                <span
                                  className={`${styles.scoreNumber} ${styles.scoreRed}`}
                                >
                                  {score.red}
                                </span>
                              </>
                            )}
                            {score.muted > 0 && (
                              <>
                                <span
                                  className={`${styles.scoreDot} ${styles.scoreDotMuted}`}
                                />
                                <span className={styles.scoreNumber}>{score.muted}</span>
                              </>
                            )}
                          </div>
                        </td>

                        {/* KPI cells */}
                        {activeKpis.map((kpi) => {
                          const val = company.kpis[kpi.key] || 'Not assessed';
                          return (
                            <td
                              key={kpi.key}
                              className={styles.cellHover}
                              onMouseEnter={() => setHoveredKpi(`${company.id}-${kpi.key}`)}
                              onMouseLeave={() => setHoveredKpi(null)}
                            >
                              <div className={styles.tooltipWrapper}>
                                <span
                                  className={`${styles.badge} ${getBadgeClass(
                                    kpi.key,
                                    val
                                  )}`}
                                >
                                  {val}
                                </span>
                                {hoveredKpi === `${company.id}-${kpi.key}` && (
                                  <div className={styles.tooltip}>
                                    <div className={styles.tooltipTitle}>
                                      {lang === 'it' ? kpi.nameIt : kpi.nameEn}
                                    </div>
                                    <span className={`${styles.tooltipValue} ${
                                      getBadgeColor(kpi.key, val) === 'green' ? styles.tooltipValueGreen :
                                      getBadgeColor(kpi.key, val) === 'yellow' ? styles.tooltipValueYellow :
                                      getBadgeColor(kpi.key, val) === 'red' ? styles.tooltipValueRed :
                                      styles.tooltipValueMuted
                                    }`}>
                                      {val}
                                    </span>
                                    <div className={styles.tooltipJustification}>
                                      {getJustification(company.slug, kpi.key, lang)}
                                    </div>
                                    <div className={styles.tooltipDate}>
                                      <Calendar size={10} />
                                      {lang === 'it'
                                        ? `Screening: ${SCREENING_DATE}`
                                        : `Screening: ${SCREENING_DATE}`}
                                    </div>
                                  </div>
                                )}
                              </div>
                            </td>
                          );
                        })}
                      </tr>
                    );
                  })}

                  {/* ---- CONVERGENCE ROW ---- */}
                  <tr className={styles.summaryRow}>
                    <td className={styles.stickyCol}>
                      {lang === 'it'
                        ? 'Consenso (Soglia 70%)'
                        : 'Consensus (70% Threshold)'}
                    </td>
                    <td className={styles.scoreCol} />
                    {activeKpis.map((kpi) => {
                      const conv = getConvergence(kpi.key);

                      if (conv.status === 'none') {
                        return (
                          <td key={kpi.key}>
                            <div className={styles.convergenceCell}>
                              <span
                                className={`${styles.convergenceLabel} ${styles.noneText}`}
                              >
                                N/A
                              </span>
                              <div className={styles.convergenceBarTrack}>
                                <div
                                  className={`${styles.convergenceBarFill} ${styles.convergenceBarMuted}`}
                                  style={{ width: '0%' }}
                                />
                              </div>
                            </div>
                          </td>
                        );
                      }

                      const isConverge = conv.status === 'converge';
                      const barColorClass = isConverge
                        ? conv.percentage >= 90
                          ? styles.convergenceBarGreen
                          : styles.convergenceBarYellow
                        : styles.convergenceBarRed;

                      return (
                        <td key={kpi.key}>
                          <div className={styles.convergenceCell}>
                            <span
                              className={`${styles.convergenceLabel} ${
                                isConverge ? styles.convergeText : styles.divergeText
                              }`}
                            >
                              <span className={styles.convergencePercent}>
                                {conv.percentage}%
                              </span>
                              {isConverge
                                ? lang === 'it'
                                  ? 'Allineato'
                                  : 'Aligned'
                                : lang === 'it'
                                ? 'Divergente'
                                : 'Divergent'}
                            </span>
                            <div className={styles.convergenceBarTrack}>
                              <div
                                className={`${styles.convergenceBarFill} ${barColorClass}`}
                                style={{ width: `${conv.percentage}%` }}
                              />
                            </div>
                          </div>
                        </td>
                      );
                    })}
                  </tr>
                </tbody>
              </table>
            </div>

            {/* ---- LEGEND ---- */}
            <div className={styles.summaryLegend}>
              <div>
                {lang === 'it'
                  ? 'Nota: I dati si riferiscono alle versioni vigenti delle policy analizzate.'
                  : 'Note: Data refers to the active versions of analyzed policies.'}
              </div>
              <div className={styles.legendItems}>
                <div className={styles.legendItem}>
                  <div
                    className={styles.legendDot}
                    style={{ background: '#059669' }}
                  />
                  <span>
                    {lang === 'it'
                      ? 'Protettivo / Conforme'
                      : 'Protective / Compliant'}
                  </span>
                </div>
                <div className={styles.legendItem}>
                  <div
                    className={styles.legendDot}
                    style={{ background: '#d97706' }}
                  />
                  <span>
                    {lang === 'it'
                      ? 'Parziale / Attenzione'
                      : 'Partial / Attention Required'}
                  </span>
                </div>
                <div className={styles.legendItem}>
                  <div
                    className={styles.legendDot}
                    style={{ background: '#dc2626' }}
                  />
                  <span>
                    {lang === 'it'
                      ? 'Invasivo / Non Dichiarato'
                      : 'Concerning / Undisclosed'}
                  </span>
                </div>
              </div>
            </div>
          </>
        )}
      </div>
    </div>
  );
}
