'use client';
import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import styles from './MethodologyModal.module.css';
import { 
  X, Shield, Brain, Scale, Eye, AlertTriangle, 
  BookOpen, Activity, ExternalLink, Layers, Gauge, Target, CheckCircle
} from 'lucide-react';
import { IconKpiSignal } from './icons/PolicyWatcherIcons';
import { POLICYWATCHER_VERSION } from '@/lib/release';

interface MethodologyModalProps {
  isOpen: boolean;
  onClose: () => void;
  lang: 'en' | 'it';
}

// KPI definitions with bilingual descriptions and possible values.

interface KPIDef {
  key: string;
  nameEn: string;
  nameIt: string;
  descEn: string;
  descIt: string;
  group: 'privacy' | 'aiGov' | 'ethics';
  values: { label: string; color: 'green' | 'yellow' | 'red' }[];
}

const kpiDefinitions: KPIDef[] = [
  // Privacy and Data Protection.
  {
    key: 'kpiDataCollection',
    nameEn: 'Data Collection Scope',
    nameIt: 'Ambito Raccolta Dati',
    descEn: 'Measures the breadth of personal data collected by the company: types, categories, and whether collection is proportional to the stated purpose.',
    descIt: 'Misura l\'ampiezza dei dati personali raccolti dall\'azienda: tipologie, categorie, e se la raccolta è proporzionale allo scopo dichiarato.',
    group: 'privacy',
    values: [
      { label: 'Minimal', color: 'green' },
      { label: 'Moderate', color: 'yellow' },
      { label: 'Extensive', color: 'red' }
    ]
  },
  {
    key: 'kpiThirdPartySharing',
    nameEn: 'Third-Party Sharing',
    nameIt: 'Condivisione Terze Parti',
    descEn: 'Evaluates the extent and transparency of data sharing with external entities including advertisers, partners, and data brokers.',
    descIt: 'Valuta l\'entità e la trasparenza della condivisione dei dati con soggetti terzi, inclusi inserzionisti, partner e data broker.',
    group: 'privacy',
    values: [
      { label: 'None / Restricted', color: 'green' },
      { label: 'Limited / Controlled', color: 'yellow' },
      { label: 'Broad / Undisclosed', color: 'red' }
    ]
  },
  {
    key: 'kpiDataRetention',
    nameEn: 'Data Retention',
    nameIt: 'Conservazione Dati',
    descEn: 'Assesses how long the company retains personal data and whether a clear retention schedule is defined.',
    descIt: 'Valuta per quanto tempo l\'azienda conserva i dati personali e se è definito un calendario di conservazione chiaro.',
    group: 'privacy',
    values: [
      { label: 'Limited (defined)', color: 'green' },
      { label: 'Extended', color: 'yellow' },
      { label: 'Indefinite', color: 'red' }
    ]
  },
  {
    key: 'kpiRightToDeletion',
    nameEn: 'Right to Deletion',
    nameIt: 'Diritto alla Cancellazione',
    descEn: 'Checks whether users can request full deletion of their data and how effectively the company honors such requests.',
    descIt: 'Verifica se gli utenti possono richiedere la cancellazione completa dei propri dati e con quale efficacia l\'azienda soddisfa tali richieste.',
    group: 'privacy',
    values: [
      { label: 'Full / Available', color: 'green' },
      { label: 'Partial', color: 'yellow' },
      { label: 'Not available', color: 'red' }
    ]
  },
  {
    key: 'kpiCrossBorderTransfer',
    nameEn: 'Cross-Border Transfer',
    nameIt: 'Trasferimento Transfrontaliero',
    descEn: 'Evaluates whether data is transferred across jurisdictions and the safeguards in place (e.g., SCCs, adequacy decisions).',
    descIt: 'Valuta se i dati vengono trasferiti tra giurisdizioni e le garanzie adottate (es. SCC, decisioni di adeguatezza).',
    group: 'privacy',
    values: [
      { label: 'Restricted', color: 'green' },
      { label: 'Controlled', color: 'yellow' },
      { label: 'Unrestricted', color: 'red' }
    ]
  },
  // AI Governance.
  {
    key: 'kpiAiTrainingOptOut',
    nameEn: 'AI Training Opt-Out',
    nameIt: 'Opt-Out Addestramento AI',
    descEn: 'Checks whether users can opt out of having their data (conversations, uploads, content) used to train the company\'s AI models.',
    descIt: 'Verifica se gli utenti possono rifiutare l\'utilizzo dei propri dati (conversazioni, upload, contenuti) per l\'addestramento dei modelli IA dell\'azienda.',
    group: 'aiGov',
    values: [
      { label: 'Available / Not used', color: 'green' },
      { label: 'Opt-out available', color: 'yellow' },
      { label: 'Not available', color: 'red' }
    ]
  },
  {
    key: 'kpiAiOutputOwnership',
    nameEn: 'AI Output Ownership',
    nameIt: 'Proprietà Output AI',
    descEn: 'Determines who owns the intellectual property of content generated by AI tools: the user, the company, or shared ownership.',
    descIt: 'Determina chi detiene la proprietà intellettuale dei contenuti generati dagli strumenti IA: l\'utente, l\'azienda o proprietà condivisa.',
    group: 'aiGov',
    values: [
      { label: 'User retained', color: 'green' },
      { label: 'Shared', color: 'yellow' },
      { label: 'Company retained', color: 'red' }
    ]
  },
  {
    key: 'kpiAlgoTransparency',
    nameEn: 'Algorithmic Transparency',
    nameIt: 'Trasparenza Algoritmica',
    descEn: 'Measures how transparent the company is about how its algorithms work, including recommendation engines and automated decision systems.',
    descIt: 'Misura la trasparenza dell\'azienda sul funzionamento dei propri algoritmi, inclusi motori di raccomandazione e sistemi decisionali automatizzati.',
    group: 'aiGov',
    values: [
      { label: 'Published / Disclosed', color: 'green' },
      { label: 'Mentioned / Partial', color: 'yellow' },
      { label: 'Opaque / Undisclosed', color: 'red' }
    ]
  },
  {
    key: 'kpiAutomatedDecision',
    nameEn: 'Automated Decisions',
    nameIt: 'Decisioni Automatizzate',
    descEn: 'Evaluates whether automated decision-making processes are disclosed and if meaningful human review mechanisms exist.',
    descIt: 'Valuta se i processi di decisione automatizzata sono dichiarati e se esistono meccanismi significativi di revisione umana.',
    group: 'aiGov',
    values: [
      { label: 'Transparent / Human-in-loop', color: 'green' },
      { label: 'Partial disclosure', color: 'yellow' },
      { label: 'Opaque / No review', color: 'red' }
    ]
  },
  {
    key: 'kpiAiBiasFairness',
    nameEn: 'AI Bias & Fairness',
    nameIt: 'Bias e Equità AI',
    descEn: 'Assesses whether the company acknowledges AI bias risks and has active mitigation strategies (e.g., fairness audits, diverse datasets).',
    descIt: 'Valuta se l\'azienda riconosce i rischi di bias nei propri sistemi IA e ha strategie attive di mitigazione (es. audit di equità, dataset diversificati).',
    group: 'aiGov',
    values: [
      { label: 'Committed / Published', color: 'green' },
      { label: 'Mentioned', color: 'yellow' },
      { label: 'Absent', color: 'red' }
    ]
  },
  // Ethics and Corporate Governance.
  {
    key: 'kpiConsentMechanism',
    nameEn: 'Consent Mechanism',
    nameIt: 'Meccanismo di Consenso',
    descEn: 'Evaluates the quality of consent flows: explicit opt-in, granular controls vs. bundled consent or dark patterns.',
    descIt: 'Valuta la qualità dei flussi di consenso: opt-in esplicito, controlli granulari vs. consenso aggregato o dark pattern.',
    group: 'ethics',
    values: [
      { label: 'Explicit opt-in', color: 'green' },
      { label: 'Opt-out', color: 'yellow' },
      { label: 'Implicit / Bundled', color: 'red' }
    ]
  },
  {
    key: 'kpiRegulatoryCompliance',
    nameEn: 'Regulatory Compliance',
    nameIt: 'Conformità Normativa',
    descEn: 'Measures the degree of alignment with applicable regulatory frameworks such as GDPR, CCPA, EU AI Act, and DORA.',
    descIt: 'Misura il grado di allineamento ai framework normativi applicabili come GDPR, CCPA, EU AI Act e DORA.',
    group: 'ethics',
    values: [
      { label: 'Comprehensive', color: 'green' },
      { label: 'Partial', color: 'yellow' },
      { label: 'Minimal', color: 'red' }
    ]
  },
  {
    key: 'kpiBreachNotification',
    nameEn: 'Breach Notification',
    nameIt: 'Notifica Violazione',
    descEn: 'Assesses data breach notification policies: timing (within 24h/72h), scope of disclosure, and affected-user communication.',
    descIt: 'Valuta le policy di notifica delle violazioni: tempistiche (entro 24h/72h), ambito della divulgazione e comunicazione agli utenti interessati.',
    group: 'ethics',
    values: [
      { label: 'Within 24h', color: 'green' },
      { label: 'Within 72h', color: 'yellow' },
      { label: 'Unspecified', color: 'red' }
    ]
  },
  {
    key: 'kpiIndependentAudit',
    nameEn: 'Independent Audit',
    nameIt: 'Audit Indipendente',
    descEn: 'Checks whether the company undergoes independent third-party audits of its data practices and AI systems.',
    descIt: 'Verifica se l\'azienda si sottopone ad audit indipendenti da parte di terzi sulle proprie pratiche dati e sistemi IA.',
    group: 'ethics',
    values: [
      { label: 'External audit / Published', color: 'green' },
      { label: 'Mentioned', color: 'yellow' },
      { label: 'Absent / Undisclosed', color: 'red' }
    ]
  },
  {
    key: 'kpiContentModeration',
    nameEn: 'Content Moderation',
    nameIt: 'Moderazione Contenuti',
    descEn: 'Evaluates content moderation transparency: clear guidelines, appeal mechanisms, and reporting on enforcement actions.',
    descIt: 'Valuta la trasparenza della moderazione dei contenuti: linee guida chiare, meccanismi di appello e report sulle azioni di enforcement.',
    group: 'ethics',
    values: [
      { label: 'Transparent', color: 'green' },
      { label: 'Partial', color: 'yellow' },
      { label: 'Opaque', color: 'red' }
    ]
  }
];

// Bilingual text content.

const content = {
  en: {
    title: 'Methodology & Transparency',
    subtitle: 'How PolicyWatcher evaluates and classifies corporate policies',
    systemTitle: 'System Overview',
    systemDesc: 'PolicyWatcher uses a multi-stage automated pipeline to monitor, analyze, and classify corporate policy documents. The process is:\n\n1. **Retrieval & Hashing**: configured URLs are checked through direct fetch, explicit HTTP/2, optional VPS-rendered fetch for script-rendered pages, and freshness-guarded Wayback/Common Crawl archive recovery. Each strategy records outcome, HTTP status where available, failure/rejection reason and escalation path. Each valid retrieved text is hashed (SHA-256).\n2. **Failure Logging**: blocked, partial, anomalous or unusable pages are not replaced with invented content. The policy status is marked Partial, Unavailable or Needs Review and the check outcome is written to the check log.\n3. **Public Evidence Gate**: seeded, partial, unavailable or review-needed records are withheld from public routes until a source-verified baseline exists.\n4. **Diff Detection**: when a new hash is detected against a valid baseline, the system writes a version record and identifies the delta between versions.\n5. **AI Analysis (Gemini)**: the text delta is sent to Google Gemini for structured analysis, generating risk scores, KPI assessments, executive summaries, and remediation suggestions.\n6. **Region & Perspective Filtering**: each analysis is contextualized across 3 regions (EU, US, Global) and 2 perspectives (Individual, Enterprise).\n7. **Notifications**: subscribers are alerted via email only when material changes are detected from publishable source evidence.',
    workspaceTitle: 'Adaptive Workspace & Public Surfaces',
    workspaceDesc: 'Release 3.6.3 makes the Objective-based Dashboard Composer the first-use entry when there is no valid saved workspace or deep-link preset. Users choose an intent (Citizen, GRC / Legal, Research, Builder) and evidence depth (Snapshot, Operational, Forensic), then preview a composition produced from a typed registry of real dashboard evidence modules. The choice is reversible and can be persisted or deep-linked. Source QA is pinned in every stack; source-quality warnings, suspended sources, Dataset QA limits and unavailable states are never removed by composition.\n\nPublic exploration surfaces follow the same boundary: the Policy Signals Board ranks evidence availability and traceability, the Site Atlas maps public sections and protected admin boundaries, Roadmap records community priorities and delivered outcomes, Press tracks public references, Showcase and Infographics explain capabilities, and Trust exposes external quality signals. None of these surfaces convert operational evidence into certification.',
    riskTitle: 'Overall Risk Score (1-10)',
    riskDesc: 'Each monitored policy receives a composite risk score from 1 (very safe) to 10 (critical concerns). The score reflects data collection practices, AI governance posture, consent quality, regulatory alignment, and breach notification protocols.',
    riskLow: 'Low (1-3)',
    riskLowDesc: 'Strong user protections, transparent AI practices, explicit consent, quick breach notification, published audit results.',
    riskMedium: 'Medium (4-6)',
    riskMediumDesc: 'Partial protections, some opaque AI practices, opt-out consent flows, moderate data retention, limited third-party disclosure.',
    riskHigh: 'High (7-10)',
    riskHighDesc: 'Extensive data collection, opaque AI training practices, indefinite retention, broad third-party sharing, absence of independent audits.',
    riskRange: 'Range',
    riskLabel: 'Label',
    riskCriteria: 'Key Criteria',
    kpiTitle: 'The 15 KPIs: Definitions & Value Scale',
    kpiDesc: 'Each company is evaluated across 15 Key Performance Indicators grouped into three areas. The AI model analyzes the policy text and assigns one of three standardized values per KPI. Here is the full definition of each indicator and the meaning of its possible values:',
    kpiGroupPrivacy: 'Privacy & Data Protection',
    kpiGroupAiGov: 'AI Governance',
    kpiGroupEthics: 'Ethics & Corporate Governance',
    colorTitle: 'Color Coding Legend',
    colorDesc: 'The badge colors used across the dashboard and KPI matrix follow a consistent traffic-light scheme:',
    colorGreen: 'Protective: The policy demonstrates strong safeguards aligned with best practices.',
    colorYellow: 'Partial: Some protections exist but with gaps, limitations, or opt-out-only models.',
    colorRed: 'Critical: Weak or absent protections that may expose users to significant risk.',
    colorGray: 'Not assessed: Insufficient data in the policy text to make a determination.',
    paloTitle: 'PALO Framework Integration',
    paloDesc: 'PolicyWatcher\'s methodology is aligned with the **PALO Framework** (Principled AI Lifecycle Orchestration), a comprehensive end-to-end AI governance model developed by Fabrizio Degni. PALO synthesizes ISO 42001, the EU AI Act, OECD AI Principles, and NIST AI RMF into a unified operational lifecycle.',
    paloMapping: 'PolicyWatcher specifically maps onto several PALO lifecycle phases: it operates as a continuous **Deployment & Monitoring** tool (Phase 4) while its KPI framework draws from the **Ethical KPIs** paradigm that PALO advocates: converting abstract ethical principles into measurable, comparable metrics.',
    paloPhases: ['Ideation & Screening', 'Assessment & Planning', 'Dev & Validation', 'Deployment & Monitoring', 'Decommissioning'],
    paloPrinciples: ['Fairness & Non-Discrimination', 'Human Agency & Oversight', 'Transparency & Explainability', 'Societal & Environmental Well-being', 'Privacy & Data Governance'],
    paloVisit: 'Visit PALO Framework',
    selectionTitle: 'Company Selection Criteria',
    selectionDesc: 'The companies monitored by PolicyWatcher are selected based on 5 criteria:',
    selectionCriteria: [
      '**Large-Scale Impact**: Services with hundreds of millions or billions of active users, whose policy changes affect a significant portion of the global digital population.',
      '**AI Relevance**: Companies developing or integrating generative AI systems into their platforms, where data usage for model training is a critical concern.',
      '**Sensitive Data Exposure**: Platforms that collect sensitive data (financial, health, biometric, behavioral) requiring heightened regulatory scrutiny.',
      '**Regulatory Relevance**: Entities directly impacted by GDPR, EU AI Act, CCPA/CPRA, DORA, or other major data protection frameworks.',
      '**Sector Diversity**: Coverage across multiple industries (Tech, FinTech, Social Media, E-Commerce, AI Providers, Cloud/SaaS) to provide a broad comparative picture.'
    ],
    selectionNote: 'The monitored list is periodically expanded. Each policy analysis references a specific **version record** and **date** to ensure traceability.',
    sourceTitle: 'Source Selection & Dataset QA Status',
    sourceDesc: 'PolicyWatcher treats source quality as a first-class control, not a cosmetic detail. The source-selection hierarchy is:\n\n1. **Global first**: when a company publishes a global or international English policy, that canonical source is used for Global analysis.\n2. **Market-specific when available**: EU, US, UK, or other market-level analyses should point to the provider source for that market, not a generic page.\n3. **Localized pages are not primary evidence by default**: translated URLs (for example `/it/`) are flagged unless they are the best available market source and the jurisdiction label makes that clear.\n4. **Traceability over convenience**: every policy links to the configured monitored URL, version metadata, hash, check history, ingestion method, final URL, archive timestamp when applicable, and detected changes.\n5. **Public evidence gate**: snapshots and changes must be marked `publicEvidence` before public APIs, sitemap, digests, share pages, reports, timeline or benchmarks can expose them.\n6. **Bulk onboarding boundary**: `/admin/source-onboarding` persists proposed source, official-source review, first private baseline, QA gate and publication decision. Import, approval and baseline capture remain private; QA must pass and an administrator must explicitly publish. Hold and reject decisions remain recorded.\n7. **Re-baseline guard**: seed-only records can establish a first real baseline without creating a public change. If source-evidence logs or a public baseline already exist, the system uses normal comparison instead of destructive re-baseline.\n8. **Partial retrieval handling**: over-cap, incomplete or anomalous retrieval is marked Partial and suspended from public evidence instead of being promoted to a complete baseline.\n9. **Migration with auditability**: source URL migrations are scoped by company, policy name and jurisdiction, and can run in dry-run mode before touching production data.\n10. **Admin quality gates**: Dataset QA checks URL hygiene, source-fit, retrieval diagnostics, public-evidence state, seeded boundaries, hash integrity, freshness, AI JSON completeness, KPI coverage, regional-impact coverage, archive timestamp evidence, check logs, access logs and subscriber hygiene before release decisions.',
    sourceSeal: 'Dataset QA status is an operational release-control signal: open issues mean the dataset should be repaired or reviewed before the affected evidence is treated as publishable.',
    limitsTitle: 'Limitations & Disclaimer',
    limitsDesc1: `Release v${POLICYWATCHER_VERSION}: PolicyWatcher is in active development and presents evidence mapping, not certification. The assessments are generated by AI models (Google Gemini) through automated text analysis. While we strive for accuracy, these evaluations:`,
    limitsDesc2: '- May contain inaccuracies, interpretive errors, or omissions of legal language\n- Reflect a point-in-time analysis and may become outdated after the screening date\n- Do not constitute legal advice, compliance certification, or definitive assessment of corporate conduct\n- Are based solely on publicly available policy text and may not capture internal practices or confidential agreements\n- Should not be the basis for any legal, commercial, or compliance decision without independent verification',
    limitsDesc3: 'The author and the platform disclaim all liability for any decisions, actions, or omissions based on this information. The interpretation and use of the data presented are solely at the user\'s own risk and responsibility. Always verify with the original company documents and consult qualified legal professionals for compliance decisions.',
    legalTitle: 'Regulatory References',
    legalDesc: 'The following regulatory frameworks are referenced in PolicyWatcher\'s analysis. Each entry specifies the version and date of reference used:',
  },
  it: {
    title: 'Metodologia e Trasparenza',
    subtitle: 'Come PolicyWatcher valuta e classifica le policy aziendali',
    systemTitle: 'Panoramica del Sistema',
    systemDesc: 'PolicyWatcher utilizza una pipeline automatizzata multi-fase per monitorare, analizzare e classificare i documenti di policy aziendali. Il processo comprende:\n\n1. **Recupero & Hashing**: gli URL configurati sono controllati tramite fetch diretto, HTTP/2 esplicito, renderer VPS opzionale per pagine script-rendered e recupero Wayback/Common Crawl con freshness guard. Ogni strategia registra esito, HTTP status quando disponibile, motivo di fallimento/rifiuto e passaggio al fallback successivo. Ogni testo valido viene hashato (SHA-256).\n2. **Log dei fallimenti**: pagine bloccate, parziali, anomale o inutilizzabili non vengono sostituite con contenuto inventato. Lo stato diventa Partial, Unavailable o Needs Review e l\'esito viene scritto nel check log.\n3. **Gate public evidence**: record seed, partial, unavailable o needs-review non sono esposti sulle route pubbliche finché non esiste una baseline verificata da sorgente.\n4. **Rilevamento Differenze**: quando viene rilevato un nuovo hash rispetto a una baseline valida, il sistema scrive un record di versione e identifica il delta tra le versioni.\n5. **Analisi AI (Gemini)**: il delta testuale viene inviato a Google Gemini per analisi strutturata, generando punteggi di rischio, valutazioni KPI, sintesi esecutive e suggerimenti di remediation.\n6. **Filtro Regione e Prospettiva**: ogni analisi è contestualizzata su 3 regioni (UE, USA, Globale) e 2 prospettive (Privato, Azienda).\n7. **Notifiche**: gli iscritti vengono avvisati via email solo quando vengono rilevate modifiche significative da evidenza sorgente pubblicabile.',
    workspaceTitle: 'Workspace adattivo e superfici pubbliche',
    workspaceDesc: 'La release 3.6.3 rende il Composer della dashboard orientato all\'obiettivo il primo ingresso quando non esiste un workspace salvato valido o un preset deep-link. L\'utente sceglie un intento (Cittadino, GRC / Legal, Ricerca, Builder) e una profondita di evidenza (Snapshot, Operativa, Forensic), poi visualizza una composizione generata da un registro tipizzato di moduli reali della dashboard. La scelta e reversibile, persistibile e condivisibile via deep-link. Source QA resta fissato in ogni stack; avvisi sulla qualita delle fonti, sorgenti sospese, limiti Dataset QA e stati unavailable non vengono mai rimossi dalla composizione.\n\nLe superfici pubbliche seguono lo stesso perimetro: Policy Signals Board ordina disponibilita e tracciabilita delle evidenze, Site Atlas mappa sezioni pubbliche e confini admin protetti, Roadmap registra priorita community e risultati consegnati, Press conserva riferimenti pubblici, Showcase e Infographics spiegano le funzionalita, Trust espone segnali esterni di qualita. Nessuna di queste superfici trasforma evidenza operativa in certificazione.',
    riskTitle: 'Punteggio di Rischio Complessivo (1-10)',
    riskDesc: 'Ogni policy monitorata riceve un punteggio composito da 1 (molto sicura) a 10 (criticità rilevanti). Il punteggio riflette le pratiche di raccolta dati, la governance dell\'IA, la qualità del consenso, l\'allineamento normativo e i protocolli di notifica delle violazioni.',
    riskLow: 'Basso (1-3)',
    riskLowDesc: 'Forti protezioni utente, pratiche IA trasparenti, consenso esplicito, notifica rapida delle violazioni, risultati di audit pubblicati.',
    riskMedium: 'Medio (4-6)',
    riskMediumDesc: 'Protezioni parziali, alcune pratiche IA opache, flussi di consenso opt-out, conservazione dati moderata, divulgazione limitata a terzi.',
    riskHigh: 'Alto (7-10)',
    riskHighDesc: 'Raccolta dati estesa, pratiche di addestramento IA opache, conservazione indefinita, ampia condivisione con terzi, assenza di audit indipendenti.',
    riskRange: 'Intervallo',
    riskLabel: 'Etichetta',
    riskCriteria: 'Criteri Chiave',
    kpiTitle: 'I 15 KPI: Definizioni e Scala di Valori',
    kpiDesc: 'Ogni azienda viene valutata su 15 Indicatori Chiave di Prestazione raggruppati in tre aree. Il modello IA analizza il testo della policy e assegna uno dei tre valori standardizzati per KPI. Ecco la definizione completa di ciascun indicatore e il significato dei possibili valori:',
    kpiGroupPrivacy: 'Privacy e Protezione Dati',
    kpiGroupAiGov: 'Governance dell\'IA',
    kpiGroupEthics: 'Etica e Governance Aziendale',
    colorTitle: 'Legenda Codifica Cromatica',
    colorDesc: 'I colori dei badge utilizzati nella dashboard e nella matrice KPI seguono uno schema semaforico coerente:',
    colorGreen: 'Protettivo: La policy dimostra forti garanzie allineate alle migliori pratiche.',
    colorYellow: 'Parziale: Esistono alcune protezioni ma con lacune, limitazioni o modelli solo opt-out.',
    colorRed: 'Critico: Protezioni deboli o assenti che possono esporre gli utenti a rischi significativi.',
    colorGray: 'Non valutato: Dati insufficienti nel testo della policy per effettuare una determinazione.',
    paloTitle: 'Integrazione PALO Framework',
    paloDesc: 'La metodologia di PolicyWatcher è allineata al **PALO Framework** (Principled AI Lifecycle Orchestration), un modello di governance IA end-to-end sviluppato da Fabrizio Degni. PALO sintetizza ISO 42001, EU AI Act, Principi OCSE sull\'IA e NIST AI RMF in un ciclo di vita operativo unificato.',
    paloMapping: 'PolicyWatcher si inserisce specificamente in diverse fasi del ciclo di vita PALO: opera come strumento di **Deployment & Monitoring** continuo (Fase 4) mentre il suo framework KPI attinge dal paradigma dei **KPI Etici** che PALO promuove: convertendo principi etici astratti in metriche misurabili e comparabili.',
    paloPhases: ['Ideazione & Screening', 'Valutazione & Pianificazione', 'Sviluppo & Validazione', 'Deployment & Monitoraggio', 'Decommissioning'],
    paloPrinciples: ['Equità e Non-Discriminazione', 'Agenzia Umana e Supervisione', 'Trasparenza e Spiegabilità', 'Benessere Sociale e Ambientale', 'Privacy e Governance dei Dati'],
    paloVisit: 'Visita PALO Framework',
    selectionTitle: 'Criteri di Selezione delle Aziende',
    selectionDesc: 'Le aziende monitorate da PolicyWatcher sono selezionate in base a 5 criteri:',
    selectionCriteria: [
      '**Impatto su larga scala**: Servizi con centinaia di milioni o miliardi di utenti attivi, le cui modifiche di policy impattano una porzione significativa della popolazione digitale globale.',
      '**Rilevanza AI**: Aziende che sviluppano o integrano sistemi di IA generativa nelle proprie piattaforme, dove l\'uso dei dati per l\'addestramento dei modelli è una criticità centrale.',
      '**Esposizione a dati sensibili**: Piattaforme che raccolgono dati sensibili (finanziari, sanitari, biometrici, comportamentali) soggetti a scrutinio normativo rafforzato.',
      '**Rilevanza normativa**: Soggetti direttamente impattati da GDPR, EU AI Act, CCPA/CPRA, DORA o altri importanti framework di protezione dati.',
      '**Diversità settoriale**: Copertura di più industrie (Tech, FinTech, Social Media, E-Commerce, Provider AI, Cloud/SaaS) per un quadro comparativo ampio.'
    ],
    selectionNote: 'La lista è periodicamente ampliata. Ogni analisi di policy fa riferimento a uno specifico **record di versione** e a una **data** per mantenere la tracciabilità.',
    sourceTitle: 'Selezione Fonti e Stato QA Dataset',
    sourceDesc: 'PolicyWatcher considera la qualità della fonte un controllo primario, non un dettaglio estetico. La gerarchia di selezione è:\n\n1. **Global prima di tutto**: quando l’azienda pubblica una policy globale o internazionale in inglese, quella fonte canonica viene usata per l’analisi Global.\n2. **Mercato specifico quando disponibile**: analisi EU, US, UK o di altri mercati devono puntare alla fonte provider per quel mercato, non a una pagina generica.\n3. **Le pagine localizzate non sono prova primaria di default**: URL tradotti, ad esempio `/it/`, vengono segnalati salvo siano la fonte di mercato più adatta e la giurisdizione lo renda chiaro.\n4. **Tracciabilità sopra la comodità**: ogni policy mantiene URL configurato, metadati di versione, hash, check history, metodo di ingestione, final URL, timestamp archivio quando disponibile e modifiche rilevate.\n5. **Gate publicEvidence**: snapshot e change devono essere marcati `publicEvidence` prima che API pubbliche, sitemap, digest, share page, report, timeline o benchmark li espongano.\n6. **Confine del bulk onboarding**: `/admin/source-onboarding` persiste fonte proposta, revisione della fonte ufficiale, prima baseline privata, gate QA e decisione di pubblicazione. Import, approvazione e cattura della baseline restano privati; il QA deve passare e un amministratore deve pubblicare esplicitamente. Le decisioni hold e reject restano registrate.\n7. **Guardia re-baseline**: i record seed-only possono stabilire una prima baseline reale senza creare change pubblici. Se esistono già log di evidenza sorgente o baseline pubblica, il sistema usa il confronto normale invece della re-baseline distruttiva.\n8. **Gestione Partial**: recuperi incompleti, anomali o oltre il limite vengono marcati Partial e sospesi dall’evidenza pubblica invece di diventare baseline complete.\n9. **Migrazioni auditabili**: le migrazioni degli URL sorgente sono limitate per company, nome policy e giurisdizione e possono essere lanciate in dry-run prima di modificare la produzione.\n10. **Quality gate amministrativi**: Dataset QA verifica igiene URL, source-fit, diagnostica retrieval, stato public-evidence, confini seed, integrità hash, freschezza, completezza JSON AI, copertura KPI, impatti regionali, timestamp archivio, check log, access log e igiene subscriber prima delle decisioni di rilascio.',
    sourceSeal: 'Lo stato Dataset QA è un segnale operativo di controllo release: issue aperte indicano che il dataset va corretto o revisionato prima che l’evidenza coinvolta sia considerata pubblicabile.',
    limitsTitle: 'Limitazioni e Disclaimer',
    limitsDesc1: `Release v${POLICYWATCHER_VERSION}: PolicyWatcher e in sviluppo attivo e presenta una mappatura di evidenze, non una certificazione. Le valutazioni sono generate da modelli IA (Google Gemini) tramite analisi testuale automatizzata. Pur impegnandoci per l'accuratezza, queste valutazioni:`,
    limitsDesc2: '- Possono contenere imprecisioni, errori interpretativi o omissioni del linguaggio giuridico\n- Riflettono un\'analisi a un momento specifico e possono diventare obsolete dopo la data di screening\n- Non costituiscono consulenza legale, certificazione di conformita o valutazione definitiva della condotta aziendale\n- Si basano esclusivamente su testo di policy pubblicamente disponibile e potrebbero non catturare pratiche interne o accordi riservati\n- Non devono essere alla base di alcuna decisione legale, commerciale o di conformita senza verifica indipendente',
    limitsDesc3: 'L\'autore e la piattaforma declinano qualsiasi responsabilita per decisioni, azioni o omissioni basate su queste informazioni. L\'interpretazione e l\'uso dei dati presentati sono esclusivamente a rischio e responsabilita dell\'utente. Verificare sempre direttamente con i documenti ufficiali e consultare professionisti legali qualificati per le decisioni di conformita.',
    legalTitle: 'Riferimenti Normativi',
    legalDesc: 'I seguenti framework normativi sono referenziati nell\'analisi di PolicyWatcher. Ogni voce specifica la versione e la data di riferimento utilizzata:',
  }
};

const legalFrameworks = [
  {
    name: 'GDPR',
    version: 'Regulation (EU) 2016/679',
    date: '2018-05-25',
    url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
    desc: {
      en: 'General Data Protection Regulation: EU baseline for personal data processing, consent, data subject rights, and cross-border transfers.',
      it: 'Regolamento Generale sulla Protezione dei Dati: Base UE per il trattamento dei dati personali, consenso, diritti degli interessati e trasferimenti transfrontalieri.'
    }
  },
  {
    name: 'CCPA / CPRA',
    version: 'Cal. Civ. Code sections 1798.100-1798.199.100 (as amended by CPRA, Prop. 24)',
    date: '2023-01-01',
    url: 'https://oag.ca.gov/privacy/ccpa',
    desc: {
      en: 'California Consumer Privacy Act & California Privacy Rights Act: US state-level privacy regulation covering data sale opt-out, deletion rights, and automated decision-making.',
      it: 'California Consumer Privacy Act e California Privacy Rights Act: Regolamentazione privacy a livello statale USA: opt-out vendita dati, diritto alla cancellazione, decisioni automatizzate.'
    }
  },
  {
    name: 'EU AI Act',
    version: 'Regulation (EU) 2024/1689',
    date: '2024-08-01',
    url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    desc: {
      en: 'EU Artificial Intelligence Act: Risk-based framework for AI system regulation. Key articles referenced: Art. 6 (risk classification), Art. 9 (risk management), Art. 13 (transparency), Art. 27 (FRIA).',
      it: 'EU AI Act: Quadro basato sul rischio per la regolazione dei sistemi IA. Articoli chiave: Art. 6 (classificazione rischio), Art. 9 (gestione rischio), Art. 13 (trasparenza), Art. 27 (FRIA).'
    }
  },
  {
    name: 'DORA',
    version: 'Regulation (EU) 2022/2554',
    date: '2025-01-17',
    url: 'https://eur-lex.europa.eu/eli/reg/2022/2554/oj',
    desc: {
      en: 'Digital Operational Resilience Act: ICT risk management framework for financial entities. Relevant for FinTech companies in the monitored portfolio.',
      it: 'Digital Operational Resilience Act: Framework di gestione rischi ICT per entità finanziarie. Rilevante per le aziende FinTech nel portafoglio monitorato.'
    }
  },
  {
    name: 'NIST AI RMF',
    version: 'NIST AI 100-1 (v1.0)',
    date: '2023-01-26',
    url: 'https://www.nist.gov/artificial-intelligence/executive-order-safe-secure-and-trustworthy-ai',
    desc: {
      en: 'NIST AI Risk Management Framework: US voluntary framework for trustworthy AI. Referenced for Govern, Map, Measure, and Manage functions.',
      it: 'NIST AI Risk Management Framework: Framework volontario USA per IA affidabile. Utilizzato per le funzioni Govern, Map, Measure e Manage.'
    }
  },
  {
    name: 'ISO/IEC 42001',
    version: 'ISO/IEC 42001:2023',
    date: '2023-12-18',
    url: 'https://www.iso.org/standard/81230.html',
    desc: {
      en: 'AI Management System standard: Requirements for establishing, implementing, and improving an AI management system within organizations.',
      it: 'Standard per il Sistema di Gestione dell\'IA: Requisiti per istituire, implementare e migliorare un sistema di gestione IA nelle organizzazioni.'
    }
  },
  {
    name: 'OECD AI Principles',
    version: 'OECD/LEGAL/0449 (revised 2024)',
    date: '2024-05-03',
    url: 'https://oecd.ai/en/ai-principles',
    desc: {
      en: 'OECD Recommendation on AI: International guidelines for trustworthy AI, adopted by 46 countries. Updated in 2024 to address generative AI.',
      it: 'Raccomandazione OCSE sull\'IA: Linee guida internazionali per IA affidabile, adottate da 46 paesi. Aggiornate nel 2024 per l\'IA generativa.'
    }
  },
  {
    name: 'PALO Framework',
    version: 'v2.0 (incl. PALO-AM Agentic Module)',
    date: '2026-06-01',
    url: 'https://www.paloframework.org',
    desc: {
      en: 'Principled AI Lifecycle Orchestration: End-to-end AI governance model by Fabrizio Degni integrating ISO 42001, EU AI Act, OECD, and NIST AI RMF.',
      it: 'Principled AI Lifecycle Orchestration: Modello di governance IA end-to-end di Fabrizio Degni che integra ISO 42001, EU AI Act, OCSE e NIST AI RMF.'
    }
  },
];

// Render helpers.

function renderMarkdown(text: string) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i}>{part.slice(2, -2)}</strong>;
    }
    return part;
  });
}

// Component.

export default function MethodologyModal({ isOpen, onClose, lang }: MethodologyModalProps) {
  const t = content[lang];
  const privacyKPIs = kpiDefinitions.filter(k => k.group === 'privacy');
  const aiGovKPIs = kpiDefinitions.filter(k => k.group === 'aiGov');
  const ethicsKPIs = kpiDefinitions.filter(k => k.group === 'ethics');
  const kpiSignalColor: Record<KPIDef['values'][number]['color'], string> = {
    green: '#10b981',
    yellow: '#f59e0b',
    red: '#ef4444',
  };

  const renderKPIGroup = (kpis: KPIDef[], groupLabel: string, iconClass: string, icon: React.ReactNode) => (
    <div className={styles.kpiGroup}>
      <div className={styles.kpiGroupTitle}>
        {icon} {groupLabel}
      </div>
      {kpis.map(kpi => (
        <div key={kpi.key} className={styles.kpiCard}>
          <div className={styles.kpiName}>{lang === 'en' ? kpi.nameEn : kpi.nameIt}</div>
          <div className={styles.kpiDescription}>{lang === 'en' ? kpi.descEn : kpi.descIt}</div>
          <div className={styles.kpiValues}>
            {kpi.values.map((v, i) => (
              <span key={i} className={`${styles.kpiValueBadge} ${styles[v.color]}`}>
                <IconKpiSignal size={12} color={kpiSignalColor[v.color]} className={styles.kpiValueIcon} />
                {v.label}
              </span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            className={styles.backdrop}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
          />
          <motion.div
            className={styles.modal}
            initial={{ opacity: 0, scale: 0.95, x: "-50%", y: "-45%" }}
            animate={{ opacity: 1, scale: 1, x: "-50%", y: "-50%" }}
            exit={{ opacity: 0, scale: 0.95, x: "-50%", y: "-45%" }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          >
            <button className={styles.closeBtn} onClick={onClose} aria-label="Close">
              <X size={20} />
            </button>

            {/* Header */}
            <div className={styles.header}>
              <div className={styles.headerIcon}>
                <BookOpen size={24} />
              </div>
              <h2>{t.title}</h2>
              <p className={styles.headerSubtitle}>{t.subtitle}</p>
            </div>

            {/* Body */}
            <div className={styles.body}>

              {/* 1. System Overview */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.system}`}><Layers size={16} /></span>
                {t.systemTitle}
              </div>
              <div className={styles.sectionDescription}>
                {t.systemDesc.split('\n').map((line, i) => (
                  <span key={i}>{renderMarkdown(line)}{i < t.systemDesc.split('\n').length - 1 && <br />}</span>
                ))}
              </div>

              <hr className={styles.divider} />

              {/* 2. Adaptive Workspace & Public Surfaces */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.system}`}><Target size={16} /></span>
                {t.workspaceTitle}
              </div>
              <div className={styles.sectionDescription}>
                {t.workspaceDesc.split('\n').map((line, i) => (
                  <span key={i}>{renderMarkdown(line)}{i < t.workspaceDesc.split('\n').length - 1 && <br />}</span>
                ))}
              </div>

              <hr className={styles.divider} />

              {/* 3. Risk Score */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.risk}`}><Gauge size={16} /></span>
                {t.riskTitle}
              </div>
              <p className={styles.sectionDescription}>{t.riskDesc}</p>
              <table className={styles.riskTable}>
                <thead>
                  <tr>
                    <th>{t.riskRange}</th>
                    <th>{t.riskLabel}</th>
                    <th>{t.riskCriteria}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><span className={`${styles.kpiValueBadge} ${styles.green}`}>1-3</span></td>
                    <td>{t.riskLow}</td>
                    <td>{t.riskLowDesc}</td>
                  </tr>
                  <tr>
                    <td><span className={`${styles.kpiValueBadge} ${styles.yellow}`}>4-6</span></td>
                    <td>{t.riskMedium}</td>
                    <td>{t.riskMediumDesc}</td>
                  </tr>
                  <tr>
                    <td><span className={`${styles.kpiValueBadge} ${styles.red}`}>7-10</span></td>
                    <td>{t.riskHigh}</td>
                    <td>{t.riskHighDesc}</td>
                  </tr>
                </tbody>
              </table>

              <hr className={styles.divider} />

              {/* 4. KPI Definitions */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.privacy}`}><Activity size={16} /></span>
                {t.kpiTitle}
              </div>
              <p className={styles.sectionDescription}>{t.kpiDesc}</p>

              {renderKPIGroup(privacyKPIs, lang === 'en' ? 'Privacy & Data Protection' : 'Privacy e Protezione Dati', 'privacy', <Shield size={16} />)}
              {renderKPIGroup(aiGovKPIs, lang === 'en' ? 'AI Governance' : 'Governance dell\'IA', 'aiGov', <Brain size={16} />)}
              {renderKPIGroup(ethicsKPIs, lang === 'en' ? 'Ethics & Corporate Governance' : 'Etica e Governance Aziendale', 'ethics', <Scale size={16} />)}

              <hr className={styles.divider} />

              {/* 5. Color Coding */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.color}`}><Eye size={16} /></span>
                {t.colorTitle}
              </div>
              <p className={styles.sectionDescription}>{t.colorDesc}</p>
              <div className={styles.colorLegend}>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.green}`} />
                  <div>
                    <div className={styles.legendLabel}>Green</div>
                    <div className={styles.legendDesc}>{t.colorGreen}</div>
                  </div>
                </div>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.yellow}`} />
                  <div>
                    <div className={styles.legendLabel}>Yellow</div>
                    <div className={styles.legendDesc}>{t.colorYellow}</div>
                  </div>
                </div>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.red}`} />
                  <div>
                    <div className={styles.legendLabel}>Red</div>
                    <div className={styles.legendDesc}>{t.colorRed}</div>
                  </div>
                </div>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.muted}`} />
                  <div>
                    <div className={styles.legendLabel}>Gray</div>
                    <div className={styles.legendDesc}>{t.colorGray}</div>
                  </div>
                </div>
              </div>

              <hr className={styles.divider} />

              {/* 6. PALO Framework */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.palo}`}><Shield size={16} /></span>
                {t.paloTitle}
              </div>
              <div className={styles.paloCard}>
                <div className={styles.paloHeader}>
                  <div className={styles.paloLogo}>PALO</div>
                  <div>
                    <div className={styles.paloTitle}>PALO Framework</div>
                    <div className={styles.paloSubtitle}>Principled AI Lifecycle Orchestration</div>
                  </div>
                </div>
                <p className={styles.paloDescription}>{renderMarkdown(t.paloDesc)}</p>
                
                <div className={styles.paloPhases}>
                  {t.paloPhases.map((phase, i) => (
                    <div key={i} className={styles.paloPhase}>
                      <div className={styles.paloPhaseNum}>{lang === 'en' ? `Phase ${i + 1}` : `Fase ${i + 1}`}</div>
                      <div className={styles.paloPhaseName}>{phase}</div>
                    </div>
                  ))}
                </div>

                <div className={styles.paloPrinciples}>
                  {t.paloPrinciples.map((p, i) => (
                    <span key={i} className={styles.paloPrinciple}>{p}</span>
                  ))}
                </div>

                <p className={styles.paloMappingNote}>{renderMarkdown(t.paloMapping)}</p>

                <a 
                  href="https://www.paloframework.org" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className={styles.paloLink}
                >
                  <ExternalLink size={16} />
                  {t.paloVisit}
                </a>
              </div>

              <hr className={styles.divider} />

              {/* 6. Limitations */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.limits}`}><AlertTriangle size={16} /></span>
                {t.limitsTitle}
              </div>
              <div className={styles.disclaimerCard}>
                <p>{t.limitsDesc1}</p>
                <p>{t.limitsDesc2.split('\n').map((line, i) => (
                  <span key={i}>{line}<br /></span>
                ))}</p>
                <p><strong>{t.limitsDesc3}</strong></p>
              </div>

              <hr className={styles.divider} />

              {/* 7. Selection Criteria */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.system}`}><Target size={16} /></span>
                {t.selectionTitle}
              </div>
              <p className={styles.sectionDescription}>{t.selectionDesc}</p>
              <div className={styles.disclaimerCard}>
                {t.selectionCriteria.map((criterion, i) => (
                  <p key={i} style={{ margin: '6px 0' }}>{renderMarkdown(`${i + 1}. ${criterion}`)}</p>
                ))}
                <p style={{ marginTop: 12, fontStyle: 'italic' }}>{renderMarkdown(t.selectionNote)}</p>
              </div>

              <hr className={styles.divider} />

              {/* 8. Source Quality */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.privacy}`}><CheckCircle size={16} /></span>
                {t.sourceTitle}
              </div>
              <div className={styles.disclaimerCard}>
                {t.sourceDesc.split('\n').map((line, i) => (
                  <span key={i}>{renderMarkdown(line)}{i < t.sourceDesc.split('\n').length - 1 && <br />}</span>
                ))}
                <p style={{ marginTop: 12 }}>
                  <strong>{t.sourceSeal}</strong>
                </p>
              </div>

              <hr className={styles.divider} />

              {/* 9. Legal References (versioned) */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.legal}`}><Scale size={16} /></span>
                {t.legalTitle}
              </div>
              <p className={styles.sectionDescription}>{t.legalDesc}</p>
              <ul className={styles.standardsList}>
                {legalFrameworks.map((fw, i) => (
                  <li key={i}>
                    <Scale size={14} className={styles.standardsIcon} />
                    <div>
                      <div><strong>{fw.name}</strong>: {lang === 'en' ? fw.desc.en : fw.desc.it}</div>
                      <div style={{ fontSize: '0.78rem', color: '#888', marginTop: 3 }}>
                        {lang === 'en' ? 'Ref.' : 'Rif.'}: <em>{fw.version}</em>: {lang === 'en' ? 'Effective' : 'In vigore dal'}: {fw.date}
                        {' / '}
                        <a href={fw.url} target="_blank" rel="noopener noreferrer" style={{ color: '#6366f1', textDecoration: 'none' }}>
                          {lang === 'en' ? 'Official text' : 'Testo ufficiale'}
                          <ExternalLink size={12} className={styles.externalInlineIcon} />
                        </a>
                      </div>
                    </div>
                  </li>
                ))}
              </ul>

            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
