'use client';
import React from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import styles from './MethodologyModal.module.css';
import { 
  X, Shield, Brain, Scale, Eye, AlertTriangle, 
  BookOpen, Activity, ExternalLink, Layers, Gauge, Target, CheckCircle
} from 'lucide-react';

interface MethodologyModalProps {
  isOpen: boolean;
  onClose: () => void;
  lang: 'en' | 'it';
}

// ─── KPI definitions with bilingual descriptions and possible values ───────────

interface KPIDef {
  key: string;
  nameEn: string;
  nameIt: string;
  descEn: string;
  descIt: string;
  group: 'privacy' | 'aiGov' | 'ethics';
  values: { label: string; color: 'green' | 'yellow' | 'red' }[];
}

const kpiDefinitions: KPIDef[] = [
  // ── Privacy & Data Protection ──
  {
    key: 'kpiDataCollection',
    nameEn: 'Data Collection Scope',
    nameIt: 'Ambito Raccolta Dati',
    descEn: 'Measures the breadth of personal data collected by the company: types, categories, and whether collection is proportional to the stated purpose.',
    descIt: 'Misura l\'ampiezza dei dati personali raccolti dall\'azienda: tipologie, categorie, e se la raccolta è proporzionale allo scopo dichiarato.',
    group: 'privacy',
    values: [
      { label: 'Minimal', color: 'green' },
      { label: 'Moderate', color: 'yellow' },
      { label: 'Extensive', color: 'red' }
    ]
  },
  {
    key: 'kpiThirdPartySharing',
    nameEn: 'Third-Party Sharing',
    nameIt: 'Condivisione Terze Parti',
    descEn: 'Evaluates the extent and transparency of data sharing with external entities including advertisers, partners, and data brokers.',
    descIt: 'Valuta l\'entità e la trasparenza della condivisione dei dati con soggetti terzi, inclusi inserzionisti, partner e data broker.',
    group: 'privacy',
    values: [
      { label: 'None / Restricted', color: 'green' },
      { label: 'Limited / Controlled', color: 'yellow' },
      { label: 'Broad / Undisclosed', color: 'red' }
    ]
  },
  {
    key: 'kpiDataRetention',
    nameEn: 'Data Retention',
    nameIt: 'Conservazione Dati',
    descEn: 'Assesses how long the company retains personal data and whether a clear retention schedule is defined.',
    descIt: 'Valuta per quanto tempo l\'azienda conserva i dati personali e se è definito un calendario di conservazione chiaro.',
    group: 'privacy',
    values: [
      { label: 'Limited (defined)', color: 'green' },
      { label: 'Extended', color: 'yellow' },
      { label: 'Indefinite', color: 'red' }
    ]
  },
  {
    key: 'kpiRightToDeletion',
    nameEn: 'Right to Deletion',
    nameIt: 'Diritto alla Cancellazione',
    descEn: 'Checks whether users can request full deletion of their data and how effectively the company honors such requests.',
    descIt: 'Verifica se gli utenti possono richiedere la cancellazione completa dei propri dati e con quale efficacia l\'azienda soddisfa tali richieste.',
    group: 'privacy',
    values: [
      { label: 'Full / Available', color: 'green' },
      { label: 'Partial', color: 'yellow' },
      { label: 'Not available', color: 'red' }
    ]
  },
  {
    key: 'kpiCrossBorderTransfer',
    nameEn: 'Cross-Border Transfer',
    nameIt: 'Trasferimento Transfrontaliero',
    descEn: 'Evaluates whether data is transferred across jurisdictions and the safeguards in place (e.g., SCCs, adequacy decisions).',
    descIt: 'Valuta se i dati vengono trasferiti tra giurisdizioni e le garanzie adottate (es. SCC, decisioni di adeguatezza).',
    group: 'privacy',
    values: [
      { label: 'Restricted', color: 'green' },
      { label: 'Controlled', color: 'yellow' },
      { label: 'Unrestricted', color: 'red' }
    ]
  },
  // ── AI Governance ──
  {
    key: 'kpiAiTrainingOptOut',
    nameEn: 'AI Training Opt-Out',
    nameIt: 'Opt-Out Addestramento AI',
    descEn: 'Checks whether users can opt out of having their data (conversations, uploads, content) used to train the company\'s AI models.',
    descIt: 'Verifica se gli utenti possono rifiutare l\'utilizzo dei propri dati (conversazioni, upload, contenuti) per l\'addestramento dei modelli IA dell\'azienda.',
    group: 'aiGov',
    values: [
      { label: 'Available / Not used', color: 'green' },
      { label: 'Opt-out available', color: 'yellow' },
      { label: 'Not available', color: 'red' }
    ]
  },
  {
    key: 'kpiAiOutputOwnership',
    nameEn: 'AI Output Ownership',
    nameIt: 'Proprietà Output AI',
    descEn: 'Determines who owns the intellectual property of content generated by AI tools: the user, the company, or shared ownership.',
    descIt: 'Determina chi detiene la proprietà intellettuale dei contenuti generati dagli strumenti IA: l\'utente, l\'azienda o proprietà condivisa.',
    group: 'aiGov',
    values: [
      { label: 'User retained', color: 'green' },
      { label: 'Shared', color: 'yellow' },
      { label: 'Company claimed', color: 'red' }
    ]
  },
  {
    key: 'kpiAlgoTransparency',
    nameEn: 'Algorithmic Transparency',
    nameIt: 'Trasparenza Algoritmica',
    descEn: 'Measures how transparent the company is about how its algorithms work, including recommendation engines and automated decision systems.',
    descIt: 'Misura la trasparenza dell\'azienda sul funzionamento dei propri algoritmi, inclusi motori di raccomandazione e sistemi decisionali automatizzati.',
    group: 'aiGov',
    values: [
      { label: 'Published / Disclosed', color: 'green' },
      { label: 'Mentioned / Partial', color: 'yellow' },
      { label: 'Opaque / Undisclosed', color: 'red' }
    ]
  },
  {
    key: 'kpiAutomatedDecision',
    nameEn: 'Automated Decisions',
    nameIt: 'Decisioni Automatizzate',
    descEn: 'Evaluates whether automated decision-making processes are disclosed and if meaningful human review mechanisms exist.',
    descIt: 'Valuta se i processi di decisione automatizzata sono dichiarati e se esistono meccanismi significativi di revisione umana.',
    group: 'aiGov',
    values: [
      { label: 'Transparent / Human-in-loop', color: 'green' },
      { label: 'Partial disclosure', color: 'yellow' },
      { label: 'Opaque / No review', color: 'red' }
    ]
  },
  {
    key: 'kpiAiBiasFairness',
    nameEn: 'AI Bias & Fairness',
    nameIt: 'Bias e Equità AI',
    descEn: 'Assesses whether the company acknowledges AI bias risks and has active mitigation strategies (e.g., fairness audits, diverse datasets).',
    descIt: 'Valuta se l\'azienda riconosce i rischi di bias nei propri sistemi IA e ha strategie attive di mitigazione (es. audit di equità, dataset diversificati).',
    group: 'aiGov',
    values: [
      { label: 'Committed / Certified', color: 'green' },
      { label: 'Mentioned', color: 'yellow' },
      { label: 'Absent', color: 'red' }
    ]
  },
  // ── Ethics & Corporate Governance ──
  {
    key: 'kpiConsentMechanism',
    nameEn: 'Consent Mechanism',
    nameIt: 'Meccanismo di Consenso',
    descEn: 'Evaluates the quality of consent flows: explicit opt-in, granular controls vs. bundled consent or dark patterns.',
    descIt: 'Valuta la qualità dei flussi di consenso: opt-in esplicito, controlli granulari vs. consenso aggregato o dark pattern.',
    group: 'ethics',
    values: [
      { label: 'Explicit opt-in', color: 'green' },
      { label: 'Opt-out', color: 'yellow' },
      { label: 'Implicit / Bundled', color: 'red' }
    ]
  },
  {
    key: 'kpiRegulatoryCompliance',
    nameEn: 'Regulatory Compliance',
    nameIt: 'Conformità Normativa',
    descEn: 'Measures the degree of alignment with applicable regulatory frameworks such as GDPR, CCPA, EU AI Act, and DORA.',
    descIt: 'Misura il grado di allineamento ai framework normativi applicabili come GDPR, CCPA, EU AI Act e DORA.',
    group: 'ethics',
    values: [
      { label: 'Comprehensive', color: 'green' },
      { label: 'Partial', color: 'yellow' },
      { label: 'Minimal', color: 'red' }
    ]
  },
  {
    key: 'kpiBreachNotification',
    nameEn: 'Breach Notification',
    nameIt: 'Notifica Violazione',
    descEn: 'Assesses data breach notification policies: timing (within 24h/72h), scope of disclosure, and affected-user communication.',
    descIt: 'Valuta le policy di notifica delle violazioni: tempistiche (entro 24h/72h), ambito della divulgazione e comunicazione agli utenti interessati.',
    group: 'ethics',
    values: [
      { label: 'Within 24h', color: 'green' },
      { label: 'Within 72h', color: 'yellow' },
      { label: 'Unspecified', color: 'red' }
    ]
  },
  {
    key: 'kpiIndependentAudit',
    nameEn: 'Independent Audit',
    nameIt: 'Audit Indipendente',
    descEn: 'Checks whether the company undergoes independent third-party audits of its data practices and AI systems.',
    descIt: 'Verifica se l\'azienda si sottopone ad audit indipendenti da parte di terzi sulle proprie pratiche dati e sistemi IA.',
    group: 'ethics',
    values: [
      { label: 'Certified / Published', color: 'green' },
      { label: 'Mentioned', color: 'yellow' },
      { label: 'Absent / Undisclosed', color: 'red' }
    ]
  },
  {
    key: 'kpiContentModeration',
    nameEn: 'Content Moderation',
    nameIt: 'Moderazione Contenuti',
    descEn: 'Evaluates content moderation transparency: clear guidelines, appeal mechanisms, and reporting on enforcement actions.',
    descIt: 'Valuta la trasparenza della moderazione dei contenuti: linee guida chiare, meccanismi di appello e report sulle azioni di enforcement.',
    group: 'ethics',
    values: [
      { label: 'Transparent', color: 'green' },
      { label: 'Partial', color: 'yellow' },
      { label: 'Opaque', color: 'red' }
    ]
  }
];

// ─── Bilingual text content ───────────────────────────────────────────────────

const content = {
  en: {
    title: 'Methodology & Transparency',
    subtitle: 'How PolicyWatcher evaluates and classifies corporate policies',
    systemTitle: 'System Overview',
    systemDesc: 'PolicyWatcher uses a multi-stage automated pipeline to monitor, analyze, and classify corporate policy documents. The process is:\n\n1. **Scraping & Hashing**: Policy documents are periodically fetched from official company URLs. Each version is hashed (SHA-256) to detect changes.\n2. **Diff Detection**: When a new hash is detected, the system stores a new snapshot and identifies the delta between versions.\n3. **AI Analysis (Gemini)**: The text delta is sent to Google Gemini for natural language analysis, generating risk scores, KPI assessments, executive summaries, and remediation suggestions.\n4. **Region & Perspective Filtering**: Each analysis is contextualized across 3 regions (EU, US, Global) and 2 perspectives (Individual, Enterprise).\n5. **Notifications**: Subscribers are alerted via email when material changes are detected.',
    riskTitle: 'Overall Risk Score (1-10)',
    riskDesc: 'Each monitored policy receives a composite risk score from 1 (very safe) to 10 (critical concerns). The score reflects data collection practices, AI governance posture, consent quality, regulatory alignment, and breach notification protocols.',
    riskLow: 'Low (1-3)',
    riskLowDesc: 'Strong user protections, transparent AI practices, explicit consent, quick breach notification, published audit results.',
    riskMedium: 'Medium (4-6)',
    riskMediumDesc: 'Partial protections, some opaque AI practices, opt-out consent flows, moderate data retention, limited third-party disclosure.',
    riskHigh: 'High (7-10)',
    riskHighDesc: 'Extensive data collection, opaque AI training practices, indefinite retention, broad third-party sharing, absence of independent audits.',
    riskRange: 'Range',
    riskLabel: 'Label',
    riskCriteria: 'Key Criteria',
    kpiTitle: 'The 15 KPIs: Definitions & Value Scale',
    kpiDesc: 'Each company is evaluated across 15 Key Performance Indicators grouped into three areas. The AI model analyzes the policy text and assigns one of three standardized values per KPI. Here is the full definition of each indicator and the meaning of its possible values:',
    kpiGroupPrivacy: 'Privacy & Data Protection',
    kpiGroupAiGov: 'AI Governance',
    kpiGroupEthics: 'Ethics & Corporate Governance',
    colorTitle: 'Color Coding Legend',
    colorDesc: 'The badge colors used across the dashboard and KPI matrix follow a consistent traffic-light scheme:',
    colorGreen: 'Protective: The policy demonstrates strong safeguards aligned with best practices.',
    colorYellow: 'Partial: Some protections exist but with gaps, limitations, or opt-out-only models.',
    colorRed: 'Critical: Weak or absent protections that may expose users to significant risk.',
    colorGray: 'Not assessed: Insufficient data in the policy text to make a determination.',
    paloTitle: 'PALO Framework Integration',
    paloDesc: 'PolicyWatcher\'s methodology is aligned with the **PALO Framework** (Principled AI Lifecycle Orchestration), a comprehensive end-to-end AI governance model developed by Fabrizio Degni. PALO synthesizes ISO 42001, the EU AI Act, OECD AI Principles, and NIST AI RMF into a unified operational lifecycle.',
    paloMapping: 'PolicyWatcher specifically maps onto several PALO lifecycle phases: it operates as a continuous **Deployment & Monitoring** tool (Phase 4) while its KPI framework draws from the **Ethical KPIs** paradigm that PALO advocates: converting abstract ethical principles into measurable, comparable metrics.',
    paloPhases: ['Ideation & Screening', 'Assessment & Planning', 'Dev & Validation', 'Deployment & Monitoring', 'Decommissioning'],
    paloPrinciples: ['Fairness & Non-Discrimination', 'Human Agency & Oversight', 'Transparency & Explainability', 'Societal & Environmental Well-being', 'Privacy & Data Governance'],
    paloVisit: 'Visit PALO Framework',
    selectionTitle: 'Company Selection Criteria',
    selectionDesc: 'The companies monitored by PolicyWatcher are selected based on 5 criteria:',
    selectionCriteria: [
      '**Large-Scale Impact**: Services with hundreds of millions or billions of active users, whose policy changes affect a significant portion of the global digital population.',
      '**AI Relevance**: Companies developing or integrating generative AI systems into their platforms, where data usage for model training is a critical concern.',
      '**Sensitive Data Exposure**: Platforms that collect sensitive data (financial, health, biometric, behavioral) requiring heightened regulatory scrutiny.',
      '**Regulatory Relevance**: Entities directly impacted by GDPR, EU AI Act, CCPA/CPRA, DORA, or other major data protection frameworks.',
      '**Sector Diversity**: Coverage across multiple industries (Tech, FinTech, Social Media, E-Commerce, AI Providers, Cloud/SaaS) to provide a broad comparative picture.'
    ],
    selectionNote: 'The monitored list is periodically expanded. Each policy analysis references a specific **snapshot version** and **date** to ensure traceability.',
    sourceTitle: 'Source Selection & Dataset QA Status',
    sourceDesc: 'PolicyWatcher treats source quality as a first-class control, not a cosmetic detail. The source-selection hierarchy is:\n\n1. **Global first**: when a company publishes a global or international English policy, that canonical source is used for Global analysis.\n2. **Market-specific when available**: EU, US, UK, or other market-level analyses must point to the official policy for that market, not a generic page.\n3. **Localized pages are not primary evidence by default**: translated URLs (for example `/it/`) are flagged unless they are the only official market source and the jurisdiction label makes that clear.\n4. **Traceability over convenience**: every policy links to the monitored URL, the stored snapshot, hash, and detected changes.\n5. **Admin quality gates**: Dataset QA checks URL hygiene, source-fit, hash integrity, freshness, AI JSON completeness, KPI coverage, regional-impact coverage, and subscriber hygiene before release decisions.',
    sourceSeal: 'The Dataset QA score is the operational seal of the platform: a low score means the dataset should be repaired before public claims are treated as reliable.',
    limitsTitle: 'Limitations & Disclaimer',
    limitsDesc1: 'BETA RELEASE: PolicyWatcher is in active development (beta) and does not represent a final product. The assessments are generated by AI models (Google Gemini) through automated text analysis. While we strive for accuracy, these evaluations:',
    limitsDesc2: '\u2022 May contain inaccuracies, interpretive errors, or omissions of legal language\n\u2022 Reflect a point-in-time analysis and may become outdated after the screening date\n\u2022 Do not constitute legal advice, compliance certification, or definitive assessment of corporate conduct\n\u2022 Are based solely on publicly available policy text and may not capture internal practices or confidential agreements\n\u2022 Should not be the basis for any legal, commercial, or compliance decision without independent verification',
    limitsDesc3: 'The author and the platform disclaim all liability for any decisions, actions, or omissions based on this information. The interpretation and use of the data presented are solely at the user\'s own risk and responsibility. Always verify with the original company documents and consult qualified legal professionals for compliance decisions.',
    legalTitle: 'Regulatory References',
    legalDesc: 'The following regulatory frameworks are referenced in PolicyWatcher\'s analysis. Each entry specifies the version and date of reference used:',
  },
  it: {
    title: 'Metodologia e Trasparenza',
    subtitle: 'Come PolicyWatcher valuta e classifica le policy aziendali',
    systemTitle: 'Panoramica del Sistema',
    systemDesc: 'PolicyWatcher utilizza una pipeline automatizzata multi-fase per monitorare, analizzare e classificare i documenti di policy aziendali. Il processo comprende:\n\n1. **Scraping & Hashing**: I documenti delle policy vengono periodicamente scaricati dagli URL ufficiali delle aziende. Ogni versione viene hashata (SHA-256) per rilevare le modifiche.\n2. **Rilevamento Differenze**: Quando viene rilevato un nuovo hash, il sistema salva un nuovo snapshot e identifica il delta tra le versioni.\n3. **Analisi AI (Gemini)**: Il delta testuale viene inviato a Google Gemini per l\'analisi in linguaggio naturale, generando punteggi di rischio, valutazioni KPI, sintesi esecutive e suggerimenti di remediation.\n4. **Filtro Regione e Prospettiva**: Ogni analisi è contestualizzata su 3 regioni (UE, USA, Globale) e 2 prospettive (Privato, Azienda).\n5. **Notifiche**: Gli iscritti vengono avvisati via email quando vengono rilevate modifiche significative.',
    riskTitle: 'Punteggio di Rischio Complessivo (1-10)',
    riskDesc: 'Ogni policy monitorata riceve un punteggio composito da 1 (molto sicura) a 10 (criticità rilevanti). Il punteggio riflette le pratiche di raccolta dati, la governance dell\'IA, la qualità del consenso, l\'allineamento normativo e i protocolli di notifica delle violazioni.',
    riskLow: 'Basso (1-3)',
    riskLowDesc: 'Forti protezioni utente, pratiche IA trasparenti, consenso esplicito, notifica rapida delle violazioni, risultati di audit pubblicati.',
    riskMedium: 'Medio (4-6)',
    riskMediumDesc: 'Protezioni parziali, alcune pratiche IA opache, flussi di consenso opt-out, conservazione dati moderata, divulgazione limitata a terzi.',
    riskHigh: 'Alto (7-10)',
    riskHighDesc: 'Raccolta dati estesa, pratiche di addestramento IA opache, conservazione indefinita, ampia condivisione con terzi, assenza di audit indipendenti.',
    riskRange: 'Intervallo',
    riskLabel: 'Etichetta',
    riskCriteria: 'Criteri Chiave',
    kpiTitle: 'I 15 KPI: Definizioni e Scala di Valori',
    kpiDesc: 'Ogni azienda viene valutata su 15 Indicatori Chiave di Prestazione raggruppati in tre aree. Il modello IA analizza il testo della policy e assegna uno dei tre valori standardizzati per KPI. Ecco la definizione completa di ciascun indicatore e il significato dei possibili valori:',
    kpiGroupPrivacy: 'Privacy e Protezione Dati',
    kpiGroupAiGov: 'Governance dell\'IA',
    kpiGroupEthics: 'Etica e Governance Aziendale',
    colorTitle: 'Legenda Codifica Cromatica',
    colorDesc: 'I colori dei badge utilizzati nella dashboard e nella matrice KPI seguono uno schema semaforico coerente:',
    colorGreen: 'Protettivo: La policy dimostra forti garanzie allineate alle migliori pratiche.',
    colorYellow: 'Parziale: Esistono alcune protezioni ma con lacune, limitazioni o modelli solo opt-out.',
    colorRed: 'Critico: Protezioni deboli o assenti che possono esporre gli utenti a rischi significativi.',
    colorGray: 'Non valutato: Dati insufficienti nel testo della policy per effettuare una determinazione.',
    paloTitle: 'Integrazione PALO Framework',
    paloDesc: 'La metodologia di PolicyWatcher è allineata al **PALO Framework** (Principled AI Lifecycle Orchestration), un modello di governance IA end-to-end sviluppato da Fabrizio Degni. PALO sintetizza ISO 42001, EU AI Act, Principi OCSE sull\'IA e NIST AI RMF in un ciclo di vita operativo unificato.',
    paloMapping: 'PolicyWatcher si inserisce specificamente in diverse fasi del ciclo di vita PALO: opera come strumento di **Deployment & Monitoring** continuo (Fase 4) mentre il suo framework KPI attinge dal paradigma dei **KPI Etici** che PALO promuove: convertendo principi etici astratti in metriche misurabili e comparabili.',
    paloPhases: ['Ideazione & Screening', 'Valutazione & Pianificazione', 'Sviluppo & Validazione', 'Deployment & Monitoraggio', 'Decommissioning'],
    paloPrinciples: ['Equità e Non-Discriminazione', 'Agenzia Umana e Supervisione', 'Trasparenza e Spiegabilità', 'Benessere Sociale e Ambientale', 'Privacy e Governance dei Dati'],
    paloVisit: 'Visita PALO Framework',
    selectionTitle: 'Criteri di Selezione delle Aziende',
    selectionDesc: 'Le aziende monitorate da PolicyWatcher sono selezionate in base a 5 criteri:',
    selectionCriteria: [
      '**Impatto su larga scala**: Servizi con centinaia di milioni o miliardi di utenti attivi, le cui modifiche di policy impattano una porzione significativa della popolazione digitale globale.',
      '**Rilevanza AI**: Aziende che sviluppano o integrano sistemi di IA generativa nelle proprie piattaforme, dove l\'uso dei dati per l\'addestramento dei modelli è una criticità centrale.',
      '**Esposizione a dati sensibili**: Piattaforme che raccolgono dati sensibili (finanziari, sanitari, biometrici, comportamentali) soggetti a scrutinio normativo rafforzato.',
      '**Rilevanza normativa**: Soggetti direttamente impattati da GDPR, EU AI Act, CCPA/CPRA, DORA o altri importanti framework di protezione dati.',
      '**Diversità settoriale**: Copertura di più industrie (Tech, FinTech, Social Media, E-Commerce, Provider AI, Cloud/SaaS) per un quadro comparativo ampio.'
    ],
    selectionNote: 'La lista è periodicamente ampliata. Ogni analisi di policy fa riferimento a una **versione snapshot** e una **data** specifiche per garantire la tracciabilità.',
    sourceTitle: 'Selezione Fonti e Stato QA Dataset',
    sourceDesc: 'PolicyWatcher considera la qualità della fonte un controllo primario, non un dettaglio estetico. La gerarchia di selezione è:\n\n1. **Global prima di tutto**: quando l’azienda pubblica una policy globale o internazionale in inglese, quella fonte canonica viene usata per l’analisi Global.\n2. **Mercato specifico quando disponibile**: analisi EU, US, UK o di altri mercati devono puntare alla policy ufficiale di quel mercato, non a una pagina generica.\n3. **Le pagine localizzate non sono prova primaria di default**: URL tradotti, ad esempio `/it/`, vengono segnalati salvo siano l’unica fonte ufficiale di mercato e la giurisdizione lo renda chiaro.\n4. **Tracciabilità sopra la comodità**: ogni policy mantiene URL monitorato, snapshot salvato, hash e modifiche rilevate.\n5. **Quality gate amministrativi**: Dataset QA verifica igiene URL, source-fit, integrità hash, freschezza, completezza JSON AI, copertura KPI, copertura impatti regionali e igiene subscriber prima delle decisioni di rilascio.',
    sourceSeal: 'Il punteggio Dataset QA è il sigillo operativo della piattaforma: se è basso, il dataset va corretto prima che le valutazioni pubbliche siano considerate affidabili.',
    limitsTitle: 'Limitazioni e Disclaimer',
    limitsDesc1: 'BETA RELEASE: PolicyWatcher e in fase di sviluppo (beta) e non rappresenta un prodotto finale. Le valutazioni sono generate da modelli IA (Google Gemini) tramite analisi testuale automatizzata. Pur impegnandoci per l\'accuratezza, queste valutazioni:',
    limitsDesc2: '\u2022 Possono contenere imprecisioni, errori interpretativi o omissioni del linguaggio giuridico\n\u2022 Riflettono un\'analisi a un momento specifico e possono diventare obsolete dopo la data di screening\n\u2022 Non costituiscono consulenza legale, certificazione di conformita o valutazione definitiva della condotta aziendale\n\u2022 Si basano esclusivamente su testo di policy pubblicamente disponibile e potrebbero non catturare pratiche interne o accordi riservati\n\u2022 Non devono essere alla base di alcuna decisione legale, commerciale o di conformita senza verifica indipendente',
    limitsDesc3: 'L\'autore e la piattaforma declinano qualsiasi responsabilita per decisioni, azioni o omissioni basate su queste informazioni. L\'interpretazione e l\'uso dei dati presentati sono esclusivamente a rischio e responsabilita dell\'utente. Verificare sempre direttamente con i documenti ufficiali e consultare professionisti legali qualificati per le decisioni di conformita.',
    legalTitle: 'Riferimenti Normativi',
    legalDesc: 'I seguenti framework normativi sono referenziati nell\'analisi di PolicyWatcher. Ogni voce specifica la versione e la data di riferimento utilizzata:',
  }
};

const legalFrameworks = [
  {
    name: 'GDPR',
    version: 'Regulation (EU) 2016/679',
    date: '2018-05-25',
    url: 'https://eur-lex.europa.eu/eli/reg/2016/679/oj',
    desc: {
      en: 'General Data Protection Regulation: EU baseline for personal data processing, consent, data subject rights, and cross-border transfers.',
      it: 'Regolamento Generale sulla Protezione dei Dati: Base UE per il trattamento dei dati personali, consenso, diritti degli interessati e trasferimenti transfrontalieri.'
    }
  },
  {
    name: 'CCPA / CPRA',
    version: 'Cal. Civ. Code §§ 1798.100–1798.199.100 (as amended by CPRA, Prop. 24)',
    date: '2023-01-01',
    url: 'https://oag.ca.gov/privacy/ccpa',
    desc: {
      en: 'California Consumer Privacy Act & California Privacy Rights Act: US state-level privacy regulation covering data sale opt-out, deletion rights, and automated decision-making.',
      it: 'California Consumer Privacy Act e California Privacy Rights Act: Regolamentazione privacy a livello statale USA: opt-out vendita dati, diritto alla cancellazione, decisioni automatizzate.'
    }
  },
  {
    name: 'EU AI Act',
    version: 'Regulation (EU) 2024/1689',
    date: '2024-08-01',
    url: 'https://eur-lex.europa.eu/eli/reg/2024/1689/oj',
    desc: {
      en: 'EU Artificial Intelligence Act: Risk-based framework for AI system regulation. Key articles referenced: Art. 6 (risk classification), Art. 9 (risk management), Art. 13 (transparency), Art. 27 (FRIA).',
      it: 'EU AI Act: Quadro basato sul rischio per la regolazione dei sistemi IA. Articoli chiave: Art. 6 (classificazione rischio), Art. 9 (gestione rischio), Art. 13 (trasparenza), Art. 27 (FRIA).'
    }
  },
  {
    name: 'DORA',
    version: 'Regulation (EU) 2022/2554',
    date: '2025-01-17',
    url: 'https://eur-lex.europa.eu/eli/reg/2022/2554/oj',
    desc: {
      en: 'Digital Operational Resilience Act: ICT risk management framework for financial entities. Relevant for FinTech companies in the monitored portfolio.',
      it: 'Digital Operational Resilience Act: Framework di gestione rischi ICT per entità finanziarie. Rilevante per le aziende FinTech nel portafoglio monitorato.'
    }
  },
  {
    name: 'NIST AI RMF',
    version: 'NIST AI 100-1 (v1.0)',
    date: '2023-01-26',
    url: 'https://www.nist.gov/artificial-intelligence/executive-order-safe-secure-and-trustworthy-ai',
    desc: {
      en: 'NIST AI Risk Management Framework: US voluntary framework for trustworthy AI. Referenced for Govern, Map, Measure, and Manage functions.',
      it: 'NIST AI Risk Management Framework: Framework volontario USA per IA affidabile. Utilizzato per le funzioni Govern, Map, Measure e Manage.'
    }
  },
  {
    name: 'ISO/IEC 42001',
    version: 'ISO/IEC 42001:2023',
    date: '2023-12-18',
    url: 'https://www.iso.org/standard/81230.html',
    desc: {
      en: 'AI Management System standard: Requirements for establishing, implementing, and improving an AI management system within organizations.',
      it: 'Standard per il Sistema di Gestione dell\'IA: Requisiti per istituire, implementare e migliorare un sistema di gestione IA nelle organizzazioni.'
    }
  },
  {
    name: 'OECD AI Principles',
    version: 'OECD/LEGAL/0449 (revised 2024)',
    date: '2024-05-03',
    url: 'https://oecd.ai/en/ai-principles',
    desc: {
      en: 'OECD Recommendation on AI: International guidelines for trustworthy AI, adopted by 46 countries. Updated in 2024 to address generative AI.',
      it: 'Raccomandazione OCSE sull\'IA: Linee guida internazionali per IA affidabile, adottate da 46 paesi. Aggiornate nel 2024 per l\'IA generativa.'
    }
  },
  {
    name: 'PALO Framework',
    version: 'v2.0 (incl. PALO-AM Agentic Module)',
    date: '2026-06-01',
    url: 'https://www.paloframework.org',
    desc: {
      en: 'Principled AI Lifecycle Orchestration: End-to-end AI governance model by Fabrizio Degni integrating ISO 42001, EU AI Act, OECD, and NIST AI RMF.',
      it: 'Principled AI Lifecycle Orchestration: Modello di governance IA end-to-end di Fabrizio Degni che integra ISO 42001, EU AI Act, OCSE e NIST AI RMF.'
    }
  },
];

// ─── Render helpers ───────────────────────────────────────────────────────────

function renderMarkdown(text: string) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i}>{part.slice(2, -2)}</strong>;
    }
    return part;
  });
}

// ─── Component ────────────────────────────────────────────────────────────────

export default function MethodologyModal({ isOpen, onClose, lang }: MethodologyModalProps) {
  const t = content[lang];
  const privacyKPIs = kpiDefinitions.filter(k => k.group === 'privacy');
  const aiGovKPIs = kpiDefinitions.filter(k => k.group === 'aiGov');
  const ethicsKPIs = kpiDefinitions.filter(k => k.group === 'ethics');

  const renderKPIGroup = (kpis: KPIDef[], groupLabel: string, iconClass: string, icon: React.ReactNode) => (
    <div className={styles.kpiGroup}>
      <div className={styles.kpiGroupTitle}>
        {icon} {groupLabel}
      </div>
      {kpis.map(kpi => (
        <div key={kpi.key} className={styles.kpiCard}>
          <div className={styles.kpiName}>{lang === 'en' ? kpi.nameEn : kpi.nameIt}</div>
          <div className={styles.kpiDescription}>{lang === 'en' ? kpi.descEn : kpi.descIt}</div>
          <div className={styles.kpiValues}>
            {kpi.values.map((v, i) => (
              <span key={i} className={`${styles.kpiValueBadge} ${styles[v.color]}`}>
                {v.color === 'green' ? '●' : v.color === 'yellow' ? '●' : '●'} {v.label}
              </span>
            ))}
          </div>
        </div>
      ))}
    </div>
  );

  return (
    <AnimatePresence>
      {isOpen && (
        <>
          <motion.div
            className={styles.backdrop}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            onClick={onClose}
          />
          <motion.div
            className={styles.modal}
            initial={{ opacity: 0, scale: 0.95, x: "-50%", y: "-45%" }}
            animate={{ opacity: 1, scale: 1, x: "-50%", y: "-50%" }}
            exit={{ opacity: 0, scale: 0.95, x: "-50%", y: "-45%" }}
            transition={{ type: 'spring', damping: 25, stiffness: 300 }}
          >
            <button className={styles.closeBtn} onClick={onClose} aria-label="Close">
              <X size={20} />
            </button>

            {/* Header */}
            <div className={styles.header}>
              <div className={styles.headerIcon}>
                <BookOpen size={24} />
              </div>
              <h2>{t.title}</h2>
              <p className={styles.headerSubtitle}>{t.subtitle}</p>
            </div>

            {/* Body */}
            <div className={styles.body}>

              {/* 1. System Overview */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.system}`}><Layers size={16} /></span>
                {t.systemTitle}
              </div>
              <div className={styles.sectionDescription}>
                {t.systemDesc.split('\n').map((line, i) => (
                  <span key={i}>{renderMarkdown(line)}{i < t.systemDesc.split('\n').length - 1 && <br />}</span>
                ))}
              </div>

              <hr className={styles.divider} />

              {/* 2. Risk Score */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.risk}`}><Gauge size={16} /></span>
                {t.riskTitle}
              </div>
              <p className={styles.sectionDescription}>{t.riskDesc}</p>
              <table className={styles.riskTable}>
                <thead>
                  <tr>
                    <th>{t.riskRange}</th>
                    <th>{t.riskLabel}</th>
                    <th>{t.riskCriteria}</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td><span className={`${styles.kpiValueBadge} ${styles.green}`}>1 – 3</span></td>
                    <td>{t.riskLow}</td>
                    <td>{t.riskLowDesc}</td>
                  </tr>
                  <tr>
                    <td><span className={`${styles.kpiValueBadge} ${styles.yellow}`}>4 – 6</span></td>
                    <td>{t.riskMedium}</td>
                    <td>{t.riskMediumDesc}</td>
                  </tr>
                  <tr>
                    <td><span className={`${styles.kpiValueBadge} ${styles.red}`}>7 – 10</span></td>
                    <td>{t.riskHigh}</td>
                    <td>{t.riskHighDesc}</td>
                  </tr>
                </tbody>
              </table>

              <hr className={styles.divider} />

              {/* 3. KPI Definitions */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.privacy}`}><Activity size={16} /></span>
                {t.kpiTitle}
              </div>
              <p className={styles.sectionDescription}>{t.kpiDesc}</p>

              {renderKPIGroup(privacyKPIs, lang === 'en' ? 'Privacy & Data Protection' : 'Privacy e Protezione Dati', 'privacy', <Shield size={16} />)}
              {renderKPIGroup(aiGovKPIs, lang === 'en' ? 'AI Governance' : 'Governance dell\'IA', 'aiGov', <Brain size={16} />)}
              {renderKPIGroup(ethicsKPIs, lang === 'en' ? 'Ethics & Corporate Governance' : 'Etica e Governance Aziendale', 'ethics', <Scale size={16} />)}

              <hr className={styles.divider} />

              {/* 4. Color Coding */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.color}`}><Eye size={16} /></span>
                {t.colorTitle}
              </div>
              <p className={styles.sectionDescription}>{t.colorDesc}</p>
              <div className={styles.colorLegend}>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.green}`} />
                  <div>
                    <div className={styles.legendLabel}>Green</div>
                    <div className={styles.legendDesc}>{t.colorGreen}</div>
                  </div>
                </div>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.yellow}`} />
                  <div>
                    <div className={styles.legendLabel}>Yellow</div>
                    <div className={styles.legendDesc}>{t.colorYellow}</div>
                  </div>
                </div>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.red}`} />
                  <div>
                    <div className={styles.legendLabel}>Red</div>
                    <div className={styles.legendDesc}>{t.colorRed}</div>
                  </div>
                </div>
                <div className={styles.legendItem}>
                  <div className={`${styles.legendDot} ${styles.muted}`} />
                  <div>
                    <div className={styles.legendLabel}>Gray</div>
                    <div className={styles.legendDesc}>{t.colorGray}</div>
                  </div>
                </div>
              </div>

              <hr className={styles.divider} />

              {/* 5. PALO Framework */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.palo}`}><Shield size={16} /></span>
                {t.paloTitle}
              </div>
              <div className={styles.paloCard}>
                <div className={styles.paloHeader}>
                  <div className={styles.paloLogo}>PALO</div>
                  <div>
                    <div className={styles.paloTitle}>PALO Framework</div>
                    <div className={styles.paloSubtitle}>Principled AI Lifecycle Orchestration</div>
                  </div>
                </div>
                <p className={styles.paloDescription}>{renderMarkdown(t.paloDesc)}</p>
                
                <div className={styles.paloPhases}>
                  {t.paloPhases.map((phase, i) => (
                    <div key={i} className={styles.paloPhase}>
                      <div className={styles.paloPhaseNum}>{lang === 'en' ? `Phase ${i + 1}` : `Fase ${i + 1}`}</div>
                      <div className={styles.paloPhaseName}>{phase}</div>
                    </div>
                  ))}
                </div>

                <div className={styles.paloPrinciples}>
                  {t.paloPrinciples.map((p, i) => (
                    <span key={i} className={styles.paloPrinciple}>{p}</span>
                  ))}
                </div>

                <p className={styles.paloMappingNote}>{renderMarkdown(t.paloMapping)}</p>

                <a 
                  href="https://www.paloframework.org" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className={styles.paloLink}
                >
                  <ExternalLink size={16} />
                  {t.paloVisit}
                </a>
              </div>

              <hr className={styles.divider} />

              {/* 6. Limitations */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.limits}`}><AlertTriangle size={16} /></span>
                {t.limitsTitle}
              </div>
              <div className={styles.disclaimerCard}>
                <p>{t.limitsDesc1}</p>
                <p>{t.limitsDesc2.split('\n').map((line, i) => (
                  <span key={i}>{line}<br /></span>
                ))}</p>
                <p><strong>{t.limitsDesc3}</strong></p>
              </div>

              <hr className={styles.divider} />

              {/* 7. Selection Criteria */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.system}`}><Target size={16} /></span>
                {t.selectionTitle}
              </div>
              <p className={styles.sectionDescription}>{t.selectionDesc}</p>
              <div className={styles.disclaimerCard}>
                {t.selectionCriteria.map((criterion, i) => (
                  <p key={i} style={{ margin: '6px 0' }}>{renderMarkdown(`${i + 1}. ${criterion}`)}</p>
                ))}
                <p style={{ marginTop: 12, fontStyle: 'italic' }}>{renderMarkdown(t.selectionNote)}</p>
              </div>

              <hr className={styles.divider} />

              {/* 8. Source Quality */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.privacy}`}><CheckCircle size={16} /></span>
                {t.sourceTitle}
              </div>
              <div className={styles.disclaimerCard}>
                {t.sourceDesc.split('\n').map((line, i) => (
                  <span key={i}>{renderMarkdown(line)}{i < t.sourceDesc.split('\n').length - 1 && <br />}</span>
                ))}
                <p style={{ marginTop: 12 }}>
                  <strong>{t.sourceSeal}</strong>
                </p>
              </div>

              <hr className={styles.divider} />

              {/* 9. Legal References (versioned) */}
              <div className={styles.sectionTitle}>
                <span className={`${styles.sectionTitleIcon} ${styles.legal}`}><Scale size={16} /></span>
                {t.legalTitle}
              </div>
              <p className={styles.sectionDescription}>{t.legalDesc}</p>
              <ul className={styles.standardsList}>
                {legalFrameworks.map((fw, i) => (
                  <li key={i}>
                    <Scale size={14} className={styles.standardsIcon} />
                    <div>
                      <div><strong>{fw.name}</strong>: {lang === 'en' ? fw.desc.en : fw.desc.it}</div>
                      <div style={{ fontSize: '0.78rem', color: '#888', marginTop: 3 }}>
                        {lang === 'en' ? 'Ref.' : 'Rif.'}: <em>{fw.version}</em>: {lang === 'en' ? 'Effective' : 'In vigore dal'}: {fw.date}
                        {' · '}
                        <a href={fw.url} target="_blank" rel="noopener noreferrer" style={{ color: '#6366f1', textDecoration: 'none' }}>
                          {lang === 'en' ? 'Official text ↗' : 'Testo ufficiale ↗'}
                        </a>
                      </div>
                    </div>
                  </li>
                ))}
              </ul>

            </div>
          </motion.div>
        </>
      )}
    </AnimatePresence>
  );
}
