/**
 * @file PolicyDetails.tsx
 *
 * Full-width slide-over panel that shows the complete details for a single
 * monitored policy document.
 *
 * The panel is organised into five tabs:
 *  1. **Overview & Diffs** — AI summary (TL;DR + key points), regional
 *     regulatory impact cards, and a textual diff of the latest change.
 *  2. **Version Archive** — expandable accordion of all historical snapshots
 *     with full-text view and clipboard copy.
 *  3. **AI Governance** — scorecard for AI-specific data-usage terms.
 *  4. **Risk Trends** — historical risk score line chart + risk-profile bars.
 *  5. **Remediations** — actionable remediation steps generated by Gemini.
 *
 * Includes a "Scan & Update" button that triggers a live scrape of the
 * original policy URL via `/api/scrape`, followed by a data refresh.
 *
 * Supports EN/IT localisation.
 */
'use client';

import { useState, useEffect, useCallback } from 'react';
import {
  X,
  Clock,
  FileText,
  TrendingUp,
  RefreshCw,
  ExternalLink,
  Shield,
  AlertTriangle,
  CheckCircle,
  FileDiff,
  Activity,
  Award,
  Copy,
  Info,
  Archive,
  ChevronDown,
  ChevronUp,
  Share2,
  FileDown,
  Globe,
} from 'lucide-react';
import styles from './PolicyDetails.module.css';
import type { Policy, PolicyChange, Company, RegionImpact } from '@/types/index';
import AISummary from '@/components/ai/AISummary';
import RiskReasons from '@/components/ai/RiskReasons';
import RemediationSteps from '@/components/ai/RemediationSteps';
import RiskTrendPanel from '@/components/charts/RiskTrendPanel';
import RegionHeatMap from '@/components/charts/RegionHeatMap';

/** Props for the {@link PolicyDetails} slide-over panel. */
interface PolicyDetailsProps {
  /** Database ID of the policy to display. */
  policyId: string;
  /** Dismiss callback. */
  onClose: () => void;
  /** Currently selected regulatory region — used to highlight the matching impact card. */
  selectedRegion: 'EU' | 'US' | 'Global';
  /** Currently selected audience perspective. */
  selectedPerspective: 'Individual' | 'Enterprise';
  /** Called after a successful scrape to refresh the parent dashboard data. */
  onDataRefresh: () => void;
  /** Active UI language. */
  lang: 'en' | 'it';
}

/**
 * Extended policy object returned by `/api/policies/:id`.
 * Includes nested company, ordered snapshots, and change history.
 */
interface FullPolicyDetails extends Policy {
  /** Parent company record. */
  company: Company;
  /** All monitored documents for this company (including self). */
  siblingPolicies?: SiblingPolicy[];
  /** Ordered list of scraped snapshots (newest first). */
  snapshots: {
    id: string;
    version: number;
    text: string;
    /** SHA-256 hash used for change detection. */
    hash: string;
    createdAt: string;
  }[];
  /** Change records linking consecutive snapshots. */
  changes: (PolicyChange & {
    oldSnapshot: { id: string; version: number } | null;
    newSnapshot: { id: string; version: number };
    regionImpacts: RegionImpact[];
  })[];
}

/** A single actionable remediation step parsed from the AI-generated JSON. */
interface Remediation {
  titleEn: string;
  titleIt: string;
  descriptionEn: string;
  descriptionIt: string;
  /** Optional deep-link to the relevant settings page or documentation. */
  actionUrl?: string;
  actionTextEn?: string;
  actionTextIt?: string;
}

/** Union of tab identifiers for the detail panel's navigation. */
/** A sibling policy belonging to the same company, used in the Sources tab. */
interface SiblingPolicy {
  id: string;
  name: string;
  type: string;
  url: string;
  jurisdiction: string;
  currentHash: string;
  updatedAt: string;
  snapshots: { version: number; createdAt: string }[];
}

/** Union of tab identifiers for the detail panel's navigation. */
type TabType = 'changes' | 'aiGov' | 'trends' | 'remediations' | 'archive' | 'sources';

/**
 * Slide-over detail panel for a single monitored policy.
 *
 * Displays the full change history, AI governance scorecard, risk trend
 * charts, and remediation advice for the selected policy document.
 *
 * @param props - {@link PolicyDetailsProps}
 * @returns The panel overlay with tabbed content.
 */
export default function PolicyDetails({ 
  policyId, 
  onClose, 
  selectedRegion, 
  selectedPerspective,
  lang
}: PolicyDetailsProps) {
  const [policy, setPolicy] = useState<FullPolicyDetails | null>(null);
  const [loading, setLoading] = useState(true);
  const [copied, setCopied] = useState(false);
  const [closing, setClosing] = useState(false);
  const [activeTab, setActiveTab] = useState<TabType>('changes');
  const [activeChangeIndex, setActiveChangeIndex] = useState<number>(0);
  const [expandedSnapshot, setExpandedSnapshot] = useState<string | null>(null);
  const [copiedSnapshotId, setCopiedSnapshotId] = useState<string | null>(null);

  const handleClose = useCallback(() => {
    setClosing(true);
    setTimeout(() => onClose(), 250);
  }, [onClose]);

  const fetchPolicyDetails = useCallback(async () => {
    setLoading(true);
    try {
      const res = await fetch(`/api/policies/${policyId}`);
      if (res.ok) {
        const data = await res.json();
        setPolicy(data);
        setActiveChangeIndex(0);
      }
    } catch (error) {
      console.error('Error fetching policy details:', error);
    } finally {
      setLoading(false);
    }
  }, [policyId]);

  useEffect(() => {
    queueMicrotask(() => {
      void fetchPolicyDetails();
    });
  }, [fetchPolicyDetails]);

  // Escape key to close
  useEffect(() => {
    const handleEsc = (e: KeyboardEvent) => {
      if (e.key === 'Escape') handleClose();
    };
    window.addEventListener('keydown', handleEsc);
    return () => window.removeEventListener('keydown', handleEsc);
  }, [handleClose]);


  const copyToClipboard = () => {
    if (!policy) return;
    navigator.clipboard.writeText(policy.url);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  if (loading) {
    return (
      <div className={styles.overlay} onClick={handleClose}>
        <div className={styles.panel} onClick={(e) => e.stopPropagation()} style={{ justifyContent: 'center', alignItems: 'center' }}>
          <RefreshCw className="animate-spin" size={40} color="var(--primary)" />
        </div>
      </div>
    );
  }

  if (!policy) return null;

  const activeChange = policy.changes[activeChangeIndex];

  /**
   * Parses the JSON diff string and renders it as a styled inline diff.
   * Added chunks are highlighted green, removed chunks red.
   */
  const renderDiffContent = (diffJson: string) => {
    try {
      const diffArray = JSON.parse(diffJson) as { value: string; added?: boolean; removed?: boolean }[];
      return diffArray.map((chunk, index) => {
        let lineClass = styles.diffUnchanged;
        if (chunk.added) lineClass = styles.diffAdded;
        if (chunk.removed) lineClass = styles.diffRemoved;

        return (
          <span key={index} className={`${styles.diffLine} ${lineClass}`}>
            {chunk.added ? '+ ' : chunk.removed ? '- ' : '  '}
            {chunk.value}
          </span>
        );
      });
    } catch {
      return <pre style={{ color: 'var(--text-muted)' }}>{diffJson}</pre>;
    }
  };

  const getRiskColor = (risk: string) => {
    if (risk === 'High') return 'var(--risk-high)';
    if (risk === 'Medium') return 'var(--risk-medium)';
    return 'var(--risk-low)';
  };

  const getRiskIcon = (risk: string) => {
    if (risk === 'High') return <AlertTriangle size={16} color="var(--risk-high)" />;
    if (risk === 'Medium') return <AlertTriangle size={16} color="var(--risk-medium)" />;
    return <CheckCircle size={16} color="var(--risk-low)" />;
  };

  const getRiskBadgeClass = (risk: string) => {
    if (risk === 'High') return 'badge-high';
    if (risk === 'Medium') return 'badge-medium';
    return 'badge-low';
  };

  const getRemediations = (): Remediation[] => {
    if (!activeChange?.remediationsJson) return [];
    try {
      return JSON.parse(activeChange.remediationsJson);
    } catch {
      return [];
    }
  };

  /**
   * Maps a human-readable AI governance value to a numeric risk percentage.
   * Used to build the "Active Risk Profile Vectors" bar chart.
   * Higher values indicate higher risk.
   */
  const getIndicatorScore = (value: string): number => {
    const riskMap: Record<string, number> = {
      'Not Allowed': 90, 'Claimed by company': 85, 'Indefinite': 80,
      'Permitted': 75, 'Not specified': 60,
      'Opt-out available': 45, 'Shared': 40, '30 days': 35,
      'Restricted': 20, 'Protected': 15, 'Allowed': 10, 'System-deleted': 10,
    };
    return riskMap[value] || 50;
  };

  const riskProfileData = activeChange ? [
    { 
      labelEn: 'Data Privacy', labelIt: 'Privacy Dati', 
      value: getIndicatorScore(activeChange.aiTrainingOptOut) 
    },
    { 
      labelEn: 'AI Consent', labelIt: 'Consenso AI', 
      value: getIndicatorScore(activeChange.aiDataScrapingRestricted) 
    },
    { 
      labelEn: 'IP Rights', labelIt: 'Diritti IP', 
      value: getIndicatorScore(activeChange.aiIpLicensing) 
    },
    { 
      labelEn: 'Data Retention', labelIt: 'Conservazione', 
      value: getIndicatorScore(activeChange.aiPromptRetention) 
    },
  ] : [];

  const getBarColor = (value: number) => {
    if (value > 70) return 'var(--risk-high)';
    if (value > 40) return 'var(--risk-medium)';
    return 'var(--risk-low)';
  };

  // TL;DR text used for the native share sheet
  const tldrShare =
    (lang === 'it'
      ? activeChange?.tldrIt || activeChange?.aiSummaryIt
      : activeChange?.tldrEn || activeChange?.aiSummaryEn) || '';

  return (
    <div className={styles.overlay} onClick={handleClose} role="dialog" aria-modal="true" aria-label={`${policy.company.name} - ${policy.name}`}>
      <div className={`${styles.panel} ${closing ? styles.panelClosing : ''}`} onClick={(e) => e.stopPropagation()}>
        {/* Header */}
        <div className={styles.header}>
          <div className={styles.titleArea}>
            <h2 className={styles.title}>{policy.company.name}</h2>
            <span className={styles.subtitle}>
              <FileText size={16} /> {policy.name}
              <span className={styles.jurisdictionTag}>{policy.jurisdiction}</span>
            </span>
          </div>
          <div className={styles.headerActions}>
            <button onClick={handleClose} className={styles.closeBtn} aria-label="Close">
              <X size={20} />
            </button>
          </div>
        </div>

        {/* Policy Link Section */}
        <div className={styles.linkSection}>
          <span className={styles.linkLabel}>
            {lang === 'it' ? 'Link Ufficiale Documento:' : 'Official Policy Document Link:'}
          </span>
          <div className={styles.linkInputWrapper}>
            <input type="text" readOnly value={policy.url} className={styles.linkInput} />
            <button onClick={copyToClipboard} className={styles.copyBtn} aria-label="Copy URL">
              {copied ? (lang === 'it' ? 'Copiato!' : 'Copied!') : <Copy size={14} />}
            </button>
            <a href={policy.url} target="_blank" rel="noreferrer" className={styles.copyBtn} aria-label="Open in new tab">
              <ExternalLink size={14} />
            </a>
          </div>
        </div>

        {/* Share + PDF actions */}
        <div className={styles.shareRow}>
          <a
            href={`/api/report/${policy.id}?lang=${lang}`}
            target="_blank"
            rel="noreferrer"
            className={styles.shareBtn}
          >
            <FileDown size={14} />
            {lang === 'it' ? 'Report PDF' : 'PDF Report'}
          </a>
          <button
            onClick={async () => {
              const shareUrl = `${window.location.origin}/share/${policy.id}?lang=${lang}`;
              try {
                if (navigator.share) {
                  await navigator.share({
                    title: `${policy.company.name}: PolicyWatcher`,
                    text: tldrShare,
                    url: shareUrl,
                  });
                } else {
                  await navigator.clipboard.writeText(shareUrl);
                  setCopied(true);
                  setTimeout(() => setCopied(false), 1800);
                }
              } catch {
                /* user cancelled */
              }
            }}
            className={styles.shareBtn}
          >
            <Share2 size={14} />
            {copied
              ? lang === 'it' ? 'Link copiato!' : 'Link copied!'
              : lang === 'it' ? 'Condividi' : 'Share'}
          </button>
        </div>

        {/* Last Verified Indicator */}
        <div className={styles.actionsBar}>
          <div className={styles.actionText} style={{ display: 'flex', alignItems: 'center', gap: 8, width: '100%' }}>
            <Clock size={14} style={{ opacity: 0.7 }} />
            <span>
              {lang === 'it' ? 'Ultima verifica: ' : 'Last verified: '}
              <strong>
                {policy.updatedAt
                  ? new Date(policy.updatedAt).toLocaleDateString(
                      lang === 'it' ? 'it-IT' : 'en-US',
                      { day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit' }
                    )
                  : lang === 'it' ? 'In attesa di scansione' : 'Pending scan'}
              </strong>
            </span>
          </div>
        </div>

        {/* Timeline */}
        {policy.changes.length > 0 && (
          <div>
            <h3 className={styles.sectionTitle}>
              <Clock size={18} /> {lang === 'it' ? 'Cronologia Modifiche' : 'Version Updates Timeline'} ({policy.changes.length})
            </h3>
            <div className={styles.timelineWrapper}>
              {policy.changes.map((change, idx) => {
                const date = new Date(change.createdAt).toLocaleDateString(lang === 'it' ? 'it-IT' : 'en-US', { day: 'numeric', month: 'short', year: 'numeric' });
                const isSelected = idx === activeChangeIndex;
                const vText = change.oldSnapshot 
                  ? `V${change.oldSnapshot.version} > V${change.newSnapshot.version}`
                  : `${lang === 'it' ? 'Iniziale' : 'Initial'} V${change.newSnapshot.version}`;

                return (
                  <div 
                    key={change.id}
                    onClick={() => setActiveChangeIndex(idx)}
                    className={`${styles.timelineItem} ${isSelected ? styles.timelineItemActive : ''}`}
                  >
                    <span className={styles.versionTitle}>{vText}</span>
                    <span className={styles.versionDate}>{date}</span>
                    <span className={`badge ${getRiskBadgeClass(change.overallRisk)}`} style={{ fontSize: '0.6rem', padding: '1px 6px', marginTop: '4px' }}>
                      {change.overallRisk}
                    </span>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* Tabs */}
        <nav className={styles.tabContainer} role="tablist">
          {([
            { key: 'changes' as TabType, icon: <FileDiff size={16} />, labelEn: 'Overview & Diffs', labelIt: 'Panoramica & Diffs' },
            { key: 'archive' as TabType, icon: <Archive size={16} />, labelEn: `Version Archive (${policy.snapshots.length})`, labelIt: `Archivio Versioni (${policy.snapshots.length})` },
            { key: 'aiGov' as TabType, icon: <Shield size={16} />, labelEn: 'AI Governance', labelIt: 'Governance AI' },
            { key: 'trends' as TabType, icon: <Activity size={16} />, labelEn: 'Risk Trends', labelIt: 'Grafici Evolutivi' },
            { key: 'remediations' as TabType, icon: <Award size={16} />, labelEn: 'Remediations', labelIt: 'Piano d\'Azione' },
            { key: 'sources' as TabType, icon: <Globe size={16} />, labelEn: `Sources (${policy.siblingPolicies?.length || 0})`, labelIt: `Fonti (${policy.siblingPolicies?.length || 0})` },
          ]).map((tab) => (
            <button 
              key={tab.key}
              onClick={() => setActiveTab(tab.key)} 
              className={`${styles.tabButton} ${activeTab === tab.key ? styles.tabButtonActive : ''}`}
              role="tab"
              aria-selected={activeTab === tab.key}
            >
              {tab.icon} {lang === 'it' ? tab.labelIt : tab.labelEn}
            </button>
          ))}
        </nav>

        {activeChange ? (
          <div className={styles.tabContent}>
            {/* TAB 1: OVERVIEW & DIFFS */}
            {activeTab === 'changes' && (
              <div>
                <div className={styles.summaryBox}>
                  <h3 className={styles.sectionTitle} style={{ marginBottom: '8px' }}>
                    <TrendingUp size={18} color="var(--primary)" /> {lang === 'it' ? 'Sintesi AI del Cambiamento' : 'AI Executive Summary'}
                  </h3>
                  <AISummary
                    tldrEn={activeChange.tldrEn}
                    tldrIt={activeChange.tldrIt}
                    keyPointsJson={activeChange.keyPointsJson}
                    legacySummaryEn={activeChange.aiSummaryEn}
                    legacySummaryIt={activeChange.aiSummaryIt}
                    lang={lang}
                  />
                  <div style={{ marginTop: '14px' }}>
                    <RiskReasons
                      riskReasonsJson={activeChange.riskReasonsJson}
                      lang={lang}
                    />
                  </div>
                </div>

                <h3 className={styles.sectionTitle}>
                  <Shield size={18} /> {lang === 'it' ? 'Valutazione d\'Impatto Normativo' : 'Regional Regulatory Assessment'}
                </h3>
                <div className={styles.heatMapWrap}>
                  <RegionHeatMap
                    regionImpacts={activeChange.regionImpacts}
                    lang={lang}
                  />
                </div>
                <div className={styles.impactsGrid}>
                  {activeChange.regionImpacts.map((impact) => {
                    const isSelectedContext = 
                      impact.region === selectedRegion && impact.perspective === selectedPerspective;

                    return (
                      <div 
                        key={impact.id}
                        className={`${styles.impactCard} ${isSelectedContext ? styles.impactCardActive : ''}`}
                        style={{ borderLeft: `3px solid ${getRiskColor(impact.riskLevel)}` }}
                      >
                        <div className={styles.impactHeader}>
                          <span className={styles.impactRegion}>
                            {impact.region === 'EU' ? (lang === 'it' ? 'Europa (EU)' : 'Europe (EU)') : impact.region === 'US' ? 'United States (US)' : 'Global'} / {impact.perspective === 'Individual' ? (lang === 'it' ? 'Privato' : 'Individual') : (lang === 'it' ? 'Azienda' : 'Enterprise')}
                          </span>
                          <span className={`badge ${getRiskBadgeClass(impact.riskLevel)}`} style={{ fontSize: '0.65rem' }}>
                            {getRiskIcon(impact.riskLevel)} {impact.riskLevel}
                          </span>
                        </div>
                        
                        <p className={styles.impactText}>
                          {lang === 'it' ? impact.impactAnalysisIt : impact.impactAnalysisEn}
                        </p>
                        
                        {(lang === 'it' ? impact.complianceNoteIt : impact.complianceNoteEn) && (
                          <div className={styles.complianceNote}>
                            <CheckCircle size={12} /> {lang === 'it' ? impact.complianceNoteIt : impact.complianceNoteEn}
                          </div>
                        )}
                      </div>
                    );
                  })}
                </div>

                <h3 className={styles.sectionTitle}>
                  <FileDiff size={18} /> {lang === 'it' ? 'Dettaglio Differenze Testo' : 'Text Differences (Diff)'}
                </h3>
                <div className={styles.diffContainer}>
                  {renderDiffContent(activeChange.diff)}
                </div>
              </div>
            )}

            {/* TAB 2: AI GOVERNANCE SCORECARD */}
            {activeTab === 'aiGov' && (
              <div>
                <h3 className={styles.sectionTitle}>
                  <Shield size={18} color="var(--secondary)" /> {lang === 'it' ? 'AI Governance & IA Dati Scorecard' : 'AI Governance & Data Safety Scorecard'}
                </h3>
                
                <div className={styles.govGrid}>
                  {([
                    { labelEn: 'Model Training Consent', labelIt: 'Consenso Addestramento Modelli', value: activeChange.aiTrainingOptOut, 
                      colorHigh: 'Not Allowed', colorMed: 'Opt-out available' },
                    { labelEn: 'Scraping / Crawling Restrictions', labelIt: 'Restrizione Scraper / Crawling', value: activeChange.aiDataScrapingRestricted, 
                      colorHigh: '', colorMed: '' },
                    { labelEn: 'IP Ownership Inputs/Outputs', labelIt: 'Proprieta Intellettuale Inputs/Outputs', value: activeChange.aiIpLicensing, 
                      colorHigh: 'Claimed by company', colorMed: '' },
                    { labelEn: 'Prompt Data Retention', labelIt: 'Conservazione Dati Prompt', value: activeChange.aiPromptRetention, 
                      colorHigh: '', colorMed: '' },
                  ]).map((item, idx) => (
                    <div key={idx} className={styles.govCard}>
                      <span className={styles.govLabel}>{lang === 'it' ? item.labelIt : item.labelEn}</span>
                      <span className={styles.govValue} style={{
                        color: item.value === item.colorHigh ? 'var(--risk-high)' :
                               item.value === item.colorMed ? 'var(--risk-medium)' :
                               item.value === 'Restricted' || item.value === 'Protected' || item.value === 'Allowed' || item.value === 'System-deleted' ? 'var(--risk-low)' :
                               'var(--secondary)'
                      }}>
                        {item.value}
                      </span>
                    </div>
                  ))}
                </div>

                <div className={styles.infoBox}>
                  <Info size={24} color="var(--secondary)" style={{ flexShrink: 0 }} />
                  <p className={styles.infoText}>
                    {lang === 'it' 
                      ? 'Questo pannello evidenzia le clausole specifiche relative ai diritti sui dati per l\'addestramento di modelli di intelligenza artificiale. L\'analisi aiuta le aziende a mitigare il rischio di leak di segreti industriali e violazione del copyright (inclusa la conformita con l\'EU AI Act).'
                      : 'This panel extracts terms relating to user-submitted data usage for training foundational AI models. This audit enables corporations to secure their IP and align with the European AI Act guidelines.'}
                  </p>
                </div>
              </div>
            )}

            {/* TAB 3: RISK TRENDS */}
            {activeTab === 'trends' && (
              <div>
                <h3 className={styles.sectionTitle}>
                  <Activity size={18} color="var(--primary)" /> {lang === 'it' ? 'Evoluzione Storica del Rischio' : 'Historical Risk & Impact Trends'}
                </h3>

                <div className={styles.chartGrid}>
                  {/* Real historical trend (aggregated via /api/trends) */}
                  <RiskTrendPanel companyId={policy.companyId} lang={lang} />

                  {/* Bar Chart: Risk Profile Vectors (data-driven) */}
                  <div className={styles.chartCard}>
                    <span className={styles.chartTitle}>
                      <Shield size={16} color="var(--secondary)" />
                      {lang === 'it' ? 'Vettori Rischio Attivi (%)' : 'Active Risk Profile Vectors (%)'}
                    </span>
                    <div className={styles.chartWrapper}>
                      <div className={styles.histogram}>
                        {riskProfileData.map((bar, idx) => (
                          <div key={idx} className={styles.barContainer}>
                            <span className={styles.barValue}>{bar.value}%</span>
                            <div className={styles.barTrack}>
                              <div 
                                className={styles.barFill} 
                                style={{ 
                                  height: `${bar.value}%`,
                                  background: `linear-gradient(to top, ${getBarColor(bar.value)}, ${getBarColor(bar.value)}88)`
                                }} 
                              />
                            </div>
                            <span className={styles.barLabel}>
                              {lang === 'it' ? bar.labelIt : bar.labelEn}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* TAB 4: REMEDIATIONS */}
            {activeTab === 'remediations' && (
              <div>
                <h3 className={styles.sectionTitle}>
                  <Award size={18} color="var(--secondary)" /> {lang === 'it' ? 'Raccomandazioni e Piano di Rimedio' : 'Actionable Remediations & Tips'}
                </h3>
                
                <div className={styles.remList}>
                  {getRemediations().length > 0 ? (
                    <RemediationSteps
                      remediationsJson={activeChange.remediationsJson}
                      lang={lang}
                    />
                  ) : (
                    <div className={styles.emptyTab}>
                      <p>
                        {lang === 'it' 
                          ? 'Nessun rimedio specifico richiesto per questa versione. I termini sono stabili.' 
                          : 'No specific remediations are required for this snapshot.'}
                      </p>
                    </div>
                  )}
                </div>
              </div>
            )}
          </div>
        ) : (
          <div className={styles.emptyTab}>
            <p>
              {lang === 'it' 
                ? 'Nessun cambiamento registrato per questa policy.' 
                : 'No changes registered for this policy.'}
            </p>
          </div>
        )}

        {/* SOURCES TAB -- shows all monitored documents for this company */}
        {activeTab === 'sources' && (
          <div className={styles.tabContent}>
            <h3 className={styles.sectionTitle}>
              <Globe size={18} color="var(--primary)" /> {lang === 'it' ? 'Documenti Monitorati per ' : 'Monitored Documents for '}{policy.company.name}
            </h3>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '16px', lineHeight: 1.5 }}>
              {lang === 'it'
                ? 'Tutti i documenti di policy ufficiali attualmente tracciati da PolicyWatcher per questa azienda, con il link alla fonte e alla versione archiviata su Wayback Machine.'
                : 'All official policy documents currently tracked by PolicyWatcher for this company, with links to the source and the archived version on the Wayback Machine.'}
            </p>

            <div className={styles.archiveList}>
              {(policy.siblingPolicies || []).map((sib) => {
                const lastSnap = sib.snapshots[0];
                const lastScanDate = lastSnap
                  ? new Date(lastSnap.createdAt).toLocaleDateString(lang === 'it' ? 'it-IT' : 'en-US', { day: 'numeric', month: 'long', year: 'numeric' })
                  : (lang === 'it' ? 'Mai scansionato' : 'Never scanned');
                const version = lastSnap?.version || 0;
                const isCurrent = sib.id === policy.id;
                const waybackUrl = `https://web.archive.org/web/*/${sib.url}`;
                const typeLabel = sib.type === 'privacy' ? 'Privacy' : sib.type === 'terms' ? 'Terms' : sib.type === 'ai' ? 'AI' : sib.type === 'aup' ? 'AUP' : sib.type;

                return (
                  <div key={sib.id} className={styles.archiveCard} style={isCurrent ? { borderLeft: '3px solid var(--primary)' } : {}}>
                    <div className={styles.archiveCardHeader} style={{ cursor: 'default' }}>
                      <div className={styles.archiveCardMeta}>
                        <span className={styles.archiveVersion}>
                          {sib.name}
                          <span style={{ marginLeft: 8, fontSize: '0.7rem', padding: '2px 8px', borderRadius: 4, background: 'var(--bg-tertiary)', color: 'var(--text-muted)' }}>{typeLabel}</span>
                          <span style={{ marginLeft: 6, fontSize: '0.7rem', padding: '2px 8px', borderRadius: 4, background: 'var(--bg-tertiary)', color: 'var(--text-muted)' }}>{sib.jurisdiction}</span>
                          {isCurrent && (
                            <span className={styles.currentBadge}>
                              {lang === 'it' ? 'Stai guardando' : 'Viewing'}
                            </span>
                          )}
                        </span>
                        <span className={styles.archiveDate}>
                          V{version} | {lang === 'it' ? 'Ultimo scan:' : 'Last scan:'} {lastScanDate}
                        </span>
                      </div>
                    </div>
                    <div style={{ display: 'flex', gap: 8, padding: '8px 16px 12px', flexWrap: 'wrap' }}>
                      <a href={sib.url} target="_blank" rel="noreferrer" className={styles.archiveActionBtn}>
                        <ExternalLink size={14} />
                        {lang === 'it' ? 'Fonte ufficiale' : 'Official source'}
                      </a>
                      <a href={waybackUrl} target="_blank" rel="noreferrer" className={styles.archiveActionBtn}>
                        <Globe size={14} />
                        Wayback Machine
                      </a>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        {/* VERSION ARCHIVE TAB -- outside activeChange conditional */}
        {activeTab === 'archive' && (
          <div className={styles.tabContent}>
            <h3 className={styles.sectionTitle}>
              <Archive size={18} color="var(--primary)" /> {lang === 'it' ? 'Archivio Completo Versioni Policy' : 'Complete Policy Version Archive'}
            </h3>
            <p style={{ fontSize: '0.85rem', color: 'var(--text-muted)', marginBottom: '16px', lineHeight: 1.5 }}>
              {lang === 'it'
                ? 'Di seguito sono riportate tutte le versioni storiche del documento. Clicca su una versione per leggere il testo integrale.'
                : 'Below are all historical versions of this policy document. Click on a version to read the full text.'}
            </p>

            <div className={styles.archiveList}>
              {policy.snapshots.map((snapshot, idx) => {
                const isLatest = idx === 0;
                const isExpanded = expandedSnapshot === snapshot.id;
                const wordCount = snapshot.text.split(/\s+/).length;
                const date = new Date(snapshot.createdAt).toLocaleDateString(
                  lang === 'it' ? 'it-IT' : 'en-US',
                  { day: 'numeric', month: 'long', year: 'numeric' }
                );

                const handleCopySnapshot = () => {
                  navigator.clipboard.writeText(snapshot.text);
                  setCopiedSnapshotId(snapshot.id);
                  setTimeout(() => setCopiedSnapshotId(null), 2000);
                };

                return (
                  <div key={snapshot.id} className={`${styles.archiveCard} ${isExpanded ? styles.archiveCardExpanded : ''}`}>
                    <button
                      className={styles.archiveCardHeader}
                      onClick={() => setExpandedSnapshot(isExpanded ? null : snapshot.id)}
                      aria-expanded={isExpanded}
                    >
                      <div className={styles.archiveCardMeta}>
                        <span className={styles.archiveVersion}>
                          V{snapshot.version}
                          {isLatest && (
                            <span className={styles.currentBadge}>
                              {lang === 'it' ? 'Attuale' : 'Current'}
                            </span>
                          )}
                        </span>
                        <span className={styles.archiveDate}>{date}</span>
                        <span className={styles.archiveWordCount}>
                          {wordCount.toLocaleString()} {lang === 'it' ? 'parole' : 'words'}
                        </span>
                      </div>
                      {isExpanded ? <ChevronUp size={18} /> : <ChevronDown size={18} />}
                    </button>

                    {isExpanded && (
                      <div className={styles.archiveTextContainer}>
                        <div className={styles.archiveActions}>
                          <button onClick={handleCopySnapshot} className={styles.archiveActionBtn}>
                            <Copy size={14} />
                            {copiedSnapshotId === snapshot.id
                              ? (lang === 'it' ? 'Copiato!' : 'Copied!')
                              : (lang === 'it' ? 'Copia testo integrale' : 'Copy full text')}
                          </button>
                          <a href={policy.url} target="_blank" rel="noreferrer" className={styles.archiveActionBtn}>
                            <ExternalLink size={14} />
                            {lang === 'it' ? 'Apri fonte ufficiale' : 'Open official source'}
                          </a>
                          <a
                            href={`https://web.archive.org/web/${new Date(snapshot.createdAt).toISOString().replace(/[-:T]/g, '').substring(0, 14)}*/${policy.url}`}
                            target="_blank"
                            rel="noreferrer"
                            className={styles.archiveActionBtn}
                          >
                            <Globe size={14} />
                            Wayback Machine
                          </a>
                        </div>
                        <div className={styles.archiveFullText}>
                          {snapshot.text.split('\n').map((para, pIdx) => (
                            para.trim() ? <p key={pIdx}>{para}</p> : <br key={pIdx} />
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
