'use client';

/**
 * TermsGate - blocks access to the platform until the user explicitly
 * accepts the Terms of Use and the Beta disclaimer.
 *
 * Persistence: the acceptance is stored in localStorage under
 * `policywatcher_terms_accepted_v1`. Bumping the suffix invalidates
 * previous acceptances (use when the terms text changes materially).
 *
 * Behaviour:
 *  - When NOT accepted: renders a full-screen gate and returns null for
 *    the children (the dashboard is NOT mounted).
 *  - When accepted: renders children normally.
 */
import { useEffect, useState } from 'react';
import { ShieldCheck, AlertTriangle, ExternalLink, Lock } from 'lucide-react';
import styles from './TermsGate.module.css';
import type { Lang } from '@/types';

const STORAGE_KEY = 'policywatcher_terms_accepted_v1';
/** Terms acceptance expires after 90 days (milliseconds). */
const ACCEPTANCE_TTL_MS = 90 * 24 * 60 * 60 * 1000;

/** Props for the {@link TermsGate} component. */
interface TermsGateProps {
  /** The application content that will only render after acceptance. */
  children: React.ReactNode;
  /** Active UI language — controls the terms copy and button labels. */
  lang: Lang;
  /** Toggles the language *before* acceptance (the gate renders its own toggle). */
  onLangToggle: () => void;
}

const content = {
  en: {
    badge: 'BETA RELEASE',
    title: 'Before you continue',
    subtitle:
      'PolicyWatcher is an experimental platform. Please read and accept the terms of use to access the dashboard.',
    termsTitle: 'Terms of Use & Disclaimer',
    terms: [
      'PolicyWatcher is in active development (beta) and does not represent a final product.',
      'All assessments are purely indicative, generated by an automated (AI) analysis of publicly available policy texts as of the screening date.',
      'They do NOT constitute legal advice, compliance certification, binding judgment, or a definitive assessment of corporate conduct in any way.',
      'Values may contain inaccuracies, interpretive errors, or omissions, and may not reflect all corporate practices, confidential agreements, or subsequent updates.',
      'The author and the platform disclaim all liability for any decisions, actions, or omissions based on this information.',
      'The interpretation and use of the data is solely at your own risk and responsibility. Always consult official sources and qualified legal counsel.',
    ],
    checkbox:
      'I have read and accept the Terms of Use and acknowledge the Beta disclaimer.',
    acceptBtn: 'Accept & Continue',
    declineBtn: 'Decline',
    footer: 'By accepting, you acknowledge this is not legal advice.',
    langToggle: 'Italiano',
  },
  it: {
    badge: 'VERSIONE BETA',
    title: 'Prima di continuare',
    subtitle:
      'PolicyWatcher è una piattaforma sperimentale. Leggi e accetta i termini di utilizzo per accedere alla dashboard.',
    termsTitle: 'Termini di Utilizzo & Disclaimer',
    terms: [
      'PolicyWatcher e in fase di sviluppo (beta) e non rappresenta un prodotto finale.',
      'Le valutazioni sono puramente indicative, generate da un\'analisi automatizzata (AI) di testi di policy pubblicamente disponibili alla data dello screening.',
      'NON costituiscono in alcun modo parere legale, certificazione di conformità, giudizio vincolante o valutazione definitiva della condotta aziendale.',
      'I valori possono contenere imprecisioni, errori interpretativi o omissioni e possono non riflettere tutte le pratiche aziendali, gli accordi riservati o gli aggiornamenti successivi.',
      'L\'autore e la piattaforma declinano ogni responsabilità per decisioni, azioni o omissioni basate su queste informazioni.',
      'L\'interpretazione e l\'uso dei dati sono esclusivamente a carico e sotto la responsabilità dell\'utente. Consulta sempre le fonti ufficiali e un consulente legale qualificato.',
    ],
    checkbox:
      'Ho letto e accetto i Termini di Utilizzo e riconosco il disclaimer Beta.',
    acceptBtn: 'Accetta & Continua',
    declineBtn: 'Rifiuta',
    footer: 'Accettando, riconosci che questo non è un parere legale.',
    langToggle: 'English',
  },
};

/**
 * Full-screen gate that blocks access to the dashboard until the user
 * explicitly accepts the Terms of Use and Beta disclaimer.
 *
 * On acceptance, persists a flag to `localStorage` (`policywatcher_terms_accepted_v1`)
 * so returning visitors bypass the gate automatically.
 *
 * @param props - {@link TermsGateProps}
 * @returns The children if accepted, the gate overlay if not, or `null` during hydration.
 */
export default function TermsGate({ children, lang, onLangToggle }: TermsGateProps) {
  const [accepted, setAccepted] = useState<boolean | null>(null);
  const [checked, setChecked] = useState(false);
  const [showError, setShowError] = useState(false);

  // Read acceptance from localStorage on mount (client-only).
  // Checks both presence and TTL expiry (90 days).
  useEffect(() => {
    try {
      const v = localStorage.getItem(STORAGE_KEY);
      if (v) {
        const timestamp = parseInt(v, 10);
        if (!isNaN(timestamp) && Date.now() - timestamp < ACCEPTANCE_TTL_MS) {
          setAccepted(true);
          return;
        }
        // Expired or invalid: clear and re-prompt
        localStorage.removeItem(STORAGE_KEY);
      }
      setAccepted(false);
    } catch {
      // localStorage unavailable (SSR / privacy mode): default to not accepted
      setAccepted(false);
    }
  }, []);

  /**
   * Persists acceptance and unmounts the gate.
   * Requires the checkbox to be checked; shows an inline error otherwise.
   */
  const handleAccept = () => {
    if (!checked) {
      setShowError(true);
      return;
    }
    try {
      // Store acceptance timestamp for TTL expiry (90 days)
      localStorage.setItem(STORAGE_KEY, Date.now().toString());
    } catch {
      /* ignore write errors */
    }
    setAccepted(true);
  };

  // While we haven't read localStorage yet, render nothing (avoid flashing
  // the gate to users who already accepted).
  if (accepted === null) return null;

  if (accepted) return <>{children}</>;

  const t = content[lang];

  return (
    <div className={styles.overlay}>
      {/* Lang toggle */}
      <button onClick={onLangToggle} className={styles.langToggle}>
        {t.langToggle}
      </button>

      <div className={styles.card}>
        {/* Badge */}
        <div className={styles.badge}>
          <AlertTriangle size={13} />
          {t.badge}
        </div>

        {/* Header */}
        <h1 className={styles.title}>
          <ShieldCheck size={28} className={styles.titleIcon} />
          {t.title}
        </h1>
        <p className={styles.subtitle}>{t.subtitle}</p>

        {/* Terms box */}
        <div className={styles.termsBox}>
          <div className={styles.termsHeader}>
            <Lock size={14} />
            {t.termsTitle}
          </div>
          <ul className={styles.termsList}>
            {t.terms.map((term, i) => (
              <li key={i} className={styles.termsItem}>
                <span className={styles.termsBullet}>{i + 1}</span>
                <span>{term}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Checkbox */}
        <label className={styles.checkboxRow}>
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => {
              setChecked(e.target.checked);
              if (e.target.checked) setShowError(false);
            }}
            className={styles.checkbox}
          />
          <span className={styles.checkboxLabel}>{t.checkbox}</span>
        </label>
        {showError && (
          <p className={styles.error}>
            {lang === 'it'
              ? 'Devi spuntare la casella per continuare.'
              : 'You must check the box to continue.'}
          </p>
        )}

        {/* Actions */}
        <div className={styles.actions}>
          <button
            onClick={handleAccept}
            className={`${styles.btn} ${styles.btnPrimary} ${!checked ? styles.btnDisabled : ''}`}
            disabled={!checked}
          >
            <ShieldCheck size={16} />
            {t.acceptBtn}
          </button>
        </div>

        <p className={styles.footer}>
          <ExternalLink size={11} />
          {t.footer}
        </p>
      </div>
    </div>
  );
}
