/**
 * @file Toast.tsx
 *
 * Application-wide toast notification system built on React Context.
 *
 * Architecture:
 *  - **ToastProvider** — wraps the app root, maintains the toast queue,
 *    and renders the fixed-position container.
 *  - **useToast()** — hook that exposes `addToast` and `removeToast`
 *    to any descendant component.
 *  - **ToastItem** — individual notification card with auto-dismiss timer,
 *    animated progress bar, and manual close button.
 *
 * Supports four severity levels: success, error, warning, info.
 * Each level maps to a distinct icon and colour accent.
 */
'use client';

import React, {
  createContext,
  useContext,
  useState,
  useCallback,
  useRef,
  useEffect,
} from 'react';
import { CheckCircle2, XCircle, AlertTriangle, Info, X } from 'lucide-react';
import styles from './Toast.module.css';

// -- Types --

/** Severity level of a toast notification. */
type ToastType = 'success' | 'error' | 'warning' | 'info';

/** Data model for a single toast notification. */
interface Toast {
  /** Unique identifier (auto-generated by the provider). */
  id: string;
  /** Visual severity level. */
  type: ToastType;
  /** Bold headline displayed in the toast. */
  title: string;
  /** Optional body copy rendered below the title. */
  message?: string;
  /** Auto-dismiss delay in milliseconds (defaults to 5 000). */
  duration?: number;
}

/** Value exposed by the toast React Context. */
interface ToastContextValue {
  /** Enqueue a new toast notification. The `id` is auto-assigned. */
  addToast: (toast: Omit<Toast, 'id'>) => void;
  /** Immediately remove (dismiss) a toast by its `id`. */
  removeToast: (id: string) => void;
}

// -- Context --

const ToastContext = createContext<ToastContextValue | null>(null);

/**
 * Hook to access the toast notification system from any component.
 *
 * @throws If used outside of a {@link ToastProvider}.
 * @returns `{ addToast, removeToast }` functions.
 */
export function useToast(): ToastContextValue {
  const ctx = useContext(ToastContext);
  if (!ctx) {
    throw new Error('useToast must be used within a ToastProvider');
  }
  return ctx;
}

// -- Icon mapping --

const iconMap: Record<ToastType, React.ReactNode> = {
  success: <CheckCircle2 size={18} color="var(--risk-low)" />,
  error: <XCircle size={18} color="var(--risk-high)" />,
  warning: <AlertTriangle size={18} color="var(--risk-medium)" />,
  info: <Info size={18} color="var(--primary)" />,
};

const typeStyleMap: Record<ToastType, string> = {
  success: styles.toastSuccess,
  error: styles.toastError,
  warning: styles.toastWarning,
  info: styles.toastInfo,
};

/**
 * Renders a single toast card with icon, text, close button, and
 * an animated progress bar that counts down to auto-dismiss.
 *
 * @param props.toast    - The toast data to render.
 * @param props.onRemove - Callback to remove this toast from the queue.
 */
function ToastItem({
  toast,
  onRemove,
}: {
  toast: Toast;
  onRemove: (id: string) => void;
}) {
  const [exiting, setExiting] = useState(false);
  const timerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const duration = toast.duration ?? 5000;

  const handleClose = useCallback(() => {
    setExiting(true);
    setTimeout(() => onRemove(toast.id), 300);
  }, [onRemove, toast.id]);

  useEffect(() => {
    timerRef.current = setTimeout(handleClose, duration);
    return () => {
      if (timerRef.current) clearTimeout(timerRef.current);
    };
  }, [duration, handleClose]);

  return (
    <div
      className={`${styles.toast} ${typeStyleMap[toast.type]} ${exiting ? styles.toastExiting : ''}`}
      role="alert"
      aria-live="assertive"
    >
      <span className={styles.toastIcon}>{iconMap[toast.type]}</span>
      <div className={styles.toastBody}>
        <div className={styles.toastTitle}>{toast.title}</div>
        {toast.message && (
          <div className={styles.toastMessage}>{toast.message}</div>
        )}
      </div>
      <button
        className={styles.toastClose}
        onClick={handleClose}
        aria-label="Dismiss notification"
      >
        <X size={14} />
      </button>
      <div
        className={styles.toastProgress}
        style={{ animationDuration: `${duration}ms` }}
      />
    </div>
  );
}

/** Auto-incrementing counter for generating unique toast IDs. */
let toastCounter = 0;

/**
 * Context provider that manages the global toast queue.
 *
 * Wrap your app root (or layout) with this provider so that any child
 * component can call `useToast().addToast(...)` to show notifications.
 *
 * @param props.children - The application tree.
 */
export function ToastProvider({ children }: { children: React.ReactNode }) {
  const [toasts, setToasts] = useState<Toast[]>([]);

  const addToast = useCallback((toast: Omit<Toast, 'id'>) => {
    const id = `toast-${++toastCounter}-${Date.now()}`;
    setToasts((prev) => [...prev, { ...toast, id }]);
  }, []);

  const removeToast = useCallback((id: string) => {
    setToasts((prev) => prev.filter((t) => t.id !== id));
  }, []);

  return (
    <ToastContext.Provider value={{ addToast, removeToast }}>
      {children}
      <div className={styles.toastContainer} aria-label="Notifications">
        {toasts.map((toast) => (
          <ToastItem key={toast.id} toast={toast} onRemove={removeToast} />
        ))}
      </div>
    </ToastContext.Provider>
  );
}
